### ISSUE TITLE
Dependency Injection in Node

### ISSUE THREAD

**Issue by emilong** [sfnode/sfnode#10]
## Abstract

Dependency injection (DI) is a popular pattern in Java, C#, and even in Angular, but is not often used in backend Node applications. This talk will discuss the pattern in general, how most Node developers are getting their dependencies now, and how DI might make your life easier, especially with larger applications. We'll present illustrative examples using the open-source [bottlejs](https://github.com/young-steveo/bottlejs) module.

(Related to, but expanding upon, this blog post, https://engineering.haus.com/declarative-dependencies-for-unit-testing-node-js-services-45542ceb5703#.bzc2nhnqn)

## Speaker

Emil Ong [@OngEmil](https://twitter.com/OngEmil)

Emil is the Head of Engineering at [Haus](https://haus.com) where he works on a fullstack JS application, backed by Node. Outside of coding, he enjoys Japanese candy, independent movies, and meditation.

### Other

- **Are you going to be live coding?** Nope
- **Do you need audio from your computer?** Nope

**Comment by paulgrock** [comment]
HI @emilong. Thanks for the talk submission. We're still looking for someone to present at the September event next Thursday, the 1st. Are you interested/available to present that night?

**Comment by emilong** [comment]
@paulgrock Yup! That works great for me.

**Comment by paulgrock** [comment]
@emilong Awesome! I've added your talk details to the [meetup page](http://www.meetup.com/sfnode/events/225747576/). Let me know if anything needs updated.

**Comment by emilong** [comment]
Looks good. Thanks!

**Comment by paulgrock** [comment]
Hey @emilong. Thanks for speaking last night. Could you post a link to your slides on here so we can share them with the rest of the community?

**Comment by emilong** [comment]
Thanks @paulgrock! There's a repo here with the Spectacle slides and a sample project showing the technique I described: https://github.com/haus-inc/sfnode-sept2016-di

**Comment by paulgrock** [comment]
Awesome! Thanks again for presenting last night, @emilong!

**Comment by paulgrock** [comment]
Is there a place that people can view the slides online without cloning/npm installing this repo?

**Comment by emilong** [comment]
Yes! Apparently it's really easy to publish to surge.sh with Spectacle, so I have done 😄 : http://sfnode-sept2016-di.surge.sh/

**Comment by paulgrock** [comment]
Fantastic. Thank you.

**Comment by emilong** [comment]
Thank you! Thanks for hosting!
