### ISSUE TITLE
Talk Proposal: Your Sh*t Doesn't Work in Africa

### ISSUE THREAD

**Issue by Chuloo** [sfnode/sfnode#100]
## Talk
With the rapid growing tech ecosystem in Africa is mind, let's talk about why applications perform poorly in these parts and how they can do better. This talk will be focused majorly on web performance bottlenecks, performance tips to mitigate them and insights on the growing developer ecosystem in Africa generally.

## About William
William is a developer, developer advocate and technical writer passionate about building communites and travelling. He currently builds developer communities at Andela and writes technical articles on [Scotch.io](https://scotch.io/@chuloo). He is passionate about all things JavaScript, Web Performance, JAMStack, good food and great jokes. 
Twitter: [@iChuloo](https://twitter.com/iChuloo)

## Logistics
- URL to slides will be shared later.
- No live coding.
- No audio from computer required

**Comment by Trewaters** [comment]
Thanks for opening this issue. We look forward to your talk!
