### ISSUE TITLE
Talk proposal: A GraphQL guide for backend developers

### ISSUE THREAD

**Issue by engfragui** [sfnode/sfnode#101]
### Talk abstract

There’s a lot of information out there about GraphQL, and most of it focuses on the benefits that this technology brings to developers building web and mobile applications. 

But wait. What about backend developers? How do things look from their perspective? Can GraphQL help them be more efficient and improve their day-to-day work?

In this talk, I would like to illustrate some of the benefits (and the not-so-good parts) of GraphQL from the perspective of a backend developer like myself, and also share some of the lessons and best practices I’ve learned while working with GraphQL.

At the end, you’ll want to try GraphQL out if you haven’t done so already, and you’ll also be able to convince your backend developer friends to do the same!

### About the speaker

[Francesca Guiducci](https://twitter.com/engfragui)

Francesca is a software engineer, a tech conference goer, a tea drinker, a cat mum, and a wife. 
Among other things, she’s very passionate about women in engineering, GraphQL, work-life balance, self-improvement, and continuous learning.

She grew up in Italy eating pasta twice a day and loving it! Since she moved to San Francisco few years ago, she has been on a quest to try out all the Italian restaurants in the Bay Area and find the very best.

She recently joined the API team at Pinterest, where she got reacquainted with her first love, Python. Before Pinterest, she was at Trulia working on APIs and, you guessed it, GraphQL.

### Logistics

- Slides: https://github.com/engfragui/graphql-for-backend-devs-talk (will be uploaded on the day of the talk)
- I will not do live coding. I’ll interact with the GraphiQL UI in the browser.
- I don’t need to play audio from my computer.

**Comment by Trewaters** [comment]
Thanks for opening this issue. We would love to have you talk in March!

@paulgrock
