### ISSUE TITLE
Talk Proposal: Chronos - An Event Data Capturing System for Greenfield Applications

### ISSUE THREAD

**Issue by sashaProdan** [sfnode/sfnode#102]
#### Chronos - An Event Data Capturing System for Greenfield Applications

In our digital world a lot of real-time activity now happens in the web space. This activity can be analyzed and provide useful insights for making the right decisions and creating efficient strategies for the future at early stages of application development. There are a lot of existing analytics solutions, however their setup and use might not be well suited for greenfield applications. 

In this talk I will introduce you to Chronos project and existing solutions for real-time analytics. You’ll learn about event data and technologies we used to make a process of setting up and using analytics easy for a greenfield developer.

#### About Alexandra Prodan 
Alexandra is a software engineer who loves to solve real world problems and explore new tools and technologies. She is also a co-creator of Chronos which was built using Node.js, Apache Kafka and deployed via Docker.

**Personal website**
https://sashaprodan.github.io/

**Url to slides is** [here](https://docs.google.com/presentation/d/18rKsbcAf4aFXK9rc7jdhih6_UIlJ9omZXTOkFTTOnLQ/edit#slide=id.g4a8f743382_0_55)

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Thanks for opening and issue. Currently our next available speaking date would be June 2019. Are you available on June 6th?

**Comment by sashaProdan** [comment]
Yes I am available on June 6th. Is there a time limit for each event?

**Comment by Trewaters** [comment]
Yes. Each speaker gets 30 minutes. We use that time to set up the laptop too.

**Comment by sashaProdan** [comment]
Ok. Thanks.

**Comment by Trewaters** [comment]
Hi @sashaProdan I understand you might be able to speak May 2nd instead. I am waiting a couple days to make sure issue #90 doesn't want that date.  With all communication going back and forth I want to give everyone a fair chance.

If I don't hear back from them by the end of the weekend I will move your talk to May. I will post later when I know more. Have a great weekend!

**Comment by sashaProdan** [comment]
Hi @Trewaters. Yes I wouldn't mind to give a talk earlier as my friend told me she couldn't make it. But I understand that you have to work it out with other presenter first. Thanks for your help!

**Comment by Trewaters** [comment]
I moved this talk to May. I will be in touch when the event gets closer.

**Comment by sashaProdan** [comment]
Do you by the chance know the approximate talk day? Is it later then May the 1st?

**Comment by paulgrock** [comment]
Our May event is on the 2nd.

**Comment by sashaProdan** [comment]
Ok 👍 thanks

**Comment by Trewaters** [comment]
Hi @sashaProdan 
I apologize for being late on this check-in. I am updating the event details today with Venue (GitHub) and speaker details. We have three speakers. I think the first two Dshaw and James will be talking together. But I will know more soon.

Are you ready to speak next week? Do you have any questions for us?

Look forward to your talk!

**Comment by sashaProdan** [comment]
Hi @Trewaters 

No worries. I am ready to speak. I just saw the event details on SFNode meetup page and it looks like I have 30 min for my talk. Am I correct? I just want to confirm that so I can adjust my speed and content before the talk. 

And is it all right that I come at 7 since I start speaking at 7:30? Does setup takes to much time?

Thank you!

**Comment by Trewaters** [comment]
Great! @sashaProdan 

Yep it is 30 minutes for your speaking slot.

7 pm will be fine. They have a security desk that will be open for you to check in. GitHub does have a good sound system. It should be a smooth process to get you connected, maybe 5 minutes.

**Comment by sashaProdan** [comment]
Will the event be recorded?

**Comment by Trewaters** [comment]
We are trying too get it recorded or streamed. Will that be okay?

**Comment by sashaProdan** [comment]
Sure. I was just wondering ))

I am looking forward to the event!

**Comment by Trewaters** [comment]
Thanks for your talk!

Here is a link to the YouTube recording from that night ( https://youtu.be/lcKrqk9NDiQ ).
