### ISSUE TITLE
Talk Proposal: WTF Are Serverless Apps?

### ISSUE THREAD

**Issue by ErickWendel** [sfnode/sfnode#103]
WTF Are Serverless Apps?

Many myths and histories are created every day about the Serverless architectures and concepts. Maybe because of the attractive price,  availability metrics or the power to scale apps without additional configurations. Attendees will learn how to start in the serverless applications based and how to avoid surprises at the end of the month with high prices on their credit cards. 

About Erick Wendel

Erick Wendel is a Speaker, Software Consultant and community Co-organizer in Brazil. Named by Microsoft as Most Valuable Professional, and by Google as Google Developer Expert, a specialist in Node.js and Javascript Applications. He is a Software Independent Architect who helps companies to make better and cheaper applications using Serverless architectures, Container based applications, and Hybrid Cloud solutions. He has experience speaking and teaching at the biggest conferences in Brazil and Americas, working as voluntary Leader of NodeBR, Javascript São Paulo and Nerdzão Communities.

Talks: https://erickwendel.com
Facebook: https://fb.com/page.erickwendel
Twitter: [https://twitter.com/erickwendel_](https://twitter.com/erickwendel_)

Live coding:
Yes

Audio:
no audio needed

**Comment by Trewaters** [comment]
I am closing this issue since issue #104 is the one you are presenting in April.
