### ISSUE TITLE
Talk Proposal: Building VSCode Extensions with TypeScript

### ISSUE THREAD

**Issue by ErickWendel** [sfnode/sfnode#104]
**Building VSCode Extensions with TypeScript**

Productivity, good project delivery, and Code review are words that can scare many software developers. Maybe because of the delivery time or project complexity.  This talk will show you how to create visual studio code snippets, extensions, and tools using TypeScript.  Attendees will learn how to be more productive and how to change their mindset to think focused on business less than only code :D

About Erick Wendel

Erick Wendel is a Speaker, Software Consultant and community Co-organizer in Brazil. Named by Microsoft as Most Valuable Professional, and by Google as Google Developer Expert, a specialist in Node.js and Javascript Applications. He is a Software Independent Architect who helps companies to make better and cheaper applications using Serverless architectures, Container based applications, and Hybrid Cloud solutions. He has experience speaking and teaching at the biggest conferences in Brazil and Americas, working as voluntary Leader of NodeBR, Javascript São Paulo and Nerdzão Communities.

Talks: https://erickwendel.com
Facebook: https://fb.com/page.erickwendel
Twitter: [https://twitter.com/erickwendel_](https://twitter.com/erickwendel_)

Live coding:
Yes

Audio:
no audio needed

**Comment by Trewaters** [comment]
@ErickWendel so great to hear from you. We would like if you can do this talk on April 4th. Does that work for you?

**Comment by ErickWendel** [comment]
Sure!! Count on me :D
