### ISSUE TITLE
Talk Proposal: Reactive Node.js with RxJS and Typescript!

### ISSUE THREAD

**Issue by ErickWendel** [sfnode/sfnode#105]
**Reactive Node.js with RxJS and Typescript!**

Reactive Programming solves many architecture problems by use of events. Inside Node.js ecosystem, we need to know about callbacks, promises and how the event-loop works to make a better workflow. Attendees will learn examples, common problems, and the concepts about Reactive programming techniques and how RxJS can help their lives to write better software. 

About Erick Wendel

Erick Wendel is a Speaker, Software Consultant and community Co-organizer in Brazil. Named by Microsoft as Most Valuable Professional, and by Google as Google Developer Expert, a specialist in Node.js and Javascript Applications. He is a Software Independent Architect who helps companies to make better and cheaper applications using Serverless architectures, Container based applications, and Hybrid Cloud solutions. He has experience speaking and teaching at the biggest conferences in Brazil and Americas, working as voluntary Leader of NodeBR, Javascript São Paulo and Nerdzão Communities.

Talks: https://erickwendel.com
Facebook: https://fb.com/page.erickwendel
Twitter: [https://twitter.com/erickwendel_](https://twitter.com/erickwendel_)

Live coding:
Yes

Audio:
no audio needed

**Comment by Trewaters** [comment]
I am closing this issue since issue #104 is the one you are presenting in April.
