### ISSUE TITLE
Talk Proposal: Introduction to GraphQL: What is GraphQL and how its designed to improve your team’s communication

### ISSUE THREAD

**Issue by shark-h** [sfnode/sfnode#106]
#### Introduction to GraphQL: What is GraphQL and how its designed to improve your team’s communication

In this talk, I will motivate how the process of API development and API integration is fraught with inefficiency that GraphQL was designed to streamline from the ground-up. In this unique introduction to GraphQL, we will cover the pros of GraphQL and its trade-offs that is ideal for developers looking for a rapid introduction to the why, what and how of GraphQL. 
I was a GraphQL skeptic and this talk is inspired by my journey of understanding how GraphQL works, why it is such an important idea and what makes it better than things that came before it.

#### About Tanmai Gopal
Tanmai is the co-founder of hasura.io. He is a StackOverflow powered fullstack, polyglot developer whose areas of interest and work span across React, GraphQL, NodeJS, Python, Haskell, Docker, Postgres, Kubernetes. He is passionate about making it easy to build things and is the instructor of India's largest MOOC imad.tech with over 250,000 students.

Twitter profile: https://twitter.com/tanmaigo

**Are you going to be live coding?** 
Yes

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Do you think you might have availability in June, or later to give this talk?

**Comment by shark-h** [comment]
Hey, sorry for the delay. I will be out of SF for a while. I should be back around June/July but I'll only know around end of April. Can I reach out to you then and we can figure it out?

**Comment by Trewaters** [comment]
@shark-h Thanks for the update. You can definitely reach out to us in the future.

I will close this issue. Feel free to ask me to re-open it in the future or submit a new one if you come up with different topic.
