### ISSUE TITLE
Talk proposal: bcoin - Complete Bitcoin full node implementation written in JS

### ISSUE THREAD

**Issue by pinheadmz** [sfnode/sfnode#107]
### What
https://github.com/bcoin-org/bcoin
https://bcoin.io
@bcoin

### WHAT?!
bcoin is an open-source, complete implementation of the Bitcoin protocol written in JavaScript. We also maintain forks for Bitcoin Cash and Handshake (a new blockchain that will decentralize DNS and certificate authority and expand the TLD root zone). bcoin is written beautifully, very easy to read and a great way to learn about Bitcoin. We'll talk about its architecture (async/await, extending EventEmitters, levelDB, REST API, websockets, 100% dependency-free), how to run a node in Full, Pruned or SPV mode, and how to use individual modules from the library to make useful applications for nodejs, electron or the web browser. I also want to describe how easy it is to integrate bcoin into any nodejs application and just accept is a payment method! You don't have to be buying heroin on the dark web :-)

We are currently developing different user interface options which I could also talk about.

From the community we're looking for contributors, users, and developers curious about Bitcoin!

### Who
Presented by (me) Matthew Zipkin, Developer Advocate at bcoin.
matthew@purse.io
@matthewzipkin

### How
Probably just slides and maybe some live coding, HDMI or AirPlay screen share is fine, no audio.

**Comment by Trewaters** [comment]
We are currently scheduling talks for July. Would you be available to make this talk in July?

**Comment by pinheadmz** [comment]
Sounds good! Keep me posted! I think the last week of July I may be unavailable.

**Comment by Trewaters** [comment]
I am looking through our schedule. We are trying to figure a few things out.

I will get back to you in a few days but I would like you to hold July 11th for us. The July meetup will be on the 2nd Thursday because of the US Holiday.

**Comment by pinheadmz** [comment]
👍

**Comment by Trewaters** [comment]
@pinheadmz Would you be available to talk June 6th instead of July.

**Comment by Trewaters** [comment]
I made a mistake. I thought we had an opening in June but the venue will have a speaker so I would like to keep you in the July spot.

Sorry for the confusion @pinheadmz

**Comment by pinheadmz** [comment]
Ha, no problem! Keeping July 11 on the calendar :-) Thanks again!

**Comment by Trewaters** [comment]
I appreciate your understanding. Looking forward to a Crypto Currency talk!

**Comment by pinheadmz** [comment]
I'm starting to put together my presentation and I just wanted to confirm: I'll have about 30 min? You guys usually do two talks per meetup? And, do you have any idea how knowledgable the crowd is about Bitcoin? I can adjust on the fly (based on show-of-hands) but I'm trying to plan some time to explain the blockchain protocol a little bit as well.

**Comment by Trewaters** [comment]
The talks are 30 minutes. We have a good mix of folks, so I would say you don't have to explain the very basics of bitcoin, but whatever you feel is appropriate go for it.

There will be 2 talks that night yours and another.

**Comment by pinheadmz** [comment]
@Trewaters do you usually video the talks? If not I may bring my own camera

**Comment by Trewaters** [comment]
Good question. We don't have a way of recording the talks this month. I would suggest bringing your camera. We can work with you to post the video on our YouTube channel after the event
