### ISSUE TITLE
`nvm`: maintaining a version manager for node.js

### ISSUE THREAD

**Issue by ljharb** [sfnode/sfnode#11]
- Full name and Bio:
  - Jordan Harband
  - bio to come later
 - Talk title and abstract (description):
  - Maintaining a version manager for node.js
    - (or, if you think JS is hard, try coding in POSIX)

 - Make sure talk is true to the title and abstract: ok
 - Twitter handle (optional): [@ljharb](https://twitter.com/ljharb)
 - Other social profiles or personal blog (optional): [Github](http://ljharb.codes)
 - Url to slides or github (either now or can be posted in meetup comments later): later
 - Are you going to be live coding? : no
 - Do you need audio from your computer?: no
 - Add the proposal label to your issue: someone will have to do this for me

I'll fill this in with more detail as the month progresses; I'm unable to make it to the September meetup, but I'd like to speak at the October one.

**Comment by paulgrock** [comment]
Hey @ljharb are you still available to speak at the October event? The event details can be found http://www.meetup.com/sfnode/events/227074414/.

**Comment by ljharb** [comment]
@paulgrock yup!

**Comment by paulgrock** [comment]
@ljharb cool, I'll add your info to the meetup page. Do you have a bio you'd like me to use or should I just grab your twitter/github one?

**Comment by ljharb** [comment]
I'll try to write one up later this month; otherwise that one's just fine, thanks
