### ISSUE TITLE
Talk proposal: Progressive UX Design for Engineers

### ISSUE THREAD

**Issue by logandavis** [sfnode/sfnode#110]
**Progressive UX Design for Engineers**
Beyond delivering valuable features to users, engineers have a responsibility to respect their users' time by not making them wait for applications to process, load, or respond. This talk is an introduction to designing web applications that are not just _RESTful_ but also _respectful_, covering topics like:
- Optimistic rendering
- When to show a loading spinner
- Dogfooding in variable network conditions
- Building predictable interfaces
- Semantic correctness

For more, see [this blog post](https://engineering.mixmax.com/blog/progressive-ux-design-for-engineers).

**About Logan Davis**
Logan Davis is a software engineer at Mixmax, where he helps to give users half of their day back. Previously, he studied engineering with a concentration in computing at Olin College of Engineering. He loves stories, baseball, improv comedy, and exploring — preferably with nothing even resembling a plan.

**Other**
- Twitter: @logankeahidavis
- Linkedin: logankeahidavis
- Blog: https://engineering.mixmax.com/blog
- No live coding or audio from computer required

**Comment by Trewaters** [comment]
Thanks for submitting the talk. I have your space reserved for June.

**Comment by Trewaters** [comment]
Are you ready for tomorrow? I am here for questions. 

Please post a comment to confirm you are on for tomorrow.

We are meeting at Mixmax. We expect folks to arrive at 6:30 pm. Pizza and soda is being provided.

**Comment by logandavis** [comment]
I'm ready!
