### ISSUE TITLE
Talk proposal: Building a Data Pipeline for the Cloud

### ISSUE THREAD

**Issue by jacobleecd** [sfnode/sfnode#111]
Hi all,
I'd like to propose a talk.

**Full name & bio:** Jacob Coker-Dukowitz
Jake is a software engineer with experience in web application development, React JS, Node JS, Ruby on Rails, facilitation and project management.

**Talk title & Abstract:** Building a Data Pipeline for the Cloud
We'll talk about the challenges of building a cloud native application, the principles of building a good data pipeline for the cloud, and the design questions that came up while building Mashr.  

Mashr is an easy to use open source data pipeline framework that orchestrates moving data from external sources into a single destination database. It's meant for small software applications who have their data spread out in a variety of external sources which they want to be able to aggregate and perform analysis on.

Mashr works by launching a data pipeline in the cloud. With the command `mashr deploy` and a configuration file, a user can quickly get started integrating different sources of data (from REST api's, psql databases and more) into a single destination database for analysis. It uses Google Cloud Storage for backup and failover, Google Cloud Functions for loading data into BigQuery, and GCE instances hosting Embulk for plugin based bulk data loading. Mashr provides an easy to use CLI, is built with Node.js and uses Docker to host Embulk on the GCE instances.

Slides for the presentation will be finished in the next day or two, and I'll have a website and writeup up in the next week.

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Thanks for your talk submission. Would you be available for July 11th 2019? We have space then.

**Comment by jacobleecd** [comment]
July 11th works for me! Let me know if you'd like for me to send you the slides beforehand.

Best,
Jake

**Comment by Trewaters** [comment]
@jacobleecd would you be free to talk June 6th instead of July 11th. We have a space open for June because another speaker needed to reschedule.

**Comment by Trewaters** [comment]
@jacobleecd I apologize but I am having some serious scheduling issues. I am trying to double book folks all summer. A speaker needed to change their date and I am not processing it properly. I had to look at the issue list multiple times to make sure I get it right this time.

It looks like our next opening September 5th, 2019. I know I asked you for the dates you agreed too but I didn't realize I was overbooking at the time. If there is another month that works better (after August) please let me know.

**Comment by jacobleecd** [comment]
Hey @Trewaters ,
No worries! I'm free both June 6th or September 5th. The earlier the better for me, but I'll make whatever time works for ya'll.

FYI, here is a link to the [slides](https://drive.google.com/file/d/1q-D7GsYzVcXkoTTQUCL43FzQVIJD0HnH/view?usp=sharing) and the [website](https://mashr-framework.github.io/). There are a few minor tweaks I plan to make but they are just about done!

Best,
Jake

**Comment by Trewaters** [comment]
Hi, I am checking in to see if you are ready to talk September 5th. Please post here to confirm you are still okay to give a talk.

Thanks,
Tre'

**Comment by jacobleecd** [comment]
Hi Tre’,
I’m really sorry but my schedule has picked up a bunch and I can no longer make the commitment for Sept 5th, and I’m not sure when I’ll be able to reschedule just yet. I hope this doesn’t leave y’all hanging.

**Comment by Trewaters** [comment]
I meant to close this proposal before now. When you are ready just resubmit the Talk. We would love to have you speak in the future.
