### ISSUE TITLE
Talk proposal: A deep dive into performance diagnostics for Elasticsearch with PerfTop and Open Distro for Elasticsearch

### ISSUE THREAD

**Issue by JainKartavya** [sfnode/sfnode#113]
**TITLE:**
A deep dive into performance diagnostics for Elasticsearch with PerfTop and Open Distro for Elasticsearch
 
**ABSTRACT:**
PerfTop is a new NodeJS tool from AWS to model and troubleshoot the performance of Elasticsearch. PerfTop can help achieve better deployment of highly efficient and reliable Elasticsearch services.
 
PerfTop comes packaged with Open Distro For Elasticsearch. It provides pre-configured dashboards to analyze cluster, node, and shard performance. It also provides metrics for the operation of Elasticsearch clusters to help diagnose a variety of problems.  
 
This talk will walk through the design and implementation of PerfTop. We will also do a live demo using PerfTop with Open Distro’s Performance Analyzer, showing how to troubleshoot cluster issues. Finally, we will identify ways you can contribute to this high impact open source project.
 
**SPEAKERS:** 
**Alolita Sharma**
Alolita Sharma is a Principal Technologist at AWS. Currently, she drives open source strategy and developer contributions for open source projects such as Open Distro for Elasticsearch. Two decades of doing open source continue to inspire her. Alolita has built and led engineering teams at Wikipedia, Twitter, PayPal and IBM. Alolita is passionate about language technologies that enable everyone to participate in the Web’s information revolution. She serves on the board of Unicode Consortium and is an invited expert on W3C and ECMA workgroups. She has served on the boards of the OSI and SFLC.in. You can find her on Twitter @alolita.

**Comment by JainKartavya** [comment]
Thanks for scheduling this session in Sep. I have a couple of questions:
1. When would we know the exact meetup date in Sep?
2. When would the event page go live? I'd like to promote it on social channels.

**Comment by Trewaters** [comment]
This meetup is September 5th 2019.

The event has a placeholder now, found here (https://www.meetup.com/sfnode/events/mxstsmyzmbhb/). We usually have the exact details filled in about 2 weeks ahead of the event. So by  August 22nd it would be safe to share with the world and link to.

**Comment by JainKartavya** [comment]
Please remove Anna Jung from the speaker list. Alolita Sharma will be the only speaker.

**Comment by Trewaters** [comment]
I will try to track this but please double check me when the event goes up.

**Comment by Trewaters** [comment]
Hi, I am checking in to see if you are ready to talk September 5th.  I haven't updated the meetup description yet but I will after confirming our line up for the night.

Please post here to confirm you are still okay to give a talk.

Thanks,
Tre'

**Comment by JainKartavya** [comment]
Hi - I will check with the speaker "Alolita Sharma" and confirm tomorrow.

**Comment by Trewaters** [comment]
sounds good, Thanks!

**Comment by JainKartavya** [comment]
Yes, September 5 works for us. Can you please confirm if Open Distro will be Talk 1 or Talk 2?

**Comment by Trewaters** [comment]
Thanks for your patience. 

Open Distro will have the first talk. I am working on the meetup description. It should be up by Friday morning.
