### ISSUE TITLE
Talk Proposal: Produce & Perform EDM right from the browser with Scribbletune, React, GraphQL and the WebAudio API.

### ISSUE THREAD

**Issue by walmik** [sfnode/sfnode#115]
**Full name and Bio**
Walmik Deshpande
Distinguished sprint monkey @PayPal. 
Sings in the bathvroom, plays guitars in the bedvroom, yawns in the boardvroom. Just vroom vroom vroom!

**Talk title and abstract (description)**
The browser has come a long way when it comes to building really powerful applications that are capable of processing rich media on the fly. Audio production is not far behind in this fantastic progress. Especially with the advent of audio web workers over script processor node, we have precise timing enabling us to build music production and performance applications that work entirely out of the browser. 

We ll go over techniques available to us today for producing & performing electronic dance music with free and open source JavaScript libraries. We ll build a fully functional web application and we ll do our best to bring the place down with sick, algorhythmic beats, builds and drops.

**Twitter handle**
_walmik

**Personal website**
walmik.info

**Url to slides or github**
scribbletune.com

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
Absoeffinlutely!

**Comment by Trewaters** [comment]
The working title is a bit long for us but everything looks great!

Thanks for adding this to the issue tracker

**Comment by walmik** [comment]
Cool, i shortened it :) @Trewaters

**Comment by walmik** [comment]
Ok made one minor change @Trewaters  (kept the size the same however).

**Comment by Trewaters** [comment]
Looking forward to the talk. If you have questions let me know.

**Comment by walmik** [comment]
Hi @Trewaters same here.. looking forward to it too! I had one quick question if you could find out.. Last time I spoke at Github, I had gotten a HDMI out. Would I be able to get HDMI out again? If so, I can get my main computer along (else will have to settle for an older mac book air)

**Comment by walmik** [comment]
Hi @Trewaters @paulgrock whenever you get a chance could you find out bout this query of mine?

**Comment by Trewaters** [comment]
@walmik sorry to leave you hanging on this. I was on vacation until last night.

I am getting on it now.

**Comment by Trewaters** [comment]
We will have an HDMI out for you to use. I have a bundle of HDMI adapters. Something will fit!

**Comment by walmik** [comment]
Thank you Tre, that helps. I too might have a HDMI to USB-C adapter and I try to get it along.

**Comment by Trewaters** [comment]
Fantastic talk! Glad we could host it at GitHub 👍
