### ISSUE TITLE
Talk Proposal: Osgood

### ISSUE THREAD

**Issue by tlhunter** [sfnode/sfnode#116]
**Full name and Bio**
**Thomas Hunter II**: Thomas is the author of Advanced Microservices and is a prolific public speaker with a passion for reducing complex problems into simple language and diagrams. His career includes working at Fortune 50's in the Midwest, co-founding a successful startup, and everything in between.
**Bryan English**: Bryan is a JavaScript and Rust developer with over a decade of professional software development experience. Node.js security is his current game. He is Software Engineer & Poutine Artist at Intrinsic and is a Node.js core collaborator.

**Talk title and abstract (description)**
**An Introduction to Osgood**: Osgood is a secure, fast, and simple platform for running JavaScript HTTP Servers (and will be open sourced before the talk). In this talk we'll look at some sample Osgood applications, discuss the constraints we considered while architecting it, take a quick peek at the underlying Rust source code, and demonstrate how the security policies can be used to protect an application from malicious code.

**Url to Slides or GitHub Repo**
WIP

**Social Media Info (Optional)**
https://twitter.com/intrinsic
https://github.com/IntrinsicLabs

**Are you going to be live coding?**
TBD

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
OMG! I was in a hurry and posted you as talking on July 11th. Will that work for you? Sorry about this.

I know we talked verbally but I didn't confirm and it has been 3 weeks so I understand if this won't work. I put you and Bryan on first. Please let me know if I should move you from July 2019.

Thanks!

**Comment by tlhunter** [comment]
@Trewaters I will get back with you tomorrow!

**Comment by Trewaters** [comment]
sounds good. I apologize for the lack of communication on my part.

**Comment by tlhunter** [comment]
No worries

**Comment by tlhunter** [comment]
@Trewaters We're able to present on 7/11 (-:

**Comment by Trewaters** [comment]
That is great news!

**Comment by Trewaters** [comment]
Thanks for the excellent talk! Definitely enjoyed it.
