### ISSUE TITLE
Talk Proposal: Building a Centralized Log Management Framework for Small Web Apps

### ISSUE THREAD

**Issue by 4g3m** [sfnode/sfnode#117]
Hello,

My talk proposal: Building a Centralized Log Management Framework for Small Web Apps

Full name & bio: Faazil Shaikh 
Faazil is a software engineer with experience in full-stack web applications, building with JavaScript, Ruby on Rails, React, and NodeJS.

Talk title & Abstract: Building a Centralized Log Management Framework for Small Web Apps

The talk will start about discovering about what a log is. We’ll talk about syslog as a standard and system, its variants and the challenges of building of a centralized logging system and why small web applications should be collecting all of this valuable data. We’ll talk about the design of centralized logging systems and cover the various types of solution within this space. We will discuss these ideas and how they helped form Crato.

Crato is an easy-to-use full-stack log management framework for small web apps. Crato Client is a Bash application on the client side that forwards logs to a central server. Crato is a centralized log management system built using Rsyslog, Node.JS, Apache Kafka, AWS S3 and InfluxDB. Crato Core processes, enriches the log and delivers it ultimately to AWS S3 Glacier and InfluxDB database.

Crato is built, deployed, and orchestrated with Docker. Crato offers a simple CLI interface on top of Docker to easily tail incoming logs, manage system services, and do additional work by attaching a shell to any Crato service. Crato is designed to fully help capture log data that they may be losing daily. In Crato, logs are aggregated and processed in a central Rsyslog server, transported and buffered in Kafka, before being picked up by a NodeJS consumer to be written to AWS S3 for long-term storage and InfluxDB for immediate querying.

Presentation slides and a write-up should be done by the end of this week.

Are you going to be live coding?  No

Do you need audio from your computer?  No

**Comment by Trewaters** [comment]
This looks good. Would you be able to do it in 20-25 minutes?

We have a space for September 5th. Would you be ready to talk then?

**Comment by 4g3m** [comment]
Hey Tre', I can do the talk then and and I will do my best to keep to the 25 minute limit. Do you need anything else on my end? If not, I'll reply on the thread by the end of this week with a writeup link. Is it okay if I post the slides around the day of the talk?

**Comment by 4g3m** [comment]
Or slides just sometime next week if not then?

**Comment by 4g3m** [comment]
Hey Tre', I do have the writeup now ready on the site [here](https://crato-logging.github.io/) and the slides are linked [here](https://docs.google.com/presentation/d/1lKlYi1R4z3b4C1Np9QiEaevj_z1d4JEyyfFb9CQolKo/) as well. These materials are mostly stable, but some some changes will be made between now and the meetup.

Please let me know if we can still confirm for September 5th.

**Comment by Trewaters** [comment]
We can confirm September 5th. I will update the meetup description by Friday morning. Slides don't need to be ready until the day of the talk.

**Comment by Trewaters** [comment]
Do you have a Twitter account we can share in the description? We could also put another social media profile if you prefer. This is a great way for people to follow up with you.

**Comment by 4g3m** [comment]
Sure. @cratodev on twitter.
