### ISSUE TITLE
Talk Proposal: How to Transform Slack Into a Workflow Command Center

### ISSUE THREAD

**Issue by jacoblee93** [sfnode/sfnode#120]
**Full name and Bio**
Hey, I'm Jacob Lee, the co-founder of Standard Library. As part of my job, I deal with APIs of all kinds on a daily basis. Slack, Stripe, Airtable, Twilio, AWS, coinmarketcap.com -- you name it, there's a good chance I've built with it! Before working on Standard Library, I worked on Google Photos as a web developer.

**Talk title and abstract (description)**
If you're an engineer in San Francisco, odds are you spend hours each day in Slack. This talk will focus on helping you maximize those hours by unlocking Slack's potential as a developer platform. 

We'll use Build on Standard Library to set up Node.js based workflows that combine different APIs into powerful pieces of functionality -- think creating Stripe invoices, gathering information on user signups with Clearbit, and, of course, sending cat GIFs to people who have had a hard day -- all triggerable via Slack. All the logic will be fully customizable, so the sky's the limit!

**Social Media Info (Optional)**
Twitter: https://twitter.com/hacubu

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by jacoblee93** [comment]
Hey @Trewaters! I can do the October 3rd meetup if there is space.

**Comment by Trewaters** [comment]
Awesome! We are still getting commitments from folks. The venue might have a speaker but I haven't heard for sure yet. 

Could I get back with you on Tuesday? Hopefully I will know more by then.

**Comment by jacoblee93** [comment]
Yup, no problem. Let me know!

**Comment by jacoblee93** [comment]
Hey @Trewaters, any updates?

**Comment by Trewaters** [comment]
Good morning @jacoblee93 

I would like to schedule your talk for November 7th. It sounds like the Venue has a speaker and issue #118 should be available. Just waiting for their confirmation.

I appreciate your patience. I should have been back with everyone on Monday. Time is not my friend ;)

**Comment by jacoblee93** [comment]
Totally understand, sounds good!

**Comment by Trewaters** [comment]
Would you believe we do have space in October. The other talk submission will be unable to appear. 

Are you still available? Sorry for all the back and forth @jacoblee93

**Comment by jacoblee93** [comment]
Yes, I am available and that would be great. Looking forward to it!

**Comment by Trewaters** [comment]
Yay that is awesome news! You will be out second speaker October 3rd.

I appreciate your patience with the process.

If you have any questions send them my way.

Happy Friday!

**Comment by jacoblee93** [comment]
Great! I do have one question: how long should I plan on making my talk?

**Comment by Trewaters** [comment]
Talks should be 25 minutes or less. There is some AV setup so this seems to work great.
