### ISSUE TITLE
Talk Proposal: Building a cloud-native GraphQL app with NodeJS & Hasura

### ISSUE THREAD

**Issue by coco98** [sfnode/sfnode#121]
**Full name and Bio**
Tanmai Gopal
Tanmai is a founder at Hasura (hasura.io), an open-source project to make data-access and eventing easy using GraphQL. He's a fullstack developer, with primary areas of interest and work spanning GraphQL, Kubernetes, Haskell and Javascript over the last few years. He used to be an instructor of one of the largest MOOCs in India, and is passionate about making it easier to build things!

**Talk title and abstract (description)**
**Title:**
Building a cloud-native GraphQL app with NodeJS & Hasura

**Abstract:**
GraphQL is the best gift you can give to your API consumers, but building a , high-performance, auto-scalable GraphQL backend is challenging! In this talk, I'm going to build a "cloud-native" GraphQL application. I will be using NodeJS, Hasura and Postgres to build out an application, with bits of live coding and demos. Along the way, I will also try to bring in architectural concepts around high-performance and extensible GraphQL, scalable realtime GraphQL and event-driven business logic to motivate the pros and cons of building an application like this.

**Url to Slides or GitHub Repo**
_Will add later_

**Social Media Info (Optional)**
https://twitter.com/tanmaigo

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Thanks so much for your patience! We look forward to hearing your talk.
