### ISSUE TITLE
Talk Proposal: Parts of OWASP Top 10 for Fullstack JS developpers

### ISSUE THREAD

**Issue by vdeturckheim** [sfnode/sfnode#122]
**Full name and Bio**
Vladimir de Turckheim works as a software engineer at Sqreen where he builds a tool to secure web applications. He used to be a professional security auditor and a web developer in agencies. He is one of the most active members of the Node.js Security Working Group where he handles the security of Node.js and its ecosystem.

**Talk title and abstract (description)**
### Parts of OWASP Top 10 for Fullstack JS developpers
The OWASP (Open Web Application Security Project) Top 10 is the reference document regarding the security of web applications.
Let's discover it from the point of view of a JavaScript Engineer.
Which vulnerabilities impact backend code? What about Frontend code?
For instance, did you know that there are three kinds of XSS? And one of them never reaches the server at all!

**Url to Slides or GitHub Repo**
TBA

**Social Media Info (Optional)**
https://twitter.com/poledesfetes

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Thanks for submitting. Would you be available on the 1st Thursday of December or January?

**Comment by vdeturckheim** [comment]
Hey @Trewaters, sadly I will be SF only in November.

**Comment by Trewaters** [comment]
I understand. Maybe next time you are visiting we could set something up.

**Comment by vdeturckheim** [comment]
Yes, I'll ping you back :)
