### ISSUE TITLE
Talk Proposal: Building a serverless SMS panic button

### ISSUE THREAD

**Issue by Xabadu** [sfnode/sfnode#123]
**Full name and Bio**
Fernando is the stylin’, profilin’, UI buildin’, web codin’, community leadin’, son of a gun! He is a Developer Evangelist at Twilio, organizer of NodeSchool SF, contributes to open source communities in the Bay Area and Latin America, bakes some mean 🍪 and constantly rants about wrestling and why it never makes sense but it's so freakin' great.

**Talk title and abstract (description)**
In an emergency such as an accident, an insecure situation, or a natural disaster, a successful response time is often measured in seconds. Communicating a call for help quickly is essential. If someone is unable to make a phone call or send a text message, a readily accessible panic button can enable them to make an urgent call for help discreetly and efficiently.

In this talk, I'll show you how to accomplish this by building a serverless SMS panic button to notify a list of emergency contacts with one single click.

**Social Media Info**
* Twitter: [@xabadu](https://twitter.com/xabadu)
* GitHub: [Xabadu](https://github.com/Xabadu)
* Website: [https://xabadu.dev](https://xabadu.dev)

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Are you available for December 5th at Flatiron School? Looking forward to hearing your talk

**Comment by Xabadu** [comment]
@Trewaters I am! Looking forward to doing it ✌️
