### ISSUE TITLE
Venue Proposal: Scoop

### ISSUE THREAD

**Issue by dcvidetta** [sfnode/sfnode#124]
Posting for Scoop. We do not have a date yet, please contact denise@takescoop.com to discuss the details and date you need venue for. 

**What is the address, floor, room name if any, entrance instructions?**
22 4th st, San Francisco, CA 94103

**Do we need to submit an attendee list for security purposes?**
Yes

**What's the total number of people that space can hold?**
60-70 

**Will food and drinks will be provided? Are there vegetarian and gluten free options?**
Yes, snacks and drinks will be provided with vegetarian and GF options

**What is the AV setup like?**
Open space room with 2 monitors and mics. 

**What is the microphone setup? Mic stand or headset mic?**
Both available

**What is the parking situation like? Is bike parking available? Any off-street parking?**
Hourly rate parking lot in the building, no street parking

**Comment by Trewaters** [comment]
Thank you for reaching out. I would be happy to coordinate with you to hold an event. I will connect with you next week to get something scheduled.
