### ISSUE TITLE
Talk Proposal: Type as much as you want

### ISSUE THREAD

**Issue by dkundel** [sfnode/sfnode#125]
**Full name and Bio**
Dominik Kundel

Dominik is a Developer Evangelist for Twilio in San Francisco. He has a passion for JavaScript, hackathons, teaching and good whiskey. You will usually find him speaking at meetups and conferences, mentoring at hackathons and workshops or working on open source projects. 

**Talk title and abstract (description)**
Type as much as you want

>We've all been there. You are working on a feature or bug in JavaScript, think you finally got it, run the code and there it is, it basically screams at you: "undefined is not a function". I love JavaScript but as my codebases for projects grow, certain pains appear again and again.

> In recent years TypeScript has gained popularity as a tool to avoid common pains when developing a growing web application.

> However, what if you already have a large JavaScript application? Adding types and moving to a new language can be cumbersum and frustrating.

> In this talk we'll go through ways how you can leverage the power of TypeScript without having to refactor your entire codebase and instead use features of TypeScript at your own pace. Slowly adding more features when YOU want to.

**Url to Slides or GitHub Repo**
[Slides of a lightning talk version of this talk](https://speakerdeck.com/dkundel/msdev-montreal-holiday-meetup-19-how-to-move-your-project-to-typescript)

**Social Media Info (Optional)**
_Twitter_: [@dkundel](https://twitter.com/dkundel)
_GitHub_: [dkundel](https://github.com/dkundel)
_Web_: [dkundel.com](https://dkundel.com)

**Are you going to be live coding?**
_Yes_

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Thanks for the talk submission. Would you be available to speak on January 9th, next week? Or would another month work better for you?

**Comment by dkundel** [comment]
Yes Thursday works! See you then.

**Comment by Trewaters** [comment]
Yay! I will update the meetup description today.
