### ISSUE TITLE
Talk Proposal: Implementing Async/Await with Generators and Promises

### ISSUE THREAD

**Issue by copperwall** [sfnode/sfnode#128]
**Full name and Bio**
Chris Opperwall

Chris is a Senior Software Engineer at Truepill. He's been a full-stack developer at Truepill, PayPal, and iFixit. In his free time he enjoys following twitter threads where people argue about `let` vs `const`.

**Talk title and abstract (description)**

Title: Implementing Async/Await with Generators and Promises

Abstract:

The async/await feature was introduced in ES2016 and has made it possible to write asynchronous code that looks synchronous. This feature improves code readability over callback and promise async patterns of before. But have you ever wondered how this can be implemented? This talk goes over how to implement async/await using generators and promises in ES2015.

**Url to Slides or GitHub Repo**
[Google Slides](https://docs.google.com/presentation/d/1xfTWsGfq6TL4e8aONcxuFsfLcITfR6lxAX5cA3a-hts/edit?usp=sharing)

**Social Media Info (Optional)**
Twitter: @copperwall
Github: @copperwall
Medium: https://medium.com/@copperwall
Site: https://www.copperwall.dev

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Thank you for submitting this talk. Would you be available for February 13th or March 12th? I still need to check with our February host to see if they have one speaker or two.

I will update you as I know more.

**Comment by copperwall** [comment]
Hey thanks! I’m definitely available for March. I have to head out somewhat early from the meetup on February 13th, so that might not work out the best.

**Comment by JoeDoyle23** [comment]
Great. We'll schedule you as a talk for March.

**Comment by copperwall** [comment]
Awesome!!

**Comment by isurfbecause** [comment]
@copperwall I know this is short notice, but would you be able to speak tomorrow night via Zoom?

**Comment by copperwall** [comment]
Sorry, I didn't see this yesterday. I can speak tonight if that still works!

**Comment by isurfbecause** [comment]
Right on, good timing.

**Comment by isurfbecause** [comment]
@copperwall jump on zoom https://zoom.us/j/510472047
