### ISSUE TITLE
Talk Proposal: How to test Node apps. The easy way.

### ISSUE THREAD

**Issue by artgo** [sfnode/sfnode#129]
**Full name and Bio**
Hey, I'm Artem Golubev, a co-founder of testRigor. As part of my job, I deal with acceptance-level testing of all kinds on a daily basis. Safeway/Albertsons, Salseforce, Stripe -- you name it, there's a good chance we tested them! I'm very passionate about more efficient ways to test apps. Before working on testRigor, I worked in various software dev jobs.

**Talk title and abstract (description)**
How to test Node apps. The easy way.

If you're an engineer in San Francisco, odds are you spend hours each day validating that the code works. This talk will focus on helping you reduce those hours by utilizing Behaviour-Driven Test Generation.

We will walk through how to use testrigor open source node plugin to record end-user behavior in production which will automagically create tests for us.
All the test logic will be generated fully customizable, so the sky's the limit!

**Url to Slides or GitHub Repo**
https://github.com/TestRigor/actions-recorder

**Social Media Info (Optional)**
https://twitter.com/testrigor

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
The topic is great! I would love to hear about testing in Node.

I don't know for sure if we can fit you into February 13 or March 12th right now but if you are interested in either or a later month please let me know. I would say it is highly likely to be March 12th.

**Comment by Trewaters** [comment]
@artgo 
Checking in with you. Hope you are doing well.

**Comment by Trewaters** [comment]
Hi @artgo seeing if you are available for April 9th? Hope all is going well.
