### ISSUE TITLE
Node, Redis, and You!

### ISSUE THREAD

**Issue by tlhunter** [sfnode/sfnode#13]
Full name and Bio:
Thomas Hunter II
Thomas is passionate about technology and building products. A web design business created while attending college slowly evolved into a brick and mortar on Main St. of his small Midwestern hometown. His desire for fame and fortune led to the co-founding of a Y Combinator startup and a life in California.

Talk title and abstract:
Node, Redis, and You!
Get an overview of the various data structures Redis has to offer, learn how it can be used to share data across multiple Node instances, and how to perform atomic operations using the MULTI and EVAL commands.

Twitter handle:
@tlhunter

Other social profiles or personal blog:
https://thomashunter.name

Url to slides or github:
https://thomashunter.name/presentations/node-redis-v1

Are you going to be live coding?
No

Do you need audio from your computer?
No

**Comment by paulgrock** [comment]
HI @tlhunter would you be interested in presenting during our November event on the 3rd?

**Comment by tlhunter** [comment]
@paulgrock I sure would be!
