### ISSUE TITLE
Talk Proposal: Friends don't let friends Cluster

### ISSUE THREAD

**Issue by tlhunter** [sfnode/sfnode#130]
**Full name and Bio**

**Thomas Hunter II**: Thomas has contributed to dozens of enterprise Node.js services and has worked for a company dedicated to securing Node.js. He has spoken at several conferences on Node.js and JavaScript, is currently writing a book on Node.js services with O'Reilly, and is an organizer of NodeSchool SF.

**Talk title and abstract (description)**

**Friends don't let friends Cluster**: This talk first covers the `cluster` module, how it works conceptually, and how it compares to the `child_process` module. Next, HAProxy is examined, which is a reverse proxy capable of solving the same problems as `cluster`. Finally, the performance of both technologies are measured, both in throughput and memory consumption. Material is based on Thomas's upcoming book, tentatively titled Distributed Node.js.

**Url to Slides or GitHub Repo**

https://thomashunter.name/presentations/node-avoid-cluster

**Social Media Info (Optional)**

https://twitter.com/tlhunter
https://github.com/tlhunter

**Are you going to be live coding?**

Undecided

**Do you need audio from your computer?**

No

**Comment by JoeDoyle23** [comment]
Hi @tlhunter!  Thanks for the talk submission. Are you able to present this Thursday, Feb 13th?

**Comment by tlhunter** [comment]
@JoeDoyle23, certainly!

**Comment by tlhunter** [comment]
@joedoyle23 sorry for the late notice but I'm currently going through some health issues and I don't think I'll be able to speak on Thursday

**Comment by JoeDoyle23** [comment]
No problem! I hope you get well soon!

**Comment by tlhunter** [comment]
I can do it next month if you're looking for speakers

**Comment by Trewaters** [comment]
We would love to have you in March @tlhunter ! 

Get better soon, sending you good vibes.

**Comment by tlhunter** [comment]
Ironically, this talk title is more relevant than ever...

**Comment by dshaw** [comment]
Did we get this in? If not, we’re going virtual for April and yes, this would be perfect. 🤣

**Comment by tlhunter** [comment]
Virtual works for me!

**Comment by isurfbecause** [comment]
@tlhunter Are you still free to talk tomorrow?

**Comment by tlhunter** [comment]
Yes

**Comment by isurfbecause** [comment]
Right on see you online
