### ISSUE TITLE
Talk Proposal: How to Wait

### ISSUE THREAD

**Issue by chromakode** [sfnode/sfnode#131]
**Full name and Bio**
Max Goodhart co-organizes the WaffleJS meetup in San Francisco. He has been writing JavaScript professionally for 10 years.

**Talk title and abstract (description)**
Our story begins with a humble 'await fetch': your script fires off an HTTP request and settles down to nap, trusting that it'll be awoken when response data is available. While your program does nothing, a cascade of activity is now taking place: in your JS runtime, your operating system, and your hardware. What happens while your code is waiting for something to happen? In this talk, we'll peek behind the layers of the event loop, select/epoll nonblocking I/O, and hardware architecture to answer a simple question: what is waiting, and how does a program wait?

**Url to Slides or GitHub Repo**
https://chromako.de/m/how-to-wait

**Social Media Info (Optional)**
https://chromako.de
https://twitter.com/chromakode
https://github.com/chromakode

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by Trewaters** [comment]
Hi Max thanks for submitting this talk. This is awesome! Please let me know your time constraints for scheduling you February 13th?

**Comment by dshaw** [comment]
@Trewaters Max is only available from 7:00-7:30pm and will have to take off after the talk is done.
