### ISSUE TITLE
Talk Proposal: How To Get A Better Job Without Learning Another Framework

### ISSUE THREAD

**Issue by davidguttman** [sfnode/sfnode#133]
**Full name and Bio**
David Guttman

At [Superstruct](https://superstruct.tech), David helps startups build remote engineering teams that ship. He has led teams of engineers to ship projects like ultra-high-scale ad servers handling over 10 billion requests per day, written books like [Fullstack Node.js](https://www.newline.co/fullstack-nodejs), authored over 90 open-source packages on npm, and runs [js.la](https://js.la), one of the largest JavaScript events in the country.

**Talk title and abstract (description)**
How To Get A Better Job Without Learning Another Framework

Too much to learn in today's tech world? Feel like there's no end to what you need to know? Maybe you've completed a web development boot camp and think you have a good grasp on the technology. Of course, the moment you google, you realize there is so much more out there and a ton more to learn. When is enough, enough? Sure, learning is a lot of fun and probably why you got into this field, but if you're looking for a new job, it becomes very intimidating and overwhelming. Well, it turns out that you don't need to know the latest framework to help your career. To get a good gig, the key is to know what hiring managers *really* want. As a bonus, I'll talk about what to do once you have the job so that you can move up the food chain to where you actually want to be. 

**Url to Slides or GitHub Repo**
--

**Social Media Info (Optional)**
Twitter: @davidguttman
Github: @davidguttman
Site: [davidguttman.com](https://davidguttman.com)

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by dshaw** [comment]
Thanks @davidguttman 💖✨
