### ISSUE TITLE
Talk Proposal: Introduction to Nexus

### ISSUE THREAD

**Issue by jasonkuhrt** [sfnode/sfnode#134]
**Full name and Bio**
Who are you and what are you all about? We will post this in the Meetup description.

Jason Kuhrt

I am a TypeScript developer with a passionate for DX. Educated in design theory, practice, and ethics I became fascinated by systems aspects of software engineering. Over years I've oscillated between frontend (jQuery, Angular, React), backend (HTTP, TCP, GQL, Architecture), devops (AWS, GCP, Terraform, CI/CD, Kubernetes) and creative/leadership contributions all in startup environments. Today I work at Prisma on the developer productivity team responsible for enhancing the reach of our awesome developer centric database tools.

**Talk title and abstract (description)**
Introduction to Nexus

Introduction to Nexus Schema, a NodeJS library for building just the schema aspect of GraphQL APIs with code. I'll build a simple API while touring its primary features, including strong type-safety.

**Url to Slides or GitHub Repo**
Slides from a previous version of this talk https://app.pitch.com/app/presentation/f76a4138-0fba-47a4-a85a-4810afa6a3ef/c4e7d63f-7fed-49cb-9468-4a8ecc9b128c

I would evolve this however based on learnings from the previous talk.

**Social Media Info (Optional)**

https://twitter.com/jasonkuhrt
https://github.com/jasonkuhrt
https://www.instagram.com/jasonkuhrt

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by dshaw** [comment]
@jasonkuhrt Thanks for submitting the talk.

**Comment by dshaw** [comment]
@jasonkuhrt Our next meetup is on Thursday, January 14th at 7pm PT (10pm ET). Are you interested and available at that time?

**Comment by jasonkuhrt** [comment]
@dshaw a bit soon, when is the next one?

**Comment by dshaw** [comment]
2nd Tuesday of the month, so for February it's Thursday 2/11 at 7pm PT / 10pm ET. Want to shoot for that, @jasonkuhrt ?

**Comment by jasonkuhrt** [comment]
Sounds good, Thursday February 11 @ 10pm ET!

**Comment by dshaw** [comment]
Awesome. Thank you.
