### ISSUE TITLE
Talk Proposal: TypeScript: JavaScript... with types?

### ISSUE THREAD

**Issue by JeronimoFictiv** [sfnode/sfnode#135]
**Full name and Bio**
Name: Jeronimo Mora

Bio: I'm currently a Sr. Software Engineer at Fictiv where I dabble in everything from fullstack React/GraphQL/Typescript to computational geometry and WebGL. I work as a teaching assistant at Trilogy Education Services (UC Berkeley, UofU) for their web development coding bootcamps.

**Talk title and abstract (description)**
Title: TypeScript: JavaScript... with types?

Aimed at those with a beginner to intermediate understanding of javascript, such as those who may have recently finished a coding bootcamp, this talk should serve as an intro the (semi) statically typed TypeScript language. It will go through basic/intermediate typing, class types, error checking, compilation, and motivations (why bother?). We will build a small node application using TypeScript from scratch that will demonstrate its use. 

**Social Media Info (Optional)**
LinkedIn: https://www.linkedin.com/in/jeronimomora/

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by JoeDoyle23** [comment]
HI Jeronimo! As we chatted about today, you're all set for the May event on May 13th. I'll update the Meetup site shortly.
