### ISSUE TITLE
Talk Proposal: Node.js Package Management

### ISSUE THREAD

**Issue by tlhunter** [sfnode/sfnode#137]
**Full name and Bio**
Thomas Hunter II - Thomas has contributed to dozens of enterprise Node.js services and has worked for a company dedicated to securing Node.js. He has spoken at several conferences on Node.js and JavaScript, is an O'Reilly published author, and is an organizer of NodeSchool SF.

**Talk title and abstract (description)**
This talk covers package management as it is commonly performed in Node.js, from install time to run time. This includes the dependency tree hierarchy and how package managers write packages to disk, how SemVer works and its implications during the install process, and how the module resolution algorithm works when your application calls `require()`.

**Url to Slides or GitHub Repo**
https://thomashunter.name/presentations/node-package-management

**Social Media Info (Optional)**
https://twitter.com/tlhunter

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by JoeDoyle23** [comment]
Hi Thomas! Thanks for submitting a talk. Would you be available to present at our June meetup on June 10th?

**Comment by tlhunter** [comment]
That should work!

**Comment by tlhunter** [comment]
@JoeDoyle23 Sorry for the last minute notice but I've got a funeral on the day of the talk. Can I get a rain check?

**Comment by Zahidul-Islam** [comment]
@tlhunter Would you be interested in presenting this (or updated) talk in the future SFNode meetup?

**Comment by tlhunter** [comment]
@Zahidul-Islam,

I can still give this talk. I'm free on August 25th. I can bring a copy of the book for y'all to raffle off to an audience member.

Note that this talk was given at the 2021 UtahJS conference.

**Comment by Zahidul-Islam** [comment]
✅  @tlhunter Congratulations! Your talk is confirmed for the 25th August 2022 meetup.

**Comment by dshaw** [comment]
@tlhunter Racking up them speaker points!!! Thank you so much for coming through.

**Comment by Zahidul-Islam** [comment]
@tlhunter Just want to let you know that we canceled the SFNode meetup on the 25th of August because of the venue issue. Would you be interested to present the topic in October or November? Sorry for any inconvenience.

**Comment by tlhunter** [comment]
That should work out

**Comment by christian-bromann** [comment]
@tlhunter circling back on this as we ramp up the meet-up again. Is there still interest to talk about this or would you be interested in another topic?

**Comment by christian-bromann** [comment]
> Am I right in assuming the venue is "SF Homebrew Crypto Club"?

For our meetup in June we already have a speaker set up. However we could schedule you in for July. For that month we don't have settled for a venue yet.

**Comment by tlhunter** [comment]
I'd like to withdraw this talk proposal
