### ISSUE TITLE
Data Pipeline Processing 200B events with Node.js And Docker On AWS

### ISSUE THREAD

**Issue by shimont** [sfnode/sfnode#14]
## [Shimon Tolts](https://www.linkedin.com/in/tolts)
I am the General Manager, Data Solutions at [ironSource](https://www.crunchbase.com/organization/ironsource) the Israeli unicorn.
Focusing on load and scale problems around the data field.

## Data Pipeline Processing 200B events with Node.js And Docker On AWS
**I will explain how we transformed our [BigData pipeline](http://www.ironsrc.com/atom/data-flow-management/) into Docker containers using Node.js
Our data pipeline handles more then 200B monthly events and streams them in near-realtime into Redshift. I will present our code and Dockerfiles and show how we did the migration step by step and lessons learned.**

**https://twitter.com/shimontolts**
**http://stackoverflow.com/users/1779712/shimon-tolts**

Are you going to be live coding?
**No but i will show code snippets**

Do you need audio from your computer?
**no**

**Comment by paulgrock** [comment]
@shimont we've already got two speakers for our October event but have open space in November. Are you interested in presenting on November 3rd?

**Comment by shimont** [comment]
Unfortunately I wont be in the US during November, I am coming from Israel to SF during from the 2nd until the 31st. Id love to switch with one of the speakers if possible

**Comment by paulgrock** [comment]
@shimont you'll be in SF during October, right?

**Comment by shimont** [comment]
Yep October

**Comment by paulgrock** [comment]
ok, we'll see what we can do about getting you in to the October event. Thanks

**Comment by paulgrock** [comment]
@shimont how long is your talk?

**Comment by shimont** [comment]
20-30mins

**Comment by shimont** [comment]
Will i be able to present?

**Comment by paulgrock** [comment]
We're still working on it. We'll let you know.

**Comment by paulgrock** [comment]
@shimont yes, you'll be able to present. I'll update the meet up page with your information.

**Comment by shimont** [comment]
Thats great, see you there!

**Comment by paulgrock** [comment]
Thanks for the awesome talk @shimont !
