### ISSUE TITLE
Talk Proposal: Writing Smart Contracts in Javascript on NEAR 

### ISSUE THREAD

**Issue by doriancrutcher** [sfnode/sfnode#141]
**Full name and Bio**
Dorian Kinoo Crutcher. I work in Developer Relations for the [NEAR ](https://near.org/)

**Talk title and abstract (description)**
Writing Smart Contracts in Javascript on NEAR 

Blockchains all have their own take on writing smart contracts, Ethereum uses their own language, Solidity, others including NEAR use languages like Rust or their own custom language. NEAR has taken the initiative to try and make smart contract writing more accessible by allowing users to write smart contracts using Javascript. 

In this workshop I will teach you the basics of writing a smart contract in Javascript and using it to interact with the NEAR blockchain. 

**Url to Slides or GitHub Repo**
(Slides to come, link to javascript repo here: https://github.com/near/near-sdk-js

**Social Media Info (Optional)**

[Dorian's Twitter](https://twitter.com/neardorian) 

[NEAR's Website](near.org)

[NEAR's Discord](near.chat)

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
Yes/No

**Comment by Zahidul-Islam** [comment]
@doriancrutcher Our next event will be on 25th August 2022. Can you please confirm if that date works for you?

**Comment by Zahidul-Islam** [comment]
✅  @doriancrutcher Congratulations! Your talk is confirmed for the 25th August 2022 meetup.
