### ISSUE TITLE
Talk Proposal: Scaling Beyond In-Memory Objects: Past Maps & Heap - Binary Search Dictionaries!

### ISSUE THREAD

**Issue by amark** [sfnode/sfnode#143]
**Hi, I'm Mark**:
Mark Nadal is the author of GUN, an Open Source Firebase alternative. He spends his time obsessed with performance and benchmarking, and will teach you how little tricks can give you huge gains.

**Scaling Beyond In-Memory Objects: Past Maps & Heap - Binary Search Dictionaries!**
NodeJS will crash at about 1.6GB of memory without manually increasing its limits. We'd hope the OS's memory swap would handle this, but not all objects are the same. Further, some features are downright slow: `Object.keys()` is expensive on large objects, and `new Map` has a tradeoff on performance. Is there some middle ground between all these constraints? Yes! Binary Search Dictionaries! We humbly present `Book.js`.

https://github.com/amark/gun/blob/master/lib/book.js

https://twitter.com/marknadal

**Are you going to be live coding?**
Some

**Do you need audio from your computer?**
No

**Comment by Zahidul-Islam** [comment]
@amark Thank you for submitting your talks. Both are interesting and I believe the Nodejs community will learn a lot. We already have two talks for this month (August). Would you be interested to present your talk at September Meetup?

**Comment by amark** [comment]
September would be great! (Are you able to DM me on Twitter? For whatever reason, GitHub never emails me anymore.)

**Comment by amark** [comment]
@Zahidul-Islam how much time do I have for the talk? So I know whether to include more/less, both, etc.

**Comment by Zahidul-Islam** [comment]
@amark Ideally 30/45 minutes. We can allocate more time if you need it. Excited and looking forward to your talk. Please feel free to share the meetup link: https://www.meetup.com/sfnode/events/287874722/
