### ISSUE TITLE
Talk Proposal: Deep dive into Node.js Streams

### ISSUE THREAD

**Issue by ErickWendel** [sfnode/sfnode#146]
**Full name and Bio**
Erick Wendel

Erick Wendel is a professional content creator and Node.js core committer. He has given more than 100 tech talks in over 10 countries around the world. He has been recognized with the most important awards in software development for JavaScript: Microsoft MVP, GoogleDevExpert, and GitHub Stars. He has trained more than 100K people around the world as a professional instructor and content producer at his own company https://erickwendel.com/

**Talk title and abstract (description)**

Deep dive into Node.js Streams

Node.js was built to solve a specific problem to handle on-demand processing. Streams in Node.js are the most powerful and scary feature of the entire platform. Many developers have avoided using Streams because it's run a little bit differently and weirdly than the Promises approach. In this talk, attendees will learn about the native Node.js API stream and tools to help them create and understand the asynchronous flow. 
We will explore the following takeaways
- What are Node.js Streams?
- Understanding Node.js events
- Types of Streams on Node: Writable, Readable, and Transform
- Node.js Async Iterators 
- Real Use cases + fun projects using Node.js Streams

**Social Media Info (Optional)**

https://erickwendel.com/
https://linkedin.com/in/erickwendel/
[https://twitter.com/erickwendel_](https://twitter.com/erickwendel_)
https://www.youtube.com/c/ErickWendelTreinamentos
https://www.nodejsstreams.com/

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
Yes (optional)

**Comment by Zahidul-Islam** [comment]
@ErickWendel Thank you for submitting the talk. Do you know when you want to present the topic? (We have our next meetup on the 13th of this month).

**Comment by ErickWendel** [comment]
> @ErickWendel Thank you for submitting the talk. Do you know when you want to present the topic? (We have our next meetup on the 13th of this month).

Hey, my friend!! I'll be there from 07th to 12th November. So I'd like to speak at the November's edition (Nov 10th)

**Comment by Zahidul-Islam** [comment]
@ErickWendel Unfortunately SFNode Meetup will be on 17th November. I think you mentioned that you will be here from 7th to 12th November. Let me know if your schedule changes and if you can present on the 17th.

**Comment by ErickWendel** [comment]
No problem!
