### ISSUE TITLE
Talk Proposal: Idiosyncracies of NaN

### ISSUE THREAD

**Issue by LewisJEllis** [sfnode/sfnode#147]
**Full name and Bio**
Lewis Ellis

Lewis is an engineer who does Node.js stuff on the platform team at Pave.com. He's previously worked on Node.js backends in the edtech space, and on Sentry's Node.js error reporting SDK.

**Talk title and abstract (description)**
Idiosyncrasies of NaN

What NaN is, where it appears, and what one should know about it, from the perspectives of JavaScript and the IEEE754 spec.

Note: talk takes 15 minutes, can do a 20 minute slot for Q&A I guess?

**Url to Slides or GitHub Repo**
https://github.com/LewisJEllis/nantalk

**Social Media Info (Optional)**
Twitter @LewisJEllis 
GitHub @LewisJEllis

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by Zahidul-Islam** [comment]
@LewisJEllis thank you for the talk submission. I would like to confirm your talk for tomorrow's (Oct 13, 2022) meetup. Looking forward to the talk.
