### ISSUE TITLE
EclairJS = Node.js + Apache Spark

### ISSUE THREAD

**Issue by doronrosenberg** [sfnode/sfnode#15]
**EclairJS = Node.js + Apache Spark**
While Javascript usage continues to grow at a rapid pace, Javascript developers have not been able to directly work with distributed computing engines such as Apache Spark.  The open source EclairJS project changes that by providing the Spark API to Node.js developers, allowing them to use Apache Spark's large-scale analytics, streaming, SQL and machine learning features by writing only Javascript.  We will walk through a basic example's code and show off several fully featured example applications.

**Bio**
Doron Rosenberg (@doronrosenberg) has been working with Javascript his entire career, from browsers to web applications and is Staff Engineer at IBM.

https://github.com/EclairJS/eclairjs-node

Demos can be run locally off my laptop, no live coding or audio needed.  No slides at this point.

**Comment by paulgrock** [comment]
HI @doronrosenberg are you interested in speaking at our December event on the 8th?

**Comment by doronrosenberg** [comment]
@paulgrock I can do the 8th.

**Comment by paulgrock** [comment]
@doronrosenberg would it be possible to move your talk to the January 5th event?

**Comment by doronrosenberg** [comment]
@paulgrock Sure

**Comment by paulgrock** [comment]
Great! Thanks for being so accommodating

**Comment by paulgrock** [comment]
@doronrosenberg are your slides on the Internet somewhere so we can share them with the group?

**Comment by doronrosenberg** [comment]
@paulgrock I gave a pdf to the video guy, but here is a link to it: https://github.com/doronrosenberg/presentations/blob/master/sfnode.pdf

**Comment by paulgrock** [comment]
@doronrosenberg thanks!
