### ISSUE TITLE
Venue Proposal: Sauce Labs

### ISSUE THREAD

**Issue by christian-bromann** [sfnode/sfnode#150]
**What is the address, floor, room name if any, entrance instructions?**
450 Sansome St
9th Floor,
San Francisco,
CA 94111

**Do we need to submit an attendee list for security purposes?**
Yes

**What's the total number of people that space can hold?**
I believe about 50

**Will food and drinks will be provided? Are there vegetarian and gluten free options?**
Yes

**What is the AV setup like?**
Slides can be presented on a big screen through regular I/O like HDMI or USBv3

**What is the microphone setup? Mic stand or headset mic?**
Mic stand available

**What is the parking situation like? Is bike parking available? Any off-street parking?**
It's downtown SF so parking might be difficult. Easiest is to commute via Bart to Embarcadero and walk up 2 blocks.

**Comment by christian-bromann** [comment]
cc @nadvolod

**Comment by Zahidul-Islam** [comment]
@christian-bromann thank you and Sauce Labs.
