### ISSUE TITLE
Venue Proposal: Homebrew 

### ISSUE THREAD

**Issue by alecorbella** [sfnode/sfnode#152]
**What is the address, floor, room name if any, entrance instructions?**
1481 Folsom St, San Francisco, CA 94103. There is one large entrance and code will be provided to those that RSVP. 

**Do we need to submit an attendee list for security purposes?**
Not a big deal, just let us know an approximate. 

**What's the total number of people that space can hold?**
60 people

**Will food and drinks will be provided? Are there vegetarian and gluten free options?**
we can! 

**What is the AV setup like?**
We have a large tv for screening but no fancy audio service

**What is the microphone setup? Mic stand or headset mic?**
No mic 

**What is the parking situation like? Is bike parking available? Any off-street parking?**
Street Parking outside the venue is available

**Comment by christian-bromann** [comment]
@alecorbella thanks for contributing the space! We will get back to you shortly.

**Comment by christian-bromann** [comment]
@alecorbella mind updating the issue title with the company name that is sponsoring? Thanks!

**Comment by Zahidul-Islam** [comment]
@christian-bromann Just updated the company name. It is a web3 co-working space name Homebrew.
