### ISSUE TITLE
Talk Proposal: Ramping Up With Modulo.js on JAMStack

### ISSUE THREAD

**Issue by michaelpb** [sfnode/sfnode#153]
**Full Name:** Michael Bethencourt

**Bio:** Michael is a software-engineer and educator. For over a decade, he’s worked everywhere in the industry—from early-stage start-ups to tech goliaths—wearing every possible hat. As an engineer, he’s led development on a variety of web and mobile products—maybe one you’ve even used! As an educator and public speaker, he’s taught hundreds of courses and workshops to boost the coding skills and creative thinking of Bay Area tech professionals. He believes that complex CS concepts don’t need to be complicated, so over the last few years he’s been forging the way ahead at Kickstart Coding, his own ed-tech start-up, where he leads software development of an LMS product and designs curriculum on JavaScript, Python, and Computer Science topics. When he’s not working, you’ll find him biking, hiking, or playing video games that feel too much like work.

**Talk title and abstract (description)**

`Ramping Up with Modulo.js on JAMStack`

This presentation will introduce the small but mighty framework Modulo.js, designed to be a useful, 2000-line dependency-free alternative to big, popular frameworks like React and Vue, and how it was developed with two perspectives in mind: (1) the educator’s perspective, because modern, component-based frameworks are hard to teach, and (2) the engineer management perspective, because of skill barriers that these frameworks introduce to teams.

The presentation will demonstrate how Modulo introduces core concepts in a way that allows coders to begin making complex and useful JAMStack applications immediately after only learning the basics of HTML and CSS. This makes Modulo a "low code" gateway to allow educators to explain core concepts to a much bigger audience. Despite being only 2000 lines, those lines were chosen carefully, and have minimalist implementations of most features you’d expect from modern frontend frameworks such as React or Vue: State, Stores, Props, Templating, data binding, directives, DOM resolution, CSS prefixing, SSR and hydration, packing, and more. It will demonstrate with live coding a few common uses of Modulo for new apps how declarative, compositional middleware systems help bridge the coder/artist gap in product teams. This "Component Parts" middleware provides a very easy and open-ended way to extend the framework, making Modulo a great foundation for spin-offs or domain-specific frameworks.

Finally, the presentation will shift to greenfielding with Node.js, and how Modulo is already being used in the wild for JAMStack apps. It will show how using the `modulocli` tool and running `npm init modulo` will setup a JAMStack project with Markdown and DecapCMS, ready to launch on a server like Netlify, for continuous delivery of a web product built with Modulo.

**Url to Slides or GitHub Repo**: https://modulojs.org/slides/intro22.html 

**Social Media Info (Optional):** Personal site: https://michaelb.org

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by christian-bromann** [comment]
Hey @michaelpb 👋 thanks for proposing this talk. It sounds really interesting and we would love to have you for the SFNode meet-up in August (31st). Will you be around that day?

fyi: there will be [a meetup](https://www.meetup.com/sfnode/events/294813093/) this Thursday (July 27th), if you have time feel free to step by 😉

**Comment by Liam-Patten** [comment]
Hey Christian! I work with Michael and encouraged him to submit his project for consideration. I can confirm that he will be available on Thursday, August 31st to give the full presentation. I know he's excited finally unveil this long term project. I'll nudge him to get back to you directly though. Thanks

**Comment by michaelpb** [comment]
> Hey @michaelpb wave thanks for proposing this talk. It sounds really interesting and we would love to have you for the SFNode meet-up in August (31st). Will you be around that day?

Awesome, yes I can do August 31st, that works great. I'll see if I can swing by this Thursday as well, but I do have an obligation before which might make it tight. But I can definitely do August 31st, and am looking forward to it, thanks so much!

**Comment by christian-bromann** [comment]
Awesome, looking forward to the talk. How long will it be?

**Comment by christian-bromann** [comment]
@michaelpb thanks Michael for this fantastic talk! I forgot to ask you to send me your voice recording. Can you send it to me?

**Comment by christian-bromann** [comment]
ping @michaelpb , would love to get the recording if possible 😊

**Comment by christian-bromann** [comment]
Received the audio file, thanks! The video will be published next Monday. @Zahidul-Islam we can close the issue.
