### ISSUE TITLE
Talk Proposal: Using Node.js to automate your macbook

### ISSUE THREAD

**Issue by lorenzejay** [sfnode/sfnode#154]
**Full name and Bio**
My name is Lorenze, and I am a software developer consulting at various startups in the Bay. Last year I wrote a blog that got featured on [hashnode about mac automation with applescript](https://lorenzejay.hashnode.dev/how-i-automated-my-macbook-to-help-me-get-ready-for-work). I thought this could be a great talk, using node.js / JXA. 

**Talk title and abstract (description)**
When we hear Node.js we think backend language that communicates with a server or database or to make apis and endpoints. But what about using it to script or set up automation for your Macbook? 

**Url to Slides or GitHub Repo**
Either now or can be posted in Meetup comments later. Our attendees love to reference the slides after the talks.
Working on it

**Social Media Info (Optional)**
How can folks communicate with you? Twitter handle, GitHub, Other social profiles, Personal blog, etc
[Github](https://github.com/lorenzejay)
[Twitter](https://twitter.com/lorenzejayTech
)
**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by christian-bromann** [comment]
Hey @lorenzejay 👋  good to see you here!

We already have a talk scheduled for August but depending on the length we might can do two. How long is your talk gonna be?

Fyi: SFNode is happening [this week](https://www.meetup.com/sfnode/events/294813093/), if you have time, RSVP and come by 😉

**Comment by lorenzejay** [comment]
It should be less than 10 mins. I'd estimate 5-7 mins. BTW, are you the organizer now for SFnode? That's pretty cool.

**Comment by christian-bromann** [comment]
> It should be less than 10 mins. I'd estimate 5-7 mins.

I think then it makes sense to schedule it in for August, what do you think @Zahidul-Islam @copperwall ?

> are you the organizer now for SFnode?

I am helping bringing back awesome tech events in SF, that's it 😉

**Comment by chrisopperwall-qz** [comment]
That sounds great to me!

**Comment by copperwall** [comment]
That sounds good to me!

**Comment by lorenzejay** [comment]
Awesome! I'm excited for it! I'll see ya'll then. 

Thanks again, I hope to see you guys there @christian-bromann.

**Comment by christian-bromann** [comment]
@lorenzejay just want to confirm with you: we have scheduled you as lightning talk for August 31st. Does it work for you?

**Comment by lorenzejay** [comment]
Hey Christian, yes the date works for me!


> @lorenzejay just want to confirm with you: we have scheduled you as lightning talk for August 31st. Does it work for you?

**Comment by lorenzejay** [comment]
@christian-bromann
here is my talk slides - 

https://docs.google.com/presentation/d/1S1mvEefpKtdGl8IHxptehKMP5dQ8LYjsVtEdR14xytc/edit?usp=sharing

**Comment by christian-bromann** [comment]
Hey @lorenzejay , great talk - thanks for coming out! Can you send me the recording of your screen (e.g. as Google Drive link). Thanks a lot!

**Comment by lorenzejay** [comment]
> Hey @lorenzejay , great talk - thanks for coming out! Can you send me the recording of your screen (e.g. as Google Drive link). Thanks a lot!

Thank you Christian! Here is my screen record - https://drive.google.com/file/d/1FrLR0tNnrZxfCmKZPGwl1flna_ug5OEw/view?usp=drive_link


Btw, can I get the raw clip too. 

Thanks again

**Comment by christian-bromann** [comment]
Thanks, I will share the material once I got the video edited.

**Comment by lorenzejay** [comment]
Thank you Christian! Btw, can I get the raw clip too?

**Comment by christian-bromann** [comment]
> Btw, can I get the raw clip too?

Yes

**Comment by christian-bromann** [comment]
@lorenzejay shared my recoding with you, let me know if that works. YouTube video is processing and will be published in the upcoming days.

@Zahidul-Islam we can close the issue.
