### ISSUE TITLE
Talk Proposal: Machine Learning for customer support, interview preps, document assistance

### ISSUE THREAD

**Issue by will-s-205** [sfnode/sfnode#155]
**Full name and Bio**
Hi, I'm William Step. I'm a Software Quality Assurance Engineer. Currently in a career transition to Software Development. Interested in ML, OpenAI, Front End or Fullstack, JavaScript/TypeScript, Java, Python, SQL, NoSQL, AWS.

**Talk title and abstract (description)**
Have you ever waited during the phone call for a good 10 minutes just to ask one single question? How often do you go for online support just to find that there is no answer or question listed for your particular case? Well worry not! Because this is where Machine Learning comes handy! As of now I'm working on a couple of chatbots that are based on OpenAI and helping users with documents and technical interviews. Chatbots are really simple and understandable and support text-to-speech to make UX even more interesting.

**Url to Slides or GitHub Repo**
[Mini Recruiter and Document Assistant](https://github.com/will-s-205/mini-recruiter)

**Social Media Info (Optional)**
[Twitter](https://twitter.com/WilliamStep4)
[LinkedIn](https://www.linkedin.com/in/williamstep/)

**Are you going to be live coding?**
Yes (if applicable)

**Do you need audio from your computer?**
Yes (if applicable)

**Comment by christian-bromann** [comment]
Thanks William! We would love to have you in our September edition on September 28th. How long will your talk gonna be?

**Comment by will-s-205** [comment]
@christian-bromann Thanks, September 28  works for me. I believe it will take 5-10min, depends on questions we could go over similar projects I've created.
