### ISSUE TITLE
Talk Proposal: Introducing Tinylibs

### ISSUE THREAD

**Issue by Aslemammad** [sfnode/sfnode#156]
**Full name and Bio**
I'm Mohammad Bagher, the Founder of Pheno Agency and Tinylibs. Also a core maintainer for Jotai and Vitest. 

**Talk title and abstract (description)**
I wanted to introduce Tinylibs as a community and its projects like Tinypool, Tinybench and Tinyspy. As I talked with Christian, it's going to be video recorded online if possible.

**Url to Slides or GitHub Repo**
Either now or can be posted in Meetup comments later. Our attendees love to reference the slides after the talks.

**Social Media Info (Optional)**
twitter: aslemammadam
github: aslemammad
agency website: https://pheno.agency

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
Yes

**Comment by christian-bromann** [comment]
@Aslemammad awesome, thank you! Would you mind giving me a 2-3 sentence description of the talk? Also how long are you planning to speak?

**Comment by Aslemammad** [comment]
How's this:

Tinylibs is all about small and minimal libraries. In this presentation, Mohammad will introduce the organization and tell us about its most popular libraries like tinypool, Tinybench, and Tinyspy.

**Comment by dshaw** [comment]
@Aslemammad There appear to be multiple tinylibs projects. Can you please link to the projects you’re referring to?

**Comment by Aslemammad** [comment]
https://github.com/tinylibs/tinypool
https://github.com/tinylibs/tinybench
https://github.com/tinylibs/tinyspy

Here you go.
