### ISSUE TITLE
Talk Proposal: Exploring Marko

### ISSUE THREAD

**Issue by LuLaValva** [sfnode/sfnode#158]
**Full name and Bio**
Hi, I'm Luke LaValva! I've been on the Marko core team at eBay for a little over a year now. I'm passionate about developer experience, progressive enhancement, and web accessibility.

**Talk title and abstract (description)**
Exploring Marko
Marko is an open source, declarative JavaScript framework made for eBay with a focus on server-side rendering. For nearly a decade, it has been at the forefront of many of the technologies that are now becoming popular in other frameworks, such as streaming and JavaScript islands. In this presentation, we will explore some of the technologies that make Marko unique and how its lessons can be applied to the broader web.

**Url to Slides or GitHub Repo**
I'll add slides after the talk is accepted, but for now our GitHub is [marko-js](https://github.com/marko-js)

**Social Media Info (Optional)**
Twitter: [@MarkoDevTeam](https://twitter.com/MarkoDevTeam)
Join [our Discord](https://discord.gg/marko)!

**Are you going to be live coding?**
Probably Not

**Do you need audio from your computer?**
Probably Not

**Comment by Zahidul-Islam** [comment]
@LuLaValva thank you for submitting. How much time do you need for the talk?

**Comment by LuLaValva** [comment]
Apologies for the ambiguity, but I'm pretty flexible for amount of time. I'd like at least 10 minutes to tell a compelling narrative, but in an ideal world the talk would probably be about half an hour.

**Comment by christian-bromann** [comment]
@LuLaValva 30min sounds good to me

**Comment by christian-bromann** [comment]
@LuLaValva just a heads up the event will be next Thursday, we will share the meetup.com event once it is posted.

**Comment by LuLaValva** [comment]
Awesome, I'll be there. Thanks @christian-bromann!
