### ISSUE TITLE
Talk Proposal: Intro to OpenTelemetry

### ISSUE THREAD

**Issue by MikeShi42** [sfnode/sfnode#159]
**Full name and Bio**

Hi I'm Michael! I'm co-founder of HyperDX, an open source observability product based on OpenTelemetry that helps engineers fix production issues. Prior to founding HyperDX, I was leading developer experience over at Mezmo helping engineers make sense of all their production logs.

**Talk title and abstract (description)**

Intro to OpenTelemetry

When something goes wrong in production - it can be really tricky to figure out what actually went wrong. Was it user error? Bad input? Infra issues?

OpenTelemetry is a fast-growing CNCF project that makes it easier than ever to instrument your code to tell you what is going wrong in production, providing a set of SDKs to easily collect logs, metrics, traces and more to pin point what went wrong in production.

In this talk we'll quickly go over why debugging production is challenging, how OpenTelemetry can help, and how easy it is to get set up for any JS project.

**Url to Slides or GitHub Repo**

OpenTelemetry (for JS): https://github.com/open-telemetry/opentelemetry-js
HyperDX (which consumes, stores, and visualizes the OpenTelemetry data): https://github.com/hyperdxio/hyperdx

**Social Media Info (Optional)**
Twitter: https://twitter.com/MikeShi42
HyperDX Discord: https://discord.gg/4Byfw9vQwV

**Are you going to be live coding?**
Probably a live demo but not that much code

**Do you need audio from your computer?**
No

**Comment by christian-bromann** [comment]
Hey @MikeShi42 , thanks for proposing this talk. Would you be able to speak on October 26th.

**Comment by MikeShi42** [comment]
Thank you, that'd be awesome!

**Comment by MikeShi42** [comment]
@christian-bromann just wanted to double check that I'll be able to speak next week? :)

**Comment by christian-bromann** [comment]
Yes, we are about to set up the event.
