### ISSUE TITLE
Creating Electronic Dance Music with JavaScript & Node.js

### ISSUE THREAD

**Issue by walmik** [sfnode/sfnode#16]
When you go to a club or a party or a rave.. What is one of the most obvious things you notice about the music? 

> It's repetitive! 

Since we are engineers, what comes first to mind when we see something repeating itself over and over again? 

> Automate the damn thing \m/

I ve created a Node.js module called [Scribbletune](http://scribbletune.com/) which has a very minimalistic API (only 3 methods). I'd like to showcase this module along with the options available to us today when it comes to creating music with Node.js right from the terminal. Using my module and regular JavaScript String and Array functions I will put together the basic structure of an Electronic Dance Music track and show how easy it is for you to start dabbling with EDM using Node.js.
### Speaker

**Walmik Deshpande** [@_walmik](https://twitter.com/_walmik)
_Sprint Monkey at PayPal_
#### Requirements
- Since this talk is primarily around EDM with Node.js, Audio Out is required (If the venue is not too big, I can get my own sound)
- I will be live coding - I will compose parts of a EDM track with JavaScript and Node.js

**Comment by IAmEddieDean** [comment]
🤘  This is going to be a rad talk.

**Comment by paulgrock** [comment]
@walmik are you interested in presenting at the January 5th event?

**Comment by walmik** [comment]
@paulgrock Sure, would love to!

**Comment by walmik** [comment]
@paulgrock Hi Paul, is my talk on for the Jan 5 event?

**Comment by paulgrock** [comment]
@walmik yes sir
