### ISSUE TITLE
Talk Proposal: Unit Testing Javascript with Reflection and GPT-4

### ISSUE THREAD

**Issue by arvindrajnaidu** [sfnode/sfnode#160]
**Arvind Naidu**
I am an ardent javascript fan working on 10 side hustles at any given time. I work for Drivewealth as an Engineering Leader exploring the role of LLMs in QA.

**Unit Testing Javascript with reflection and GPT-4**
In this talk I would like to introduce a new way to write unit tests for Javascript functions. Will be doing some live coding, walking everyone through writing tests for a varied set of functions.

**Maineffectjs**
[Maineffectjs](https://github.com/arvindrajnaidu/maineffect)

**Twitter**
@buzzarvind

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by christian-bromann** [comment]
@arvindrajnaidu are you able to give this talk at the meetup this month on the November 30th? How long is the talk?

**Comment by arvindrajnaidu** [comment]
Yes, I can. I'd say about 30 mins.

**Comment by christian-bromann** [comment]
@arvindrajnaidu can you confirm that you can give the talk next week?

**Comment by arvindrajnaidu** [comment]
Yes. I confirm.

**Comment by christian-bromann** [comment]
Hey @arvindrajnaidu 👋 thanks again for speaking at the last meetup! Very fascinating project.

Please share your screen recording via GDrive or whatever you prefer when you get a chance so I can go ahead and edit it. Thanks!

**Comment by arvindrajnaidu** [comment]
Hi Christian,

Again thanks for having me over. I'm afraid something went wrong as soon as
the talk started .. I don't see a saved video.
Sorry about that. The project itself is here

GIT: https://github.com/arvindrajnaidu/maineffect
NPM: https://www.npmjs.com/package/maineffectjs

I will brush up the documentation.

-Arvind
