### ISSUE TITLE
Venue Proposal: CodeParrot

### ISSUE THREAD

**Issue by vedant1811** [sfnode/sfnode#162]
**What is the address, floor, room name if any, entrance instructions?**
355 Bryant St, San Francisco, CA 94107

**Do we need to submit an attendee list for security purposes?**
No

**What's the total number of people that space can hold?**
office floor: 
30 comfortable
40 is merry
50 would be a bit of a crush but possible

roof = can easily fit 70
but basically can split people across both, only thing is that the roof is very cold in evenings.

**Will food and drinks will be provided? Are there vegetarian and gluten free options?**
Yes

**What is the AV setup like?**
TV of size 70 inches (diagonal)

**What is the microphone setup? Mic stand or headset mic?**
You prob won't need a mic, it is a small venue. But we have a DJ speaker you can use, we'll can rent or buy a neck or handheld mic. 

**What is the parking situation like? Is bike parking available? Any off-street parking?**
lots of street parking in front of our building. Quite safe.

**Comment by christian-bromann** [comment]
Thanks @vedant1811 for hosting us this month. We have created the event: https://www.meetup.com/sfnode/events/298631386/. We are still open to one more speaker so if you know anyone please ping me.

**Comment by christian-bromann** [comment]
> Both companies are co-hosting :)

Update the description.
