### ISSUE TITLE
Venue Proposal: Sentry

### ISSUE THREAD

**Issue by dorothymlee** [sfnode/sfnode#163]
**What is the address, floor, room name if any, entrance instructions?**
We'll post this information on the Meetup page so that everyone knows where to go.
45 Fremont Street, 8th floor, San Francisco, CA 94105
Guests will need to check in with security at the downstairs lobby (ID is required) and then they will let them up to the 8th floor where our office is.

**Do we need to submit an attendee list for security purposes?**
Not a big deal. Just helps us plan and coordinate with you to get the list to you in time.
**Yes**

**What's the total number of people that space can hold?**
We average 75 people per month.
Anywhere from 50-80 is perfect for our space!

**Will food and drinks will be provided? Are there vegetarian and gluten free options?**
Doesn't need to be super fancy.
Yes.

**What is the AV setup like?**
Tell us about the setup so we can make sure it matches with the requirements of our speakers for that month.
We ideally would use a Google Meet to record + share slides for the talks for the meetup. It's really easy to set up, speakers can just join the meeting and share through that and it will project to the room. If we need to allow for any virtual attendees they can also join through this. We also have a microphone for the speaker.

**What is the microphone setup? Mic stand or headset mic?**
Tell us about the setup so we can make sure it matches with the requirements of our speakers for that month.
Mic stand.

**What is the parking situation like? Is bike parking available? Any off-street parking?**
We do get asked about bike parking every month, so it helps us to know if its available.
Parking is available but is not recommended. We are located in downtown SF so we strongly recommend rideshare, bus or BART (we are like a 5 minute walk from Embarcadero station).

**Comment by christian-bromann** [comment]
Hey @dorothymlee , thanks for submitting this venue proposal. We usually do SFNode every last Thursday of the month. Would this venue be available on February 29th?

**Comment by dorothymlee** [comment]
Let me check with our team and get back to you! Would we also be able to supply a speaker at all (if we have someone available) or are the talks already filled?

**Comment by dorothymlee** [comment]
Also, what time do your meetups typically start? We typically host our in office happy hours on Thursdays so we'd need some time to flip the room depending on timing.

**Comment by christian-bromann** [comment]
> Would we also be able to supply a speaker at all (if we have someone available) or are the talks already filled?

We usually find speaker from the community but if Sentry has someone who is interested to speak, we would love to have them.

> Also, what time do your meetups typically start?

We usually get together on 6:30pm until 8 or 9pm.

**Comment by dorothymlee** [comment]
Hi Christian - great! We can host a meetup on the 29th :) I will start to enquire internally if we have a speaker interested, when do you need to know by?

We have our happy hours on thursdays but they typically wrap up around 6pm. We may have a few internal employees stay around though if that's okay, but a start time of 6:30pm would be perfect.

**Comment by christian-bromann** [comment]
> when do you need to know by?

Anytime before, the sooner the better 😉

**Comment by dorothymlee** [comment]
Awesome - let me reach out to some folks and get back to you! I assume y'all will create a Meetup page and advertise it and what not to your community? We'd be happy to promote it as well on our socials/email too if you're ok with that.

We will also plan for around 75 attendees for food/bev but let me know if that changes at all.

**Comment by christian-bromann** [comment]
> I assume y'all will create a Meetup page and advertise it and what not to your community?

Correct, any co-promotion is welcome!

> We will also plan for around 75 attendees for food/bev but let me know if that changes at all.

From experience we expect usually around ~30 people depending on the speaker line up.

**Comment by dorothymlee** [comment]
Oh okay, awesome! I'll plan for closer to 30ish people instead then. Please let me know when the page is up! I'll keep you posted on a speaker too. Is there a recommend duration for the talk if we are able to secure an engineer to present?

**Comment by christian-bromann** [comment]
> Is there a recommend duration for the talk if we are able to secure an engineer to present?

Anything from between 5min to 40min is fine.

**Comment by dorothymlee** [comment]
Great, thanks! I'll be in touch soon.

**Comment by dorothymlee** [comment]
Hi team - quick update, unfortunately I couldn't find an available speaker for the meetup on the 29th :( We will still be hosting your meetup obviously though and sponsor food + drinks so no changes there. Please let me know when you have an event page up - thanks!

**Comment by christian-bromann** [comment]
Thanks for the heads up @dorothymlee , as soon as we get a speaker we will put up the event and let you know here.

**Comment by dorothymlee** [comment]
Hi Christian - is there a link to the event page? I don't see anything up on Meetup but apologies if I'm missing something.

**Comment by christian-bromann** [comment]
@dorothymlee thanks for checking in with me, I just published the event: https://www.meetup.com/sfnode/events/299183905/ . Let me know if you would like to make any changes to it.

**Comment by dorothymlee** [comment]
Thanks @christian-bromann ! This looks good to me. We're still planning for roughly 30-40 people but let me know if that changes

**Comment by christian-bromann** [comment]
> We're still planning for roughly 30-40 people but let me know if that changes

Let's observe the amount of rsvp's. Even if we reach 80 rsvp's in our experience only 50% show up.

**Comment by dorothymlee** [comment]
Hey @christian-bromann ! just checking to see how things are coming along? We have food secured for about 30-40 people (we'll have some Sentry folks as well). Also, not sure if you're planning on sending a last minute email to RSVPed folks but there are a couple reminders to share:
- there isn't much parking near our office, so I recommend using public transit/Lyft/Uber
- folks will need to bring their ID. Security will check them in downstairs and then let them up to the 8th floor where our office is.

**Comment by christian-bromann** [comment]
Hey @dorothymlee 👋  looking forward to tomorrow!

> * do you need to check people in at all?

We don't.

> * is there any chance you can share with me a registration list?

I can pull the list from meetup.com .. where can I send it to?

> there are a couple reminders to share

I will make sure to post this in the meetup group.

> * If we have their emails, they'll get sent a QR code that they can use to check in. If not, no worries

The list we get from meetup.com unfortunately doesn't contain any emails.

**Comment by dorothymlee** [comment]
Ok great - we don't need to check people in, but the building will so they'll just need to have their ID for that.

Do you know about what time you plan to arrive?

**Comment by christian-bromann** [comment]
> Do you know about what time you plan to arrive?

I will be at the office at 6pm to help set up everything in advance. Happy to arrive earlier if needed.

**Comment by dorothymlee** [comment]
6pm should be fine! Also just an FYI, we'll have the speakers join our Google Meet - that way we can record the talks and it's the easiest way for them to present their slides to our projector/screen during their sessions. Do you have their email addresses by chance? I can add them to the calendar invite.

**Comment by dorothymlee** [comment]
Yep I'll share that out when I have it post-event!

**Comment by christian-bromann** [comment]
> Are you able to share the RSVP list with whatever info you have?

Totally, where should I send the list to?

**Comment by dorothymlee** [comment]
Can you send it to dorothy.lee@sentry.io?

**Comment by a-chocolate-bear** [comment]
@dorothymlee you can reach out to praveen@hasura.io

**Comment by dorothymlee** [comment]
@a-chocolate-bear great - just added you! Thanks all

**Comment by dorothymlee** [comment]
Hey @christian-bromann - great meetup yesterday! I just shared the recording with you but not sure if you got it so sharing the link here in case: https://drive.google.com/open?id=1J09GoMBm3tTifY57JbH7Rkw92LnySoNz

**Comment by christian-bromann** [comment]
Thank you @dorothymlee 🙏 Sentry has been a fantastic host!

**Comment by djgrant** [comment]
Second that! I had a blast
