### ISSUE TITLE
Talk Proposal: Make AI generate components for you

### ISSUE THREAD

**Issue by vedant1811** [sfnode/sfnode#164]
**Full name and Bio**
Who are you and what are you all about? We will post this in the Meetup description.

Vedant Agarwala.
For the past 8 years I have been doing all things engineering- backend, frontend, engineering management. I was in various different early stage startups. A year back, I started a company, https://codeparrot.ai , with my friend and got funded by YCombinator. A month ago we launched our product to help front-end designers convert figma designs to code much faster.

**Talk title and abstract (description)**
Make AI generate components for you.

LLM's like GPT-4 are powerful to get a lot of mundane tasks done for you, like 
- fetching figma props and apply it to css
- create components from prompts like "make a navbar"
- even, centering a div!

We will explore how to do it together in a live coding environment.

**Url to Slides or GitHub Repo**
*Will post later*

**Social Media Info (Optional)**
How can folks communicate with you? Twitter handle, GitHub, Other social profiles, Personal blog, etc

- https://www.linkedin.com/in/vedantsopinions/
- https://twitter.com/vedantsopinions

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by christian-bromann** [comment]
@vedant1811 can we slot you in for this Thursday?

**Comment by vedant1811** [comment]
@christian-bromann yes please!

**Comment by christian-bromann** [comment]
Awesome, I've updated the event: https://www.meetup.com/sfnode/events/298631386/ .. looking forward to it!
