### ISSUE TITLE
Venue Proposal: Hasura

### ISSUE THREAD

**Issue by praveenweb** [sfnode/sfnode#167]
**What is the address, floor, room name if any, entrance instructions?**
We'll post this information on the Meetup page so that everyone knows where to go.
576 Folsom St, Fl 3, San Francisco, CA - 94158
Guests will need to check in at the ground floor before heading to the third floor.

**Do we need to submit an attendee list for security purposes?**
Not a big deal. Just helps us plan and coordinate with you to get the list to you in time.
Yes

**What's the total number of people that space can hold?**
We average 75 people per month.
An average of 30 people works the best for our space for now.

**Will food and drinks will be provided? Are there vegetarian and gluten free options?**
Doesn't need to be super fancy.
There could be some beverages, but food is optional.

**What is the AV setup like?**
Tell us about the setup so we can make sure it matches with the requirements of our speakers for that month.
We have a setup where speakers can join a Zoom session that mirrors to a screen. We also have a microphone if required, but the space is typically a good fit for even without a mic.

**What is the microphone setup? Mic stand or headset mic?**
Tell us about the setup so we can make sure it matches with the requirements of our speakers for that month.
Mic stand.

**What is the parking situation like? Is bike parking available? Any off-street parking?**
We do get asked about bike parking every month, so it helps us to know if its available.
We are located in downtown SF, and hence recommend public transport, Muni or BART (a 10 mins walk).

**Comment by christian-bromann** [comment]
Thanks @praveenweb for submitting the issue and HasuraHQ for hosting SFNode. We have confirmed you for April 25th.

**Comment by maxdml** [comment]
👋 Will the next meetup be April 25th then? (Just confirming because I was checking on https://www.meetup.com/sfnode/. Don't want to miss it ! 😁)

**Comment by christian-bromann** [comment]
> Will the next meetup be April 25th then?

Yes, it will!
