### ISSUE TITLE
Talk Proposal: Building Real-Time Surveys with SolidJS and PartyKit: A Practical Approach

### ISSUE THREAD

**Issue by Pillin** [sfnode/sfnode#172]
**Full name and Bio**

I'm Pillippa Perez Pons, a Frontend Software Engineer at Doordash, I am passionate about developing innovative web applications that enhance user experiences and improve efficiency. Originally from Chile, I have been living in the Bay Area for the past three years, embracing the vibrant tech community here.

Volunteering and community involvement are core to who I am. In 2019 and 2020, I mentored young girls through Niñas Pro, helping them develop their technical skills and inspiring their interest in technology. I also contributed to Django Girls in 2020, creating a welcoming environment for women to learn coding. In 2023, I had the opportunity to be an organizer for JSConf Chile, fostering a collaborative and inclusive tech community. Additionally, I played a significant role in JavaScript Chile 2023, promoting education and growth within the local JavaScript community. My commitment is to empower underrepresented groups and encourage them to pursue careers in technology, believing in their potential to make a significant impact.

**Talk title and abstract (description)**

Building Real-Time Surveys with SolidJS and PartyKit: A Practical Approach
This talk will explore how to build real-time, interactive surveys using SolidJS and PartyKit. We will delve into the integration of these technologies to create responsive and dynamic survey experiences. Attendees will learn the fundamentals of SolidJS for building fast and efficient web applications and how PartyKit can be leveraged for real-time data synchronization. By the end of the session, you'll have a practical understanding of how to implement real-time features in your web projects and enhance user engagement with live feedback mechanisms.

**Url to Slides or GitHub Repo**
Backend: https://github.com/Pillin/survey-sync-backend
Frontend: https://github.com/Pillin/survey-sync-frontend

**Social Media Info (Optional)**
Twitter: https://twitter.com/_pilliin_
Linkedin: https://www.linkedin.com/in/ignaciapons/

**Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Comment by christian-bromann** [comment]
@Pillin awesome talk proposal 🎉  are you available on Thursday, June 27th?

**Comment by christian-bromann** [comment]
Hey @Pillin cam you confirm to speak next Thursday?

**Comment by Pillin** [comment]
Hey, @christian-bromann sorry for the late answer, I missed in the all notifications 😭

**Comment by christian-bromann** [comment]
@Pillin no worries, unfortunately for this month we already had commitments on the event so we can schedule you for next month Thursday, 29th of August. Are you available that day?

**Comment by Pillin** [comment]
@christian-bromann yes, I'm available!, thank you so much!

**Comment by christian-bromann** [comment]
> yes, I'm available!, thank you so much!

Awesome, let's schedule you for that day then.

**Comment by christian-bromann** [comment]
@Pillin just letting you know that we scheduled the event https://www.meetup.com/sfnode/events/302897324/?eventOrigin=group_upcoming_events, looking forward to your talk 🙏

**Comment by Pillin** [comment]
Thank you, @christian-bromann for letting me know!. See you there!
