### ISSUE TITLE
Talk Proposal: Production Driven Development

### ISSUE THREAD

**Issue by modern-sapien** [sfnode/sfnode#173]
**Full name and Bio**
Who are you and what are you all about? We will post this in the Meetup description.

Jonathan Canales
I'm all about where testing and monitoring collide. I worked at Cypress for two years supporting their largest customers that were migrating from Selenium or refining their approaches for testing at scale. Near the end of my time there, I conducted an extensive user research project for what would be the most valuable next feature set for us to support everything pointed to running your tests in production aka synthetic monitoring. 

**Talk title and abstract (description)**
Production Driven Development

Testing is still the most arduous, painful, and expensive task within a DevOps practice, regardless of framework or approach. Why? Because the current approaches to testing and development are not focused on production. 

Let's dive into how with practical approaches and modern tooling we can get beyond the limitations of traditional test practices.

**Url to Slides or GitHub Repo**
Either now or can be posted in Meetup comments later. Our attendees love to reference the slides after the talks.

**Social Media Info (Optional)**
How can folks communicate with you? Twitter handle, GitHub, Other social profiles, Personal blog, etc
[linkedin.com/](https://www.linkedin.com/in/modern-sapien/)

**Are you going to be live coding?**
Maybe

**Do you need audio from your computer?**
No

**Comment by christian-bromann** [comment]
Hey @modern-sapien 👋 thanks for proposing the talk, can you give this presentation this Thursday?

**Comment by modern-sapien** [comment]
@christian-bromann I'm aiming for next month. Hannes from Checkly pointed me to the proposal!

**Comment by christian-bromann** [comment]
Gotcha, ok will check you in for July then!

**Comment by modern-sapien** [comment]
Awesome thank you! I'm excited!
