### ISSUE TITLE
Talk Proposal: Discovering Marko's Tags API

### ISSUE THREAD

**Issue by LuLaValva** [sfnode/sfnode#175]
**Full name and Bio**
Luke LaValva has been working on Marko at eBay for 2 years, and is passionate about leveraging the web platform as much as possible while making websites.

**Talk title and abstract (description)**
A syntax talk! Marko's Tags API is around the corner (and has been for a while 😅), so there's no better time than the present to talk about what it is all about. Join us here for a first look at what we on the Marko team think a _true_ HTML-first language might look like.

**Url to Slides or GitHub Repo**
Will post in meetup comments

**Social Media Info (Optional)**
@MarkoDevTeam, @LukeLaValva, markojs.com

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by christian-bromann** [comment]
Looking forward to hear the talk this month 🎉 thanks Luke and the whole Marko team for giving the talk 🙏
