### ISSUE TITLE
debugging < profiling < tracing < monitoring

### ISSUE THREAD

**Issue by danielkhan** [sfnode/sfnode#18]
For each stage of your applications lifecycle there are viable ways to get insights into Node.js. Let’s explore- and also understand the theory behind them. What happens if we attach a debugger or what does the V8 profiling facility give us and what does it cost? How can we monitor Node in production, which metrics are important and why is it so hard to trace through Node.js’ execution? Let’s also cover which new ways to get telemetry we can expect in upcoming versions of Node, shall we?

This session will cover all of that and in the end you will have the knowledge and tools to properly introspect your Node.js applications no matter what.

**Comment by paulgrock** [comment]
@danielkhan do you have a bio that we can add to the meetup page?
