### ISSUE TITLE
Real-time applications with GraphQL, Node.js and MQTT

### ISSUE THREAD

**Issue by JacopoDaeli** [sfnode/sfnode#19]
**About the talk**
[GraphQL](http://graphql.org/) is known as supporting queries and mutations, and now it supports subscriptions as well. With subscriptions clients can get updates pushed from the server when data they care about changes. In this talk, the speaker will describe how you can build a Real-time application using the GraphQL, Node.js and MQTT through a demo.

**About the speaker**
Jacopo Daeli ([@JacopoDaeli](https://twitter.com/JacopoDaeli)) is a Computer Scientist, Software Engineer and Hacker, passionate about web technologies. He develop with Node.js, Go, C/C++, React and Redux for the web.
After a couple of years in London, where he worked as Chief Software Engineer for Impero, Jacopo is now leading the Backend Engineering team at Pikichat, a French company which operates [Tribe](http://tribe) – the famous Video Messenger application – in Paris and San Francisco through the US subsidiary.

Website: http://jacopodaeli.com
Github: https://github.com/JacopoDaeli
Medium: https://medium.com/@jacopodaeli

**Comment by vning93** [comment]
Hey! I just stumbled upon your post while submitting my own talk proposal. Perhaps we can collaborate on an event together.

My talk proposal: #21 

Let me know what works! My email is vince@scaphold.io

**Comment by JacopoDaeli** [comment]
For sure man :-) what do you have in mind?

**Comment by vning93** [comment]
Happy new year! We could speak about GraphQL Subscriptions from a service perspective while you're there as well and perhaps provide a collaborative demo.

If you want to focus on Node and MQTT, we can provide a different approach to implementing real-time subscriptions with Redis.

**Comment by JacopoDaeli** [comment]
@vning93 works for me mate. Let see if we get a spot for presenting this in February.

**Comment by vning93** [comment]
Yeah sounds good! Hopefully

**Comment by paulgrock** [comment]
@JacopoDaeli @vning93 would you two be up for doing this talk in February?

**Comment by JacopoDaeli** [comment]
HI, which day?

**Comment by paulgrock** [comment]
Sorry about that. The event is on Thursday the 2nd.

**Comment by JacopoDaeli** [comment]
It should work for me.

**Comment by vning93** [comment]
Works for me as well @paulgrock!
@JacopoDaeli Want to hop on a call to share topics so we don't step on each other's toes?

**Comment by JacopoDaeli** [comment]
@vning93 sure, I will let you know when I will be available. 
I am traveling for the next 2 week for work, and my schedule is pretty tight, but I am sure we can schedule a call end of next week. I will be in Paris, so my evening will be your morning... it should work :-) I keep you posted.

**Comment by paulgrock** [comment]
@vning93 @JacopoDaeli for the talk title and description what would y'all like us to use on the meet up page? I can just put "graphQL talk" in the title area for now and update the title/description once you two have had a chance to talk if you'd like

**Comment by vning93** [comment]
How about just "Rapid development of real-time apps with GraphQL and Node"? We don't do much with MQTT so might be misleading for our part of the presentation if we don't mention anything about MQTT.

**Comment by JacopoDaeli** [comment]
@vning93 I use MQTT for some specific reasons that I want to explain because it's very important especially when developing real-time mobile application. Think for example low battery consumption: MQTT is optimised for this.
What about "Rapid development of real-time apps with GraphQL, Node.js and MQTT" ?

**Comment by vcn8fn** [comment]
Ah that makes sense. That works! Would you like to hop on a quick call to go over details? My email is vince@scaphold.io.

**Comment by JacopoDaeli** [comment]
Sweet, we'll do soon @vcn8fn! @paulgrock all good for you? Can you confirm our talk? 

Title: Rapid development of real-time apps with GraphQL, Node.js and MQTT

**Comment by paulgrock** [comment]
@JacopoDaeli @vcn8fn yep I'm good. The talk is confirmed and the [event page](https://www.meetup.com/sfnode/events/228990242/) has been updated with the new title.

**Comment by JacopoDaeli** [comment]
@paulgrock can you just quickly update my bio in the meetup event?

Jacopo Daeli (@JacopoDaeli) is a Computer Scientist, Software Engineer and Hacker, passionate about web technologies. He develop with Node.js, Go, C/C++, React and Redux for the web. After a couple of years in London, where he worked as Chief Software Engineer for Impero, Jacopo is now working as Head of Software Engineering at Pikichat, a French company which operates Tribe – the famous Video Messenger application – in Paris and San Francisco through the US subsidiary.

**Comment by paulgrock** [comment]
@JacopoDaeli done and done.

**Comment by JacopoDaeli** [comment]
Ah ah, thanks. Just wanted to remove my Twitter user and link my name to my website directly.  You are to quick, didn't have time to update my comment :-)

**Comment by paulgrock** [comment]
updated again 😄

**Comment by JacopoDaeli** [comment]
Sweet, thanks a lot. See you at the event.

**Comment by vning93** [comment]
This is awesome @paulgrock @JacopoDaeli ! Super excited to be speaking here.

@JacopoDaeli The bio looks great!
Can you update the link to Scaphold.io to (https://scaphold.io/?source=sfnode) though?

Cheers!

**Comment by paulgrock** [comment]
@vning93 done

**Comment by paulgrock** [comment]
@jacopodaeli and @vning93 are you two here? If so can you come find me. I'm the really tall guy in a light blue shirt

**Comment by JacopoDaeli** [comment]
@paulgrock here we go:
https://speakerdeck.com/jacopodaeli/sfnode-real-time-apps-with-graphql-node-dot-js-and-mqtt

**Comment by paulgrock** [comment]
@JacopoDaeli thanks!
