### ISSUE TITLE
Talk Proposal: Introduction to TypeScript 

### ISSUE THREAD

**Issue by blakeembrey** [sfnode/sfnode#2]
TypeScript is a typed superset of JavaScript that compiles to JavaScript. It enables you to write large applications in Node with greater productivity through features such as powerful autocompletion, future JavaScript support, symbol navigation, code refactoring and static type checking that can detect even the smallest of typos. We'll be learning to use TypeScript that'll run in Node, improve our productivity, as well as discover how we can make use of the existing NPM ecosystem in a statically typed way.

Blake is a full-stack developer specializing in all things JavaScript. He works at MuleSoft, where he spends his time working on open source projects based around RAML, an open source specification for documenting RESTful APIs.

**Comment by dshaw** [comment]
Thanks, @blakeembrey. SFNode meets on the first Thursday of every month. Any preferences or black out dates over the next 3 months?

**Comment by blakeembrey** [comment]
The only restriction I have is this immediate first Thursday - Feb 4th. I won't be in San Francisco, but I'm available the rest of the months.

**Comment by paulgrock** [comment]
@blakeembrey that's perfect. I think we're booked for Feb but either of the following two are still open. Does March or April work better for you?

**Comment by blakeembrey** [comment]
March sounds perfect.

**Comment by paulgrock** [comment]
Awesome. We'll get you added to the march event.

**Comment by blakeembrey** [comment]
Awesome, cheers! Thanks for the quick responses.

**Comment by blakeembrey** [comment]
@dshaw @paulgrock Can I confirm whether this is still happening?

**Comment by paulgrock** [comment]
@blakeembrey yes we're still. Sorry I haven't been in contact for the last month. Let me know if you have any questions

**Comment by blakeembrey** [comment]
Sounds good. Thirty minutes to introduce TypeScript is great. Should be this meetup, right? http://www.meetup.com/sfnode/events/223344180/

If you want a description that's more suited to TypeScript, here's a summary I used last month:

> TypeScript is a typed superset of JavaScript. It introduces a static type system to a language used everywhere.

> Blake is a software engineer at MuleSoft. He has been using TypeScript over the last year, working alongside the community as a member of TypeStrong, maintainer of TSD, and author of Typings and TypeScript Node.

**Comment by paulgrock** [comment]
Yep, that's the right one. We're just finishing up locking down a host then we should be able to announce. I've updated the description to have the new bio/description for you. Let me know if you'd like anything changed.
