### ISSUE TITLE
Getting Started with Chat-Bots in Node.js

### ISSUE THREAD

**Issue by Whelpley** [sfnode/sfnode#20]
# Chat-Bots in Node.js

## Abstract

This talk begins with a overview of the chat-bots landscape, explaining what they area and how they have appeared through the years, and why they are experiencing a resurgence in recent times. I then dive into a description of a specific application I made for GetHuman. While interning with them, I made a chat bot app in Node that enables customers to access their database of customer-service contact information via Slack and Facebook Messenger

###  Specs

No live coding for this one, just some slides of selected code.

No audio needed.

### Bio
Michael Whelpley (@mv_whelpley) is a former chef and culinary expert, who has recently changed careers to the world of code. He reformatted his wetware at Dev Bootcamp, and recently has produced his first major project outside of school. He is now looking for full-time employment in the Bay area.

### Slides:
[Viewable here](https://docs.google.com/presentation/d/17HyGDFXk4ROQWMqRaN0qVnXlISnt-BkbFkRKBegVchA/)

### Video:
 https://t.co/qQUYObDebl

**Comment by paulgrock** [comment]
@Whelpley are you interested in presenting at our February event on the 2nd?

**Comment by Whelpley** [comment]
Hi Paul,

I'd be delighted to!

What should I know about adapting my talk to this meetup's presentation
format?

Cheers,
Michael

**Comment by paulgrock** [comment]
The talks are usually 20-30 minutes with some Q&A time afterwards if you'd like that.

**Comment by Whelpley** [comment]
I could definitely adapt to that format. Is there anything else I need to
know?

**Comment by paulgrock** [comment]
Not really. The video you linked seems pretty similar to what we have going on at our events. If you'd like to check out some of the past presentations our youtube channel is https://www.youtube.com/channel/UCbWHWaCKZqIm5pE5hSD7KFw. That should give you an idea of how we do things.

**Comment by paulgrock** [comment]
@whelpley do you have your slides posted online anywhere or could you email them to me? We'd love to have them for the video

**Comment by Whelpley** [comment]
Hi,

I currently have the slides on Google - let me know if this link does not
work for you, and I can export it to a PDF (or other preferred format):

https://docs.google.com/presentation/d/17HyGDFXk4ROQWMqRaN0qVnXlISnt-BkbFkRKBegVchA/edit#slide=id.p

It was thrill presenting - thank you for giving me the space to speak!

Cheers,
Michael

**Comment by paulgrock** [comment]
Thanks @Whelpley
