### ISSUE TITLE
GraphQL, Node, Tools & Services

### ISSUE THREAD

**Issue by vning93** [sfnode/sfnode#21]
**Full name and Bio**

[Vincent Ning](@vning93) is a co-founder of [Scaphold.io](https://scaphold.io), a backend-as-a-service platform powered by GraphQL. He used to work at Microsoft as a software engineer for about a year before he and his roommate [Michael Paris](@mlp5ab) (also ex-Microsoft) decided it was time to create a more rapid hi-fidelity app-building experience. He's currently based out of the Bay Area running Scaphold full-time as part of the Winter 2017 Y Combinator batch, helping to grow the thousands of apps that are built on the platform.

**Talk title and abstract**

GraphQL is a new application level query language recently released by Facebook. Since its release, developer communities around the world have speculated that GraphQL may very well be the future of APIs. Particularly, the ReactJS community has embraced GraphQL as a more functional replacement for REST.  Coupled with the growing popularity of RelayJS, a GraphQL-optimized network layer for ReactJS apps, adoption has been accelerated tremendously.

In this talk, the speaker will describe how we run and scale GraphQL servers in production using NodeJS, along with the tools and services you can use to get started with GraphQL as fast as possible.

**Social**

[LinkedIn](https://www.linkedin.com/in/vcning)
[Github](https://github.com/scaphold-io)
[Blog](https://scaphold.io/blog/)
[Twitter](https://twitter.com/ScapholdDotIO)
[Facebook](https://www.facebook.com/scaphold/)

**Specs**

No live coding, but will show code snippets and slides.
No audio needed.

Cheers!

**Comment by paulgrock** [comment]
@vning93 do you have your slides posted online anywhere or could you email them to me? We'd love to have them for the video.

**Comment by vning93** [comment]
Just emailed them to you. Thanks again for hosting us!
