### ISSUE TITLE
Service Discovery with Node.js and Consul

### ISSUE THREAD

**Issue by tlhunter** [sfnode/sfnode#22]
### Full name and Bio
**Thomas Hunter II**: Thomas is passionate about technology and building products. A web design business created while attending college slowly evolved into a brick and mortar on Main St. of his small Midwestern hometown. His desire for fame and fortune led to the co-founding of a Y Combinator startup and a life in California.

### Talk title and abstract
**Service Discovery with Node.js and Consul**: Get an overview of how Consul, a Service Discovery tool, can be used to dynamically scale your Node based services. Each service will be able to find each other and report their livelihood via heartbeat all while caching an up-to-date list of service locations locally.

### Twitter handle
@tlhunter

### Other social profiles or personal blog
https://thomashunter.name

### Url to slides or github
https://thomashunter.name/presentations/node-consul-v1
https://github.com/tlhunter/consul-haproxy-example

### Are you going to be live coding?
No

### Do you need audio from your computer?
No

**Comment by paulgrock** [comment]
@tlhunter would you like to give this presentation at the March event on the 2nd?

**Comment by tlhunter** [comment]
Yes, that time would be great for me.

**Comment by paulgrock** [comment]
Hey @tlhunter. Thanks for the talk last night. The video of your talk is up at https://www.youtube.com/watch?v=I1lLzPb3MLg.
