### ISSUE TITLE
Robust Error Handling In Node.js Applications

### ISSUE THREAD

**Issue by LewisJEllis** [sfnode/sfnode#23]
Hi SFNode!

### Speaker bio
Lewis Ellis is a software engineer working for Sentry, the open source crash reporting and error tracking service. He maintains Sentry's [Node.js client](https://github.com/getsentry/raven-node) which reports 100 million errors every week.

Some of his other [open source](https://github.com/LewisJEllis) work includes [Bee-Queue](https://github.com/LewisJEllis/bee-queue) and [SuperPack](https://github.com/shapesecurity/superpack-spec). Besides that, he likes numbers, security, Redis, Lua, and JavaScript trivia.

### Talk title
Robust Error Handling in Node.js Applications

### Quick description
Unlike other platforms, error handling in Node.js is not as simple as try/catch.

It can be a handful between exceptions, callbacks, promises, event emitters, and other library patterns.

In this talk, learn to navigate the different error handling mechanisms and build robust Node applications so that when unhandled errors do happen, we can fail gracefully, alert someone, and minimize downtime.

### Detailed breakdown

This talk seeks to give a complete overview of modern best practices around errors in Node,
covering various things developers should watch out for, do, and not do. It builds up to an
overview of how to minimize the potential impact of errors to a production Node application.

Subtopics to be covered include:
- Where does the try-catch paradigm work?
- Where and why does it fall short in Node?
- What's the difference between an error and an exception, anyway?
- Operational errors vs programming errors: what can or can't we recover from?
  - Common operational errors to check for and recover from
  - Common programming errors to avoid making: be defensive!
- How does the err-back pattern work? How should I be using it?
- What's special about an EventEmitter's `error` event?
- How do promise rejections work? What do `catch` handlers do?
- How do errors work with domains, and should I be using them?
- When to use which error mechanisms and why
- How does Express do error handling? How do I fit it in with all this other stuff?
- How does the upcoming async_hooks API fit into the picture?
- How run-to-completion semantics and the event loop make some things trickier
  - Current-call-stack stack traces vs full asynchronous stack traces
- How to set up a global handler for uncaught exceptions
- What a global exception handler should and should not do
  - The danger of carrying on in an unknown state
  - Sending an alert that something broke
  - Cleaning up resources and allowing active requests to finish
  - Restarting without downtime

Target audience:
  - Node.js developers of any level, beginner-advanced
  - Intermediate-advanced developers on other backend platforms who are interested in Node
  - Intermediate-advanced frontend JavaScript developers who are interested in Node

Takeaways:
  - An overview of how error handling works in Node, especially with asynchronous APIs, and do's/do-not's around the different error handling mechanisms
  - A complete breakdown of what's needed to build robust Node applications that will minimize unhandled errors, but fail gracefully when they inevitably do happen.

Prerequisites:
 - Some familiarity with JavaScript: know what a callback is.
 - Some familiarity with try/catch exception handling: know how catch and finally work.

### Other details
- I'm [@LewisJEllis](https://twitter.com/lewisjellis) on Twitter and also @LewisJEllis on GitHub.
- [Here's](https://www.youtube.com/watch?v=GeM22aTO4Ks) a video/slides of a talk on "Idiosyncrasies of NaN" I gave at WaffleJS.
- Slides will be in a GitHub repo once I make them.
- There will be some small code examples, but not massive live coding.
- I don't need audio from my computer.
- If this talk sounds good, I'd like to give it at the March meetup if possible.

**Comment by paulgrock** [comment]
Hi @LewisJEllis. The video for your talk is up at https://www.youtube.com/watch?v=7G3C8Y5tzw4. Are your slides available anywhere that I can link in the video description?

**Comment by LewisJEllis** [comment]
Cool, thanks! Yep, just threw them up on speakerdeck: https://speakerdeck.com/lewisjellis/robust-error-handling-in-node

**Comment by paulgrock** [comment]
@LewisJEllis thank you, sir!
