### ISSUE TITLE
OpenTable as a venue sponsor

### ISSUE THREAD

**Issue by tlhunter** [sfnode/sfnode#26]
I'd like to volunteer OpenTable as a potential venue location. We're located at 1 Montgomery St on the seventh floor.

Here's a picture of our space (before recent remodeling):
https://a248.e.akamai.net/secure.meetupstatic.com/photos/theme_body/d/7/f/0/full_6835280.jpeg

We can seat up to 120 people.

**Comment by paulgrock** [comment]
@tlhunter is OpenTable interested in hosting June 1st?

**Comment by tlhunter** [comment]
I'm checking with the appropriate channels now.

**Comment by tlhunter** [comment]
@paulgrock Are you looking for building and food/beer sponsoring or do you normally have separate sponsors?

**Comment by paulgrock** [comment]
@tlhunter we'd prefer to have the host provide food and drinks.

**Comment by tlhunter** [comment]
@paulgrock I've gotten it confirmed that we can host and feed SF Node on June 1st.

**Comment by paulgrock** [comment]
@tlhunter That's fantastic! Could you track down the answers to the following questions for us as well? Once we get those we'll update the meetup page with OpenTable's info.

- What is the address, floor, room name if any, entrance instructions?
- Do we need to submit an attendee list for security purposes?
- What's the total number of people that space can hold?
- Will food and drinks will be provided? Are there vegetarian and gluten free options?
- What is the AV setup like?
- What is the microphone setup? Mic stand or headset mic?
- What is the parking situation like? Is bike parking available? Any off-street parking?

**Comment by tlhunter** [comment]
* OpenTable, Floor 7, 1 Montgomery St, San Francisco, CA 94104
* No attendee list is required, we can have someone badge visitors up
* We usually set our Meetup max to 120, we can realistically seat maybe 90
* We can provide food and drinks. We normally have Vegetarian options. I'm unsure about Vegan.
* We have a large projector and an available HDMI port
* We can support both a handheld mic and a clip-on mic at the same time. No mic stand, however.
* We don't have parking available, either for vehicles or bikes. No street parking nearby.

**Comment by paulgrock** [comment]
@tlhunter Thanks for the info. That's all we should need for now.

**Comment by paulgrock** [comment]
@JasonNierrasOT sounds goods. I updated the address on the meetup page https://www.meetup.com/sfnode/events/231626003/. As we get closer to the event I'll pass along more details about the presentations.

**Comment by paulgrock** [comment]
hey @JasonNierrasOT and @tlhunter just checking in to make sure everything is on track for the event in a few weeks. Is there anything you'd like from us at the moment?

**Comment by tlhunter** [comment]
I think we're set for now.

Do you know who the speakers will be? When will you open RSVP's for the event?

**Comment by paulgrock** [comment]
@tlhunter we're opening RSVP's tomorrow. The talks for the night are #33 and #32.

**Comment by tlhunter** [comment]
Great! Please email us at meetup@opentable.com if anything urgent comes up.

**Comment by paulgrock** [comment]
Just sent over the guest list.
