### ISSUE TITLE
Numeric Computing with Node.js

### ISSUE THREAD

**Issue by kgryte** [sfnode/sfnode#27]
## Title

> Numeric Computing with Node.js

## Abstract

Node.js and number crunching may seem an odd pair, but this is rapidly changing. In this talk, Athan will discuss the current state-of-the-art for numeric computation in Node.js and highlight emerging technologies and libraries for analysis and machine learning. He will discuss what to look for in numeric computing libraries, common implementation mistakes, and how to avoid portability issues. And he will conclude by explaining why Node.js is poised to become the next big thing for data science and numeric computation.

## Bio

Athan Reines is a full-stack engineer and data scientist. He has a PhD in Physics, where he used machine learning and time series analytics to probe biological systems at the nanoscale. He currently works full-time on open source projects to facilitate numeric computing in Node.js and JavaScript. To see his latest project, check out [stdlib](https://github.com/stdlib-js/stdlib), a standard library for Node.js and JavaScript.

## Twitter

[@kgryte](https://twitter.com/kgryte)

## GitHub

[@kgryte](https://github.com/kgryte)

## Requirements

Living coding: no.
Audio from computer: no.

**Comment by paulgrock** [comment]
Hi @kgryte are you interested in giving this talk at our April event on 4.6?

**Comment by kgryte** [comment]
@paulgrock I won't be in the country for the April event. :(

Would I be able to speak at the May (5.4) event?

**Comment by paulgrock** [comment]
@kgryte May works for me.

**Comment by kgryte** [comment]
Awesome!

**Comment by paulgrock** [comment]
Hey @kgryte we're trying out something different for our May event and it is going to be in Emeryville. Does that still work for you? If not we can reschedule for another month.

**Comment by kgryte** [comment]
Will the venue be easily accessible via BART?

**Comment by paulgrock** [comment]
You can get there via the emerygoround from MacArthur Bart. It stops right on the corner near the building. That's how I plan to get there.

**Comment by kgryte** [comment]
Yes, I can swing Emeryville.

**Comment by paulgrock** [comment]
Awesome! Thanks!

**Comment by kgryte** [comment]
Link to my slides: https://kgryte.github.io/talks-sfnode-may-2017

**Comment by paulgrock** [comment]
Thanks @kgryte Great talk!
