### ISSUE TITLE
Talk Proposal: Getting Started with GRPC and Node.js

### ISSUE THREAD

**Issue by tejasmanohar** [sfnode/sfnode#29]
## About Tejas Manohar
Tejas Manohar is an engineer at [Segment](https://segment.com/). He's helped maintain many popular Node.js modules, including [node-schedule](https://github.com/node-schedule/node-schedule) and [koa](https://github.com/koajs/koa/tree/v2.x). In his leisure time, Tejas hacks on [Quilt](https://github.com/NetSys/quilt), a simple way to use JavaScript to build and manage anything from website backends to complex distributed systems, at UC Berkeley.

## Abstract
[GRPC](http://www.grpc.io/) is an RPC framework built on top of HTTP/2 and Protocol Buffers. It allows you to define your API as simple functions, and generate idiomatic clients for a variety of platforms, including Node.js, without worrying about the underlying networking. We'll walk through building a GRPC service in Node.js and using it from anywhere. I'll also share my tips and tricks from running it in production.

## Social
[Twitter](https://twitter.com/tejasmanohar)
[GitHub](https://github.com/tejasmanohar)
[Medium](https://medium.com/@tejasmanohar)

### Are you going to be live coding?
Yes.

### Do you need audio from your computer?
No.

**Comment by paulgrock** [comment]
@tejasmanohar are you interested in speaking at our April event on the 6th?

**Comment by tejasmanohar** [comment]
For sure! @paulgrock

**Comment by paulgrock** [comment]
@tejasmanohar Great! I'll add your info to the meetup page.

**Comment by paulgrock** [comment]
Thanks for giving a talk the other day, @tejasmanohar. The video of your talk is up at https://www.youtube.com/watch?v=U7GTHv0bn3w

**Comment by tejasmanohar** [comment]
Thanks! I really enjoyed it.
