### ISSUE TITLE
Using Google BigQuery and the Cloud Vision API to analyze Reddit

### ISSUE THREAD

**Issue by JustinBeckwith** [sfnode/sfnode#3]
![CLOUDCATS](http://i.imgur.com/lzR8TDn.jpg)

Gathering deep meaning from images has traditionally been hard.  The [Google Cloud Vision API](https://cloud.google.com/vision/docs/)  can quickly classify images into thousands of categories, detect individual objects, landmarks, animals, and even facial expressions.  Combining the vast amount of data on [Reddit](reddit.com) with this API can produce some interesting results - and lots of data!  In this talk we'll show how to build a data analysis pipeline from Reddit, analyze the media with the Cloud Vision API, and stream it into Google BigQuery for real time analysis - all in JavaScript.  

**About Justin**
Justin is a product manager, web developer, and geek dad working on the developer experience for Google Cloud. He writes JavaScript, herds cats, and rocks out on the ukulele. Before joining Google, he filled various developer and architect roles with startups, healthcare companies, and universities.  He blogs at [jbeckwith.com](http://jbeckwith.com) and twitters as [@justinbeckwith](http://twitter.com/JustinBeckwith).

**Comment by paulgrock** [comment]
Hey @JustinBeckwith I just added your talk details to http://www.meetup.com/sfnode/events/223344186/. Everything look good?

**Comment by JustinBeckwith** [comment]
Looks good!

**Comment by paulgrock** [comment]
This talk was awesome. Thanks @JustinBeckwith
