### ISSUE TITLE
Talk Proposal: Introduction and Best Practices for TypeScript

### ISSUE THREAD

**Issue by nebrius** [sfnode/sfnode#32]
### Personal Info

**Name:**

Bryan Hughes

**Twitter Handle:**

[@nebrius](https://twitter.com/nebrius)

**Bio:**

Bryan Hughes is a Developer Evangelist at Microsoft and member of the [Node.js Technical Steering Committee](https://github.com/nodejs/TSC) and [Node.js Community Committee](https://github.com/nodejs/community-committee). Bryan is the creator of [Raspi IO](https://github.com/nebrius/raspi-io), a Raspberry Pi plugin for the [Johnny-Five JavaScript robotics library](http://johnny-five.io/). Outside of tech, Bryan is an [amateur photographer](https://500px.com/nebrius), [occasional writer](https://medium.com/@nebrius), a once upon a time pianist, and a wine aficionado.

### Talk Info

**Abstract:**

The dynamic nature of JavaScript enables developers to iterate rapidly from concept to production. TypeScript is a superset of JavaScript that facilitates writing robust applications by giving you type-safety and features such as modules, classes and interfaces. Bryan Hughes will share best practices for integrating TypeScript into both Node.js and web workflows, and how teams can benefit from the features TypeScript offers.

**Live coding:**

I _may_ live code if there's enough time, but I suspect there won't be enough time.

**Audio:**

no audio needed

**Comment by paulgrock** [comment]
@nebrius are you interested in giving this talk at our June event?

**Comment by nebrius** [comment]
@paulgrock I am yes! Just to confirm, the June event is Thursday June 1st, correct?

**Comment by paulgrock** [comment]
@nebrius yessir it is.
