### ISSUE TITLE
Quilt: JavaScript for Cloud Infrastructure

### ISSUE THREAD

**Issue by luise** [sfnode/sfnode#33]
## Abstract
Container orchestrators  have made great progress towards easier deployment and management of distributed applications. However, the process remains difficult, time consuming, and inefficient, largely due to rigid YAML/JSON or RESTful APIs. 
In this talk, Ethan will introduce [Quilt](http://quilt.io), a research project out of UC Berkeley, that aims to solve this issue with a new open source JavaScript framework that provides a simple and flexible way to deploy anything from a MEAN stack application to complex distributed systems.

## About Ethan J. Jackson
[Ethan J. Jackson](http://ejj.sh/) is a PhD student at UC Berkeley studying Computer Science, advised by Scott Shenker, and supported by an NSF Fellowship. He leads both development and research on [Quilt](http://quilt.io). Previously, he was a major contributor to Open vSwitch, focusing on Software-Defined Networking, Network Virtualization, and high performance software switching.

## Social
**Github**: [ejj](https://github.com/ejj)

## Requirements
**Live Coding**: Yes
**Audio from Computer**: No

**Comment by paulgrock** [comment]
hi @luise would you like to present during our June event on the first?

**Comment by luise** [comment]
@paulgrock , that would be awesome!

**Comment by paulgrock** [comment]
@luise Great! I'll add you to the meetup page.
