### ISSUE TITLE
Utilizing tools to build GraphQL backend for rapid development

### ISSUE THREAD

**Issue by TingC** [sfnode/sfnode#35]
# Abstract
GraphQL is a powerful technology providing client an efficient and elegant way to fetch data, getting exactly the data and avoid multiple round-trips.

The GraphQL community is evolving fast, with various tools emerging for HTTP server integration, query and mutation support, schema translations and ORMs. I'm a co-author of library called [Allograph](https://github.com/allograph/allograph). Allograph aims to integrate the various tools around GraphQL to provide a rapid development framework to enhance developer experience. In this talk, I'm going to show not only how to use Allograph, but go in detail on how we built Allograph from scratch, the considerations and choices we made along the way, and the tools we decided to include and leave out.

There'll be topics beyond what you see in "Introduction to GraphQL" tutorials. After the talk, you'll gain deeper understanding on GraphQL itself, with perspectives on how to build a GraphQL backend either alongside an existing app or from scratch.

# Bio
[Ting Chou](https://github.com/TingC) is a web developer in San Francisco, CA. She is co-creator of a GraphQL backend framework called Allograph, and she loves animation.

**Comment by paulgrock** [comment]
Hi @TingC would you like to present at our July event on the 6th?

**Comment by TingC** [comment]
Yes, @paulgrock that would be great!
