### ISSUE TITLE
Talk: Big Shiny Button, Must Hit.

### ISSUE THREAD

**Issue by morganrallen** [sfnode/sfnode#37]
Or..

# Using Electron in a Stop Motion Animation Booth

An exploration of using `Electron`, `Arduino`, `node-serialport` and a bit of Linux magic to create a stop motion animation booth for museum visitors. 
Fun topics include...

- The Electron in the Carpet
- Small hands can grip small parts
- How did all these wires get twisted?
- How live logging can tell you the future (it's about to break)

# Bio
Morgan works at the Chabot Space and Science Center in Oakland, California in a job that can only be described as a carpenter with a soldering iron. When presented with the opportunity to build interactive exhibits, leveraging 15+ years of experience with web technologies was the obvious choice.

Live coding: No
Audio: No
Screen Sharing: Yes

**Comment by paulgrock** [comment]
hey @morganrallen are you available to present next Thursday in Emeryville?

**Comment by morganrallen** [comment]
4th? Yeah, think I can swing that

**Comment by paulgrock** [comment]
Yep the fourth. Cool, I'll add your details to the Meetup page. Looking forward to hearing the talk.

**Comment by paulgrock** [comment]
@morganrallen will you send me a link to your slides from the other night?

**Comment by morganrallen** [comment]
Here ya go. https://gitlab.com/morganrallen/nodejs-big-shiny-button

Thanks again for having me.

**Comment by paulgrock** [comment]
@morganrallen thanks for speaking. Your talk was awesome!

**Comment by paulgrock** [comment]
@morganrallen are these available anywhere that we can link to?

**Comment by morganrallen** [comment]
Sorry that took so long
http://morganrallen.gitlab.io/nodejs-big-shiny-button/
