### ISSUE TITLE
Talk: Docker + Codeship - Development to Deployment in 30 minutes

### ISSUE THREAD

**Issue by kellyjandrews** [sfnode/sfnode#39]
Building software these days has changed in dramatic ways, increasing the pressures to deliver software at a fast pace. If you aren’t already using test automation and Continuous Integration/Continuous Deployment (CI/CD) in your workflow, then you may be running less efficiently than you realize.

In this talk, Kelly Andrews from Codeship will take an application, Dockerize and run it locally, then test and deploy using Codeship. You should walk away with the information you need to switch to a workflow designed for fast delivery. All in about 30 minutes.

[**Kelly J Andrews**](https://twitter.com/settings/account), is a developer advocate, currently working at Codeship. Kelly has been tinkering with computers for over 30 years, using BASIC for the first time at the prime age of 5.

It wasn't until building his first webpage in 1997, and trying out JavaScript for the first time that he found a true calling. Kelly now fights for JavaScript, testable code, and fast delivery. 

In his free time you can find him singing karaoke, performing magic, or cheering for the Fighting Irish.

Twitter: https://twitter.com/settings/account
Github: https://github.com/kellyjandrews
LinkedIn: https://www.linkedin.com/in/kjandrews/

Are you going to be live coding? **Yes**
Do you need audio from your computer? **No**

**Comment by paulgrock** [comment]
Hi @kellyjandrews are you interest in speaking at our event on august 3rd?

**Comment by kellyjandrews** [comment]
Unfortunately I won't be able to make this. Thanks for the invite though!

**Comment by paulgrock** [comment]
That's too bad. Perhaps our September event on the 7th?

**Comment by kellyjandrews** [comment]
I will also be unavailable. Maybe October?

**Comment by paulgrock** [comment]
Sure, that event is October 5th. Does that work?

**Comment by kellyjandrews** [comment]
I think we can make that work.
