### ISSUE TITLE
What could go wrong? Moving 80 Million Users to React, Redux, & NodeJS

### ISSUE THREAD

**Issue by abritinthebay** [sfnode/sfnode#4]
## Abstract: 

Over the last year and a half Bleacher Report has moved from a monolithic Rails application to a micro-service based system with a front-end powered by an isomorphic React & Redux app running on NodeJS. This is the story of how Bleacher Report incrementally moved their front-end tech stack to this system, the challenges they encountered along the way, and some of their design solutions for this stack - in JavaScript, CSS, and much more.

Complex React applications require deep thinking about State, Styling, Asynchronous Communication, and application structure. Not only that but developer tooling and using sensible modern workflows (like SASS, Browserfiy, ES6/Babel, Promises, etc) can create a codebase that is not only easy to reason about - but a pleasure to maintain.

The team learned a lot doing this, and I'd like to share that with you.

## Speaker Bio
Gregory Wild-Smith is a CLIO award winning web developer who has been a developer for long enough that he's starting to feel kind of old. A UK native he moved to California 10 years ago and has worked at companies such as Hi5, Zynga, and now Bleacher Report.

One day he hopes to build a JavaScript powered Ghostbusters Proton Pack (no, he is not kidding).

**Comment by paulgrock** [comment]
Hi @abritinthebay your talk details are up on http://www.meetup.com/sfnode/events/223344186/ would you mind taking a look at it to make sure all everything is good to go?

**Comment by abritinthebay** [comment]
Looks good!

**Comment by paulgrock** [comment]
Thanks for the really great talk yesterday @abritinthebay!

**Comment by abritinthebay** [comment]
You are very welcome! 👍
