### ISSUE TITLE
Talk: Building Kickass APIs with NodeJS and ExpressJS

### ISSUE THREAD

**Issue by snowcrash007** [sfnode/sfnode#41]
As Express continues to build in popularity, this widely adopted framework is becoming an essential open source tool for optimizing APIs. 

Redesigning an API is a journey, not a destination. As a developer,  it's important to understand how open source tools like ExpressJS could potentially impact your application. Where to start? What are key benefits that ExpressJS could bring to the table? These are just a few of the important questions we've been asked and would love to share practical examples with a broader Node community.

In this talk, Al from LunchBadger will provide a few practical examples with ExpressJS. You will walk away with a new love for Open Source, ExpressJS and use cases.

**About Al Tsang**
Al Tsang has been a technology practitioner for over two decades with enterprise and consumer experience at scale. Al has been widely recognized by the developer community and industry analysts as a thought leader and contributor in the API space. Al’s more recent venture is LunchBadger, a SaaS offering focused on API Empowerment - cloud native, holistic, lifecycle solutions for microservices and APIs. Prior to LunchBadger, he co-founded StrongLoop (acquired by IBM, 2015) as CTO to help bring new generation cloud technologies like NodeJS to market. He created and spearheaded LoopBack the leading open source NodeJS framework for enterprise APIs with his team.

**Comment by paulgrock** [comment]
@snowcrash007 are you interested in presenting at our next event on August 3rd?

**Comment by codebunny19** [comment]
Yes! That would be amazing! What are next steps?

**Comment by paulgrock** [comment]
We've got everything we need from you. We'll add your talk details and such to the meetup page. Then all that's left is the presentation next Thursday. Do you have any questions for us?
