### ISSUE TITLE
Talk: Disco-Era Technology for Better Contracts Today!

### ISSUE THREAD

**Issue by kemitchell** [sfnode/sfnode#42]
## Full name and Bio

Kyle E. Mitchell

Web coder. Redline-munching law-office dweller. Too many npm packages, mostly junk. Open Source licensing, database, markup language, and other tools.

## Talk title and abstract (description)

Disco-Era Technology for Better Contracts Today!

Common Form tools use Node.js, the browser, and disco-era software moves to bring all today's programming favorites---JSON, Git, vim, npm, ESLint, Babel, and friends---to the captivating world of legal contracts! Follow me on an exciting and strictly time-bounded journey through crusty legal forms of yore to the discovery of a simple schema, our passport to a captivating land of cryptographic techniques, database structures, user interface problems, and combinatoric standards complexities that are totally vintage, but totally _hot_ and _all the rage_ right now...again! To mix things up, your less-compelling-than-compulsive host will _absolutely not give legal advice_ about how to sign contracts without reading them, review contracts on your own, download forms for free off the Internet, and otherwise go on about your business like Mr. Magoo in the most litigious society known to human history.

## Twitter handle (optional)

https://twitter.com/kemitchell

## Other social profiles or personal blog (optional)

https://writing.kemitchell.com

## Url to slides or github (either now or can be posted in meetup comments later)

GitHub for Common Form is https://commonform.github.io

No slides, all demo. I can bring my own Thinkpad+Debian machine---_strongly preferred_---or use any loaner with:
- current Chrome
- a well-behaved terminal emulator with bigger-font option
- SSH
- some way to get it a temporary SSH key---USB drive, e-mail
- something that opens Word files
- something that opens PDF files
- USB port for a keyboard I can pound on without guilt

## Are you going to be live coding?

Hope so!

## Do you need audio from your computer?

Naw.

**Comment by paulgrock** [comment]
@kemitchell would you like to present at our August event on the 3rd?

**Comment by kemitchell** [comment]
@paulgrock, I'm sorry! For some reason I didn't receive an e-mail notification of your replies.

Yes, I would be very happy to speak on September 7.

**Comment by paulgrock** [comment]
Great. I'll add you to the meetup page.

**Comment by kemitchell** [comment]
Thank you!
