### ISSUE TITLE
Talk: Async data replication using Backbeat

### ISSUE THREAD

**Issue by rahulreddy** [sfnode/sfnode#43]
**Topic:** Async data replication using Backbeat

**Context:** Backbeat is an open-source project built at Scality Inc., also offering open-source S3 through the new product suite Zenko. Essentially Backbeat is a core engine which can be extended for many use cases where data needs to be manipulated or transitioned. Built in node.js, at it's heart Backbeat uses Kafka as a queue manager and exposes a core engine to manage the queue.

**About Rahul Padigela:**
Rahul Padigela is a Technical Lead at Scality Inc. working on building scalable storage services. He has extensive experience building web-scale applications in Javascript and Node.js in particular.

**Comment by paulgrock** [comment]
@rahulreddy I believe we spoke at the last event and you were interested in presenting at our September event, is that right?

**Comment by rahulreddy** [comment]
That's correct. I am open to present at the September event.

**Comment by paulgrock** [comment]
Awesome. I'll get you added to the event page

**Comment by rahulreddy** [comment]
Thank you!
