### ISSUE TITLE
Follow up - Video for Events

### ISSUE THREAD

**Issue by snowcrash007** [sfnode/sfnode#45]
Hey Team!
Someone mentioned that you all are in search of video capabilities for the meetup and I am happy to get more involved including livestreaming it if that's something that is interesting. Anyway - let me know- we're happy to help and support wherever is needed.

d

**Comment by paulgrock** [comment]
Hi @snowcrash007 we'd love to have your help with video. Dellaena, could you send us an email to temasfnode at gmail and we can discuss specifics?
