### ISSUE TITLE
Talk Proposal: Rapid web development with Huncwot & Marko

### ISSUE THREAD

**Issue by zaiste** [sfnode/sfnode#46]
## Abstract 
[Huncwot](https://github.com/zaiste/huncwot) is an opinionated & minimal Node.js (yet another) web framework, slightly inspired by Clojure and built for ES6/7 era with « batteries included » approach. It tries to formalize conventions and eliminate choices by providing solid defaults for building web applications that increase the programmers productivity. In this talk we'll explore how to build an application with Huncwot, what it brings to the table and how to make (web) programming more approachable, especially to non-programmers.

## A bit about me 
I run a software company in Paris called [Nukomeet](https://nukomeet.com/). In my spare time I organise [PolyConf](https://polyconf.com). Twitter: [@zaiste](https://twitter.com/zaiste)

PS. If accepted, I'd like to be considered for the event on Oct 5th

**Comment by paulgrock** [comment]
hi @zaiste we'd love to have you speak at our October 5th event.

**Comment by zaiste** [comment]
@paulgrock Thank you for accepting my proposal! I'm looking forward to the event, see you soon!
