### ISSUE TITLE
Talk Proposal: Let's build a Chatbot (sfnode-bot) using Microsoft's Bot Framework, LUIS and Node.js

### ISSUE THREAD

**Issue by Zahidul-Islam** [sfnode/sfnode#47]
#### Abstract

This talk  will start with a very brief overview of what **Chatbot** are,  why we should care and the landscape?  Then we will explore the **Chatbot lifecycle**, Microsoft's **Bot Framework** and **LUIS (NLU)**. Together we will implement a simple **Chatbot (sfnode-bot)** which will be able to answer basic question about SFNode Meetup.

#### Bio

Zahidul Islam (@zahidsharp) is a Node.js developer who is passionate about JavaScript, Functional Programming, Conversational AI (ChatBot), NLP. He is currently exploring Deep Learning and TensorFlow.

**Comment by paulgrock** [comment]
Do you have a link to your slides that we can share with the attendees?

**Comment by Zahidul-Islam** [comment]
Here is the link: https://docs.google.com/presentation/d/1t6-T0jazRlrSyI5uSQ74OFTwIfX5Ssz2lxSN4rSeoo0/edit?usp=sharing
