### ISSUE TITLE
Talk Proposal: AbeCMS - The lightning fast CMS

### ISSUE THREAD

**Issue by gregorybesson** [sfnode/sfnode#49]
# Abstract
[![AbeCMS](https://avatars2.githubusercontent.com/u/23280205?v=4&s=50)](https://github.com/abecms/abecms) is an open source (MIT) CMS framework proudly propelled by NodeJS and Express 4.
Already adopted by big companies and US startups, AbeCMS revolutionize the way we create CMS pages by proposing a markup language to dynamize your html pages and create the back-office in the same time.
In this code&talk (interactive demo: Everybody is invited to code during the demo) we'll explore how to build and publish a CMS in minutes, "the web is your template": By showing how easy it is to transform any HTML into a CMS template, I want to give people the power to create beautiful websites with content in mind... In no time !

# About me: Gregory Besson
I've founded [Adfab Connect](http://adfab.fr), a 70 people software company based in Paris,France and Montreal,Canada. I've created [AbeCMS](https://avatars2.githubusercontent.com/u/23280205?v=4&s=50) because I was fed up with the complexity of WordPress, Drupal, Ghost etc...
Since September my new startup [Abe](https://avatars2.githubusercontent.com/u/23280205?v=4&s=50) is incubated by [TheRefiners](http://www.therefiners.co/) in San Francisco. My goal is to give designers and HTML coders the power to create CMS websites.
LinkedIn: https://www.linkedin.com/in/gregorybesson/
Twitter: @gregorybesson
Blog: http://industrialize.it/

**Comment by paulgrock** [comment]
Do you have a link to your slides that we can share with the attendees?
