### ISSUE TITLE
The Node.js Ecosystem in Perspective

### ISSUE THREAD

**Issue by dshaw** [sfnode/sfnode#5]
Dan Shaw, CTO and Co-Founder of NodeSource.
http://twitter.com/dshaw

## The Node.js Ecosystem in Perspective

Node.js was created 7 years ago by Ryan Dahl to increase the performance of web application development. Node.js was born in the era of GitHub which led the project's phenomenal contribution story. It has superseded jQuery as the most important JavaScript project ever. Node.js is far from being the first server-side JavaScript platform, but nothing prior has had anywhere close to the impact it has. Node.js is rapidly transforming application development from an environment dominated by Java to one dominated by JavaScript.

Many novel choices were made along the way. Node.js ships with "batteries included". Node.js was built with a very liberal license. Node.js has no standard library and encourages userland experimentation. Node.js chose to standardize on a single package management solution with npm. Node.js is fully cross-platform. Node.js applications run everywhere (take that Java!). All of this comes together to create an extraordinary ecosystem.

Dan Shaw will explore the implications of these decisions and how they have impacted the Node.js Ecosystem. 7 years on, Node.js is everywhere with a massive user base and the largest package registry ever. And yet, there's still so much to do.

### Bio

Dan Shaw (dshaw) is Co-Founder and CTO of NodeSource, the Enterprise Node Company, and is dedicated to helping improve and grow the Node Community. He is a veteran of numerous Node.js startups including Voxer, Spreecast and Storify. Dan has extensive experience building large-scale, realtime systems with Node.js and has been building production services using Node since v0.2. Dan is a frequent speaker, host of the NodeUp podcast and organizer of events like EnterpriseJS and the SFNode meetup. Prior to Node, Dan worked in large-scale government contracts for Defense, Health Care and Education.

**Comment by paulgrock** [comment]
This has been added to the [July event page](http://www.meetup.com/sfnode/events/224882983/).
