### ISSUE TITLE
Talk Proposal: The Long Road to Async/Await in JavaScript

### ISSUE THREAD

**Issue by tlhunter** [sfnode/sfnode#50]
Talk might be redundant with tonights https://github.com/sfnode/sfnode/issues/48 talk.

## Full name and Bio

**Thomas Hunter II** is passionate about technology and building products. A web design business created while attending college slowly evolved into a brick and mortar on Main St. of his small Midwestern hometown. His desire for fame and fortune led to the co-founding of a Y Combinator startup and a life in California.

## Talk title and abstract (description)

**The Long Road to Async/Await in JavaScript**: This is a comparison of different methods for performing asynchronous control flow in JavaScript, specifically Callbacks, Promises, Generators / Yields (ES2015), and Async / Await (ES2016). We will explore a simple code example as it applies to each of these different "phases" of asynchronous control flow. Finally we'll examine how Async functions are just Promises under the hood and that the two are interoperable.

## Twitter handle
https://twitter.com/tlhunter
## Other social profiles or personal blog
https://thomashunter.name
## Url to slides or github
https://thomashunter.name/presentations/async-await-javascript-v1/
## Are you going to be live coding?
No
## Do you need audio from your computer?
No

**Comment by paulgrock** [comment]
@tlhunter are you interested in presenting at the March event on the 1st?

**Comment by tlhunter** [comment]
@paulgrock sure! I am giving this talk at ForwardJS in February, btw.

**Comment by paulgrock** [comment]
Oh rad. Congrats on that! We'll add you to the March list. Thanks @tlhunter
