### ISSUE TITLE
Talk Proposal: JWTs Suck

### ISSUE THREAD

**Issue by rdegges** [sfnode/sfnode#51]
JSON Web Tokens (JWTs) are all the rage in the security world. They’re becoming more and more ubiquitous in web authentication libraries, and are commonly used to store a user’s identity information.

In this talk Randall Degges, Head of Developer Advocacy at Okta, will take you on an extensive tour of the web authentication landscape. You’ll learn how JWTs and Sessions work, and why JWTs are the worst possible solution for solving web authentication problems.

You’ll also learn the real reason behind JWTs rise to fame, and better ways to secure your websites that don’t involve misplaced hype.

About Randall

Randall Degges leads Developer Advocacy at [Okta](https://developer.okta.com/), previously Stormpath, where he builds open source security libraries and helps make the internet a little safer. In a prior life, Randall was the CTO of OpenCNAM, the largest Caller ID API service.

In his free time, Randall geeks out on web best practices, explores new technologies, and spends an inordinate amount of time writing Python, Node, and Go projects. As a fun fact, Randall runs ipify.org, one of the largest IP lookup APIs which serves over 27 billion requests per month.

He writes at [https://www.rdegges.com](https://www.rdegges.com/), and tweets as [@rdegges](https://twitter.com/rdegges).

**Comment by Trott** [comment]
Personally, I would prefer if the title were a bit more descriptive and less clickbait-style. Although I guess "JWTs Suck" is more succinct and catchier than "JWTs May Not Be The Best Choice For Many Use Cases Where They Are Frequently Deployed". Like, you can dance to "JWTs Suck". I'm doing it right now.

(Disclaimer: I don't organize SF Node or curate talks or anything. I'm a regular attendee, but that's it.)

**Comment by rdegges** [comment]
I gotcha. But this talk is literally about why jwts suck and how horrible they are. All I'm going to do is rant about it for 45 minutes then walk off stage :p I tried to title it as accurately and succinctly as possible ^^

**Comment by Trott** [comment]
Can't complain if it's an accurate reflection of the anticipated content. Please do advise the organizers to provide you with an inexpensive mic to drop on the floor as you exit.

**Comment by rdegges** [comment]
:D that's be awesommeee

**Comment by IAmEddieDean** [comment]
Consider us so notified. 🤣

**Comment by paulgrock** [comment]
Hey @rdegges we're all quite excited about the talk in a couple of months. We talked about it as an organizing team and we'd like to go with a softer title.

Maybe something like:
How JWTs and Sessions Work (Poorly)
Why JWTs Are Bad for Authentication
JWTs: Don't Believe the Hype
The Truth About JWTs
Best Ways to Secure Your Website (Not JWTs)

**Comment by rdegges** [comment]
Hey! That's totally fine. I get it ;)

How about: "Why JWTs Are Bad for Authentication"? That one sounds appealing. Can we still get a safe-to-drop mic though? Would be hilarious ^^

**Comment by paulgrock** [comment]
No promises :)

**Comment by rdegges** [comment]
=p

OK! Well, wanna let me know what the official date is? I'll block off my calendar accordingly! <3

**Comment by paulgrock** [comment]
Sure. It’s Jan 4th. Your talk will either be at 7 or 7:45 ish

**Comment by rdegges** [comment]
Awesome! Just blocked it off. Looking forward to it.

**Comment by paulgrock** [comment]
@rdegges do you have slides online somewhere that we can share with the group?

**Comment by rdegges** [comment]
Yep! The slides are here: https://speakerdeck.com/rdegges/jwts-suck-and-are-stupid

Thanks so much for having me! I had a blast. <3

**Comment by paulgrock** [comment]
Your talk was awesome. Thanks for presenting.
