### ISSUE TITLE
Talk Proposal: A cartoon intro to WebAssembly

### ISSUE THREAD

**Issue by linclark** [sfnode/sfnode#52]
## Full name and Bio

Lin Clark makes code cartoons. She also works in Mozilla’s Emerging Technologies group, where she gets to tinker with things like WebAssembly, Servo, and Rust. In previous lives, she worked at npm, was a core contributor to open source projects like Firefox’s developer tools, and contributed to HTML data standards.

## Talk title and abstract (description)

WebAssembly is fast. It’s being called “the future of the web”. Its speed and potential led major browser vendors to work together to turn it into a reality. But what makes it fast? Starting from the basics, this talk will walk you through what WebAssembly is, and then why it’s fast.

## Twitter handle

https://twitter.com/linclark

## Are you going to be live coding?

No

## Do you need audio from your computer?

No

**Comment by paulgrock** [comment]
Hi @linclark as we talked about we've got a spot at the February event open for you. Looking forward to this talk.
