### ISSUE TITLE
Talk Proposal: Building Prefix Search as a Service

### ISSUE THREAD

**Issue by tiffanyhan** [sfnode/sfnode#54]
## Full name and Bio

Tiffany Han is a software engineer at Prefixy, a free and open-source hosted prefix search service. Before that, she worked on bruinwalk.com and has also done some teaching for Udacity. She finds code strangely addicting and is currently excited about node.js, functional programming, and React. 

## Abstract

How do you build a hosted prefix search service that can power suggestions for a dynamic, google-style autocomplete service? This talk will walk you through how I worked with two other developers to build an open source project called Prefixy to do just that. Topics covered include:

- A deep dive into data structure and algorithm analysis to support efficient prefix search
- Building a ranking algorithm to support crowd-sourced suggestions
- Creating a service that supports multi-tenancy
- Implementation using Node, Express, Redis, and MongoDB

## Link to slides
[slides](https://docs.google.com/presentation/d/12nFHS9Pn1mrh9ckpKqW7WLOAKHaRfI6-3UBfx6zt4Vw/edit?usp=sharing)

## Live coding
No

## Audio
None

**Comment by paulgrock** [comment]
Hi @tiffanyhan would you like to present at our next event on March 1st?

**Comment by tiffanyhan** [comment]
Hi @paulgrock , 

Yeah! March 1st sounds great.
