### ISSUE TITLE
Talk Proposal: Node.js production checklist

### ISSUE THREAD

**Issue by gergelyke** [sfnode/sfnode#55]
## Abstract

At RisingStack, we have helped enterprises to sucessfully adopt Node.js in the past years. During this period, we have seen a lot of anti-patterns and war stories. Because of this, we came up with a list of best practices on how to run Node.js applications in production successfully. This talk addresses both operational, performance and security best practices.

## Bio

Gergely is a prolific author on Node.js and security related articles. Originally from Hungary, he ran the Hungarian Node.js meetup group, and organized Node.js conferences in Budapest. Gergely works at GoDaddy and lives in San Francisco. Loves a good cup of coffee ☕️ .

**Comment by isurfbecause** [comment]
@gergelyke your presentation has been posted. So sorry the long delay.
https://www.youtube.com/watch?v=tJi5PgcrncE
