### ISSUE TITLE
Talk Proposal: The Joy of Express Middleware

### ISSUE THREAD

**Issue by magicmark** [sfnode/sfnode#57]
## Full name and Bio
Mark Larah

Mark Larah is professional keyboard-clacker, originally from the UK. Mark works on developer tooling and web infrastructure on the core web platform team at Yelp. When not coding or baking bread, Mark can typically be found roaming the grocery stores of San Francisco for new bars of Dark Chocolate 🍫

## Talk title and abstract (description)
The Joy of Express Middleware

Express middleware can be a powerful way to add logging, monitoring and performance insights into your application. In this talk, we'll walk through taking an Express application from "Hello World" to a fully logged service in a way that's practical, easily testable, and fun! We'll also go in-depth into how to expose the body of the response to get a complete view of the request, and briefly demonstrate using [Tweens](https://github.com/sharkcore/tweenz), a library to reduce some of this boilerplate.

## Twitter handle
[@mark_larah](https://twitter.com/mark_larah)

## Other social profiles or personal blog (optional)
https://blog.larah.me/

## Are you going to be live coding?
TBD, probably

## Do you need audio from your computer?
No

**Comment by paulgrock** [comment]
@magicmark would you like to present during our April 5th event?

**Comment by paulgrock** [comment]
Closing because of no response
