### ISSUE TITLE
PubNub Venue Request

### ISSUE THREAD

**Issue by JordanSchuetz** [sfnode/sfnode#58]
- 725 Folsom St, San Francisco, CA 94107, 1st floor, enter from street
- We will collect attendee list at the door (every attendee has to sign in)
- 100 people max (the meetup group can have more RSVP's though since half usually no show)
- If the meetup is going to have more than 50+ people, we will provide pizza and drinks. Veggie options yes! 
- We have microphone, huge screen, speakers, hdmi and display port connections, chairs and sofas
- We have headseat mic or regular mic
- Garage Parking, Street Parking, Limited Bike Parking inside.

**Comment by dietree** [comment]
Hi Jordan, I'm planning a <CODE> components meetup SF on August 13 and I'm looking for a location. Is this still available that day?

**Comment by JordanSchuetz** [comment]
Hi @dietree yes August 13th is available! Let me know if you want to reserve the spot. Email me schuetz@pubnub.com
