### ISSUE TITLE
Talk Proposal: Implementing a lightning fast route search engine in Typescript

### ISSUE THREAD

**Issue by tgalopin** [sfnode/sfnode#60]
*PS: I'm in San Francisco for 3 months (until 19th of May).*

# Full name and Bio

Titouan Galopin is a French software engineer and product lead at Symfony, the company behind the Symfony PHP framework (https://symfony.com). He likes PHP (Symfony) and JS/Typescript (React/Redux) and besides his work at Symfony, he works on several side projects including a mobile application for local public transports in the region of Oise in France.

https://twitter.com/titouangalopin

# Abstract

In the context of building a mobile app for public transport, I had to implement a route search engine for the region of Oise, France. It was a more complex journey than I expected and I'd like to give a glimpse on how I implemented the Connection Scan Algorithm in Typescript, heavily leveraging the async features of node.

Topics include:
* Basic route search algorithm and what data structures are used
* Implementation in Typescript using Node, Express and PostgreSQL
* An explanation of the different existing techniques to optimize the algorithm, making it the fastest route search algorithm on the market

# Link to slides

None for now, I'll do them if the subject seems interesting :) .

# Live coding

No

# Audio

No

**Comment by paulgrock** [comment]
@tgalopin would you like to present at our May 3rd event?

**Comment by tgalopin** [comment]
That would be awesome :) !

**Comment by paulgrock** [comment]
@tgalopin we don't have a second talk for our April event. Could you present at that one instead?

**Comment by tgalopin** [comment]
I have a colleague who wanted to see the presentation and is in San Francisco only in May. If you can have someone else in April it would be nice, but if you still really lack a second talk, I can do it, no problem :) .

**Comment by paulgrock** [comment]
ok, i've reached out to a few other folks. i'll let you know if we hear back. Thanks for being accommodating.

**Comment by tgalopin** [comment]
@paulgrock any news about this :) ? The colleague who's gonna join me in May is a quite renowned speaker and he coule propose a talk to replace mine if I'm in April :) .

**Comment by paulgrock** [comment]
We haven’t heard anything good back yet. If your colleague is interested please have them open an issue on here. We could have either of you speak next week. Whatever works better for you two.

**Comment by tgalopin** [comment]
Okay, let's plan me then :) . I'll tell him to propose a talk for may :) .

Thanks!

**Comment by paulgrock** [comment]
Awesome! Thanks so much! I’ll pencil you in for next week

**Comment by tgalopin** [comment]
I don't know if you want to publish it somewhere, but here are my slides :) : 

https://speakerdeck.com/tgalopin/implementing-a-lightning-fast-route-search-engine-in-typescript

**Comment by isurfbecause** [comment]
@tgalopin your presentation has been posted 
https://www.youtube.com/watch?v=Xy5w30TptlI
