### ISSUE TITLE
Talk Proposal: Objection.js - an easy, powerful and magic-averse ORM for Node.js

### ISSUE THREAD

**Issue by newhouse** [sfnode/sfnode#62]
NOTE: I'm really not sure if/when I'll have the time to do this, but I think it would be a good talk. So I'm throwing it up here to see if I can get motivated.

### Full name and Bio
Chris Newhouse
Backend-leaning full-stack developer with experience in ad-tech, sales-tech, mar-tech and finance. Can expand upon this later.

### Talk title and abstract (description)
Some of the more popular Node ORM's out there have added too much "magic" to them in the name of making things "easier" for novice developers or those looking for quick starts to getting things working.  These magic tricks pretty quickly start to look more like a curse (weird, automatic naming conventions involving pluralization oddities; unexpected behavior, etc) when your project starts getting more complex. As a moderate/competent SQL person, I want to be in control of my ORM...but I also want things to be easy when they should be, and even fun sometimes! Enter Objection.js. [Objection.js](http://vincit.github.io/objection.js) is an [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) for [Node.js](https://nodejs.org/) that aims to stay out of your way and make it as easy as possible to use the full power of SQL and the underlying database engine while keeping magic to a minimum. Objection.js is built on an SQL query builder called [knex](http://knexjs.org).

I don't know exactly what areas I'd cover would be just yet.

### Twitter handle
cwnewhouse

### Are you going to be live coding?
TBD. Probably a little.

### Do you need audio from your computer?
No.

**Comment by paulgrock** [comment]
@newhouse any chance you'd have this talk ready and be interested in speaking at next month's event on the 5th?

**Comment by newhouse** [comment]
Hey @paulgrock unfortunately not this time around. Some stuff's come up (both work and personal) and for right now I don't have the extra bandwidth to pull this together. I'll try to get settled back in in the next month or two and get it done. I'd still like to do it and that will be true until I close this issue.

**Comment by paulgrock** [comment]
No worries. Thanks for the update.
