### ISSUE TITLE
Talk Proposal: Fervor - my attempt to fix full stack development

### ISSUE THREAD

**Issue by parris** [sfnode/sfnode#63]
Hi gang, I'd like to give a talk on my open source project - https://github.com/fervorous/fervor

Full Name and Bio
----

Parris Khachi, Director of Web at Brigade, Formerly at Eventbrite (and a brief stint at Famous), Author of various npm packages (iz, fervor, dorsal). Was "myspace famous" in college because I was in ska-rockabilly band.

Talk title and abstract
----

Fervor - my attempt to fix full stack development

If you're anything like me, you have a projects directory on your computer with dozens of projects you've started an abandoned. Each one of them experiments with different architectures, and by the end of each of them you've only barely scratched the surface of the actual problem you were actually trying to solve. Meanwhile, at work we all feel like coding is slow and *yet* we want our layers of abstraction to work the right way. Fervor is my attempt speeding up the monotony of development, CRUD style endpoints should be free, react + universal rendering + good performance + a decent routing system should be free, and none of your data should belong to vendors. I wanted a no frills, no BS framework that just lets me get to the heart of side projects.

Twitter Handle
----

@parrissays

Coding Live
----

Probably a bit

Do you need audio from you computer
----

Nope

Which date
----

Hmmm, April or June could both work

**Comment by paulgrock** [comment]
@parris would you like to present in April?
