### ISSUE TITLE
Talk Proposal: Internal consulting without insulting? 

### ISSUE THREAD

**Issue by elhamrastkhadiv** [sfnode/sfnode#64]
# Name
Elham Rastkhadiv, Senior software dev at OpenTable

# Title
Internal consulting without insulting? How to be a consultant within your org.

# Abstract
Ever been in a team that needed improvement but didn’t know how to begin? Come and learn about how I use my consultancy skills to make positive changes. We will focus on building up skills in pair-programming, coding values, testing standards, knowledge sharing and on-boarding people to the codebases

# Twitter handle
rastkhadiv

# Do you need audio from your computer?
No.

**Comment by paulgrock** [comment]
@elhamrastkhadiv I know you're at OpenTable and I'm sure would prefer to present in May when we're going to be there but we're still looking for a second talk for next week's event. Let me know if you're interested.

**Comment by elhamrastkhadiv** [comment]
@paulgrock Hi sorry, I was on holiday, just saw your message. yes I do prefer the Openable one if possible.
Thanks

**Comment by paulgrock** [comment]
@elhamrastkhadiv we've got a spot open for the event in May so I'll put your name down for it
