### ISSUE TITLE
Talk Proposal: Let's Chat About Testing Chatbots

### ISSUE THREAD

**Issue by microsoftly** [sfnode/sfnode#65]
## Bio
* Matt Schwartz
* Backend Engineer for Restaurant Services at Open Table working in C# by day and node/typescript  by night.
## Abstract
Building chatbots for multiple platforms (Slack, Facebook Messenger, Skype, etc ...) is very easy with Microsoft's Botbuilder framework. With just a few lines of code and configuration, anyone can easily connect their bot to all of these platforms. What they cannot do is easily create and run autonomous tests. Putting their bots into a CICD pipeline was a pipedream (pun intended), until now.

In this talk, I will go over the basics of creating a chatbot and show the inspiration for the [BotTester framework](https://github.com/microsoftly/BotTester). Specifically, why the botbuilder SDK testing strategy was

1. Slow
2. Nearly impossible to scale
3. Limited in usefulness

and how the [BotTester framework](https://github.com/microsoftly/BotTester) addressed these concerns. Additionally, I will showcase the approach I took to make the package more consumable by the open source community (CircleCI, Coveralls, Google Hangouts, using Typescript/Typedocs).

## Computer Audio: ```not needed```

**Comment by paulgrock** [comment]
@microsoftly are you interested in presenting on April 5th?

**Comment by microsoftly** [comment]
@paulgrock would it be possible to do it in May at OpenTable (my employer 😇)?

**Comment by microsoftly** [comment]
Thanks!

@paulgrock about how long are the presentation slots?

**Comment by paulgrock** [comment]
Talks should be 20-30 min. Then there is usually some short Q&A right after the presentation.
