### ISSUE TITLE
Talk Proposal: I know what you want to eat.

### ISSUE THREAD

**Issue by greenteamuimui** [sfnode/sfnode#66]
# Name and Bio
Cherry Lam, Software Engineer at OpenTable with background in food, food and food (can further elaborate if needed)

# Title
I know what you want to eat!

# Abstract
What happens when you type “Italian food Downtown….” searching for the best restaurants to eat? How does the API figure out what you are looking for and give you the choices that are closest to you? The powerful search and indexing capabilities of ElasticSearch with Node's efficiency and ease of deployment allows the search engine to interpret the user’s intent and return the most relevant options. I will talk about the interesting logic and decisions behind indexing document, parsing and understanding user’s intent to narrowing down to the best matches in a consistent way. 

# Live Coding
Will go through some code

**Audio Not needed**

**Comment by paulgrock** [comment]
Hi @greenteamuimui I know it’s short notice but we’re short a speaker for next week’s event. Are you interested in speaking next Thursday?

**Comment by greenteamuimui** [comment]
Hi @paulgrock sorry already have plans on Thur.

**Comment by paulgrock** [comment]
ok, thanks :)

**Comment by greenteamuimui** [comment]
Hi @paulgrock, I wanted to let you know that I need to go home to attend my grandma's funeral and I won't be able to do this talk at Opentable on May 3th. Let me know if we can move mine to the next talk. Thanks.

**Comment by paulgrock** [comment]
@greenteamuimui I'm so sorry! Of course we can change this to another event. Does June 7th work for you?

**Comment by greenteamuimui** [comment]
@paulgrock Would it be possible to do the one in July? I have family visiting that day/weekend in June...sorry for the re-scheduling.

**Comment by paulgrock** [comment]
@greenteamuimui July would be perfectly fine. I'll mark you down for that month.

**Comment by greenteamuimui** [comment]
@paulgrock Hi Paul, just wanted to see if you have the date/venue for the talk in July?

**Comment by paulgrock** [comment]
The date is July 12th and we're going to be at AKQA.

**Comment by paulgrock** [comment]
thanks for presenting @greenteamuimui Loved the talk!
