### ISSUE TITLE
Talk Proposal: Smart Contracts and dApps for Web Developers

### ISSUE THREAD

**Issue by dmill** [sfnode/sfnode#67]
Hi Everyone,

I'm putting together [a course on Ethereum development](http://www.destinationdev.com/blockchain/) geared towards web developers without blockchain knowledge, and I have a talk I'm putting together going over the basics. I recently took a crash course myself with our instructor, so I know that the material is approachable but I also know that it's difficult figuring out where to start. A ton of the new tools are JS-centered, so I figured this would be a great place to give a talk like this. Anyone interested?

**Comment by Trewaters** [comment]
Are you still interested in speaking? If not we will close the issue in a few days.

**Comment by dmill** [comment]
Hey @Trewaters! I may still be able to do something on this, but my schedule is a bit hectic at the moment. I'll go ahead and close this for now and check back in with you when I have some more time.

**Comment by Trewaters** [comment]
That is totally fair. Thanks for closing this one.
I look forward to catching up in the future.
