### ISSUE TITLE
Talk Proposal: Lessons in building a distributed file storage system

### ISSUE THREAD

**Issue by dylankb** [sfnode/sfnode#69]
### Full name and bio: 

Dylan Barnard has wrangled sheep, fish, people, and now code as a software developer in Oakland, CA. He’s into long hikes and longer learning projects.

### Title:

Lessons in building a *decentralized* file storage system

(Note that this is the correct title, I used an incorrect word in the issue name)

### Abstract: 

Everyday we upload our data to companies who help us with our cloud file storage needs (AWS, Dropbox, Google, Apple, etc.), but what if we don’t trust these companies with our data? Is there another way besides using centralized cloud file storage services? I’d like to talk about what decentralized storage systems are and how they could help us protect our personal data, privacy, and maybe even our pocketbooks against some of the potential disadvantages of a centralized service. Two other developers and I built an experimental distributed file storage system called [Layr](https://github.com/layr-team/Layr), which I’ll use to talk about:

* Why we can rely on random, unreliable strangers to reliably store our private files for us
* The libraries and data structures to scale to huge numbers of peers on a network
* Using crypto-currencies to encourage participation and manage micro-transactions

Built with Node.js

### URL to slides:
[Link](https://docs.google.com/presentation/d/1hINOIyJ2oLpbmd6boQQg9gRQFhNi4qBCdmUuzQAzbEs/edit?usp=sharing)

### Live coding:  
No

### Audio:  
No

**Comment by paulgrock** [comment]
@dylankb we just talked about you presenting in July but I just wanted to make a note of it here so I don’t forget

**Comment by paulgrock** [comment]
thanks for speaking @dylankb Your talk was super informative!
