### ISSUE TITLE
Promises with Generics using TypeScript

### ISSUE THREAD

**Issue by brennanMKE** [sfnode/sfnode#7]
🕒 ~15 minutes (+ Q&A?)

### Talk Abstract

----

Promises become much easier to use in your code base when generics reveal the types which will sent when a promise is resolved. And once you have a lot of code it will be possible to refactor because you will be able to use the errors and warnings made possible with generics to identify where changes are needed. This talk will cover how generics can be used with promises using TypeScript as well as getting started with TypeScript including automating Grunt tasks integrated with VSCode.

In the past several months TypeScript has matured considerably along with VSCode to make for a great developer story. Utilities like `tsd` have been deprecated and replaced by `typings` to enable more helpful options to support developer's needs. This talk will cover the current state of TypeScript so you can make use of it right away.

### Speaker Bio

----

Brennan Stehling

Brennan is a software engineer with many years experience with JavaScript and recently with Node.js and TypeScript along with years with iOS. https://github.com/brennanMKE/

**Comment by paulgrock** [comment]
@brennanMKE are you available to give this talk for the August event on 8.4?
