### ISSUE TITLE
AKQA Venue Request

### ISSUE THREAD

**Issue by JoshyJAKQA** [sfnode/sfnode#70]
I hope all is well! I'm Josh Jacobs and I'm work over at AKQA. I work closely with the Tech team and have heard positive things about your meet-ups! I've already reached out to Paul and Dan to see if we can collaborate on something in the near future.

With that said, I wanted to reach out to see if you guys were ever open to hosting one here at our office. We have an amazing rooftop we can host at or cafe that can be rearranged to the team's standards.

If interested feel free to reach out and I would love to help you guys set something up either later this month or next.

Thanks again and look forward to hearing back.

Cheers,

Josh

**Comment by paulgrock** [comment]
Hey @JoshyJAKQA we'd definitely love to come to AKQA. We're looking for a host for our July event which is probably going to be the 12th of July. Are y'all open for that date? Could you provide answers to the following questions we ask all of our prospective hosts?

* What is the address, floor, room name if any, entrance instructions?
* Do we need to submit an attendee list for security purposes?
* What's the total number of people that space can hold?
* Will food and drinks will be provided? Are there vegetarian and gluten free options?
* What is the AV setup like?
* What is the microphone setup? Mic stand or headset mic?
* What is the parking situation like? Is bike parking available? Any off-street parking?

**Comment by JoshyJAKQA** [comment]
Thanks, @paulgrock! July 12th is looking good as of right now. What would the ideal flow of this event be? Would love to learn more on how it would be run, plus it's itinerary.

Please find your answers below: 

What is the address, floor, room name if any, entrance instructions?
**5th floor, 360 Third St
San Francisco, CA 94107, United States**

Do we need to submit an attendee list for security purposes?
**Yes, please.**

What's the total number of people that space can hold?
**65**

Will food and drinks will be provided? Are there vegetarian and gluten free options?
**We can provide food & drinks. If needed, we can provide both**

What is the AV setup like?
**We can customize to your needs**

What is the microphone setup? Mic stand or headset mic?
**we can have a mic stand or microphone to hold**

What is the parking situation like? Is bike parking available? Any off-street parking?
**Street parking is available outside the building**

**Comment by JoshyJAKQA** [comment]
@paulgrock just following up here to see what next steps would be for July

**Comment by paulgrock** [comment]
Sorry about that. We're good from our side with this information. We'll add AKQA to the meetup page https://www.meetup.com/sfnode/events/mxstsmyxkbhb/. The flow for the event is guests show up at 6:30 (organizers will show up at 6 or so unless needed earlier) talks start at 7 then everyone is out by 9. Does that help?

**Comment by JoshyJAKQA** [comment]
Sounds good, @paulgrock ! Can we move this conversation to email? It will be easier to manage on our end.

Josh.Jacobs@akqa.com

Thanks again and look forward to hearing back.

Cheers,

Josh
