### ISSUE TITLE
Talk Proposal: Microservices application delivery to cloud

### ISSUE THREAD

**Issue by rubenhak** [sfnode/sfnode#73]
**Full name and Bio**
Ruben Hakopian is a software engineer. Builds management software for cloud, networking hardware, video processing equipment, silicon wafer processing equipment. Worked in variety of companies: Cisco, Insieme Networks, Harmonic, Mattson Technology, etc. Now trying to build a company to significantly simplify back-end software development.

**Talk title and abstract (description)**
It used to be relatively easy to build initial versions of monolithic applications. Just put together a couple of service tiers and voilà! With a minimal configuration you would have things up and running.  The same approach doesn't work well anymore. Demand and expectations are much higher, which requires braking up the monoliths into microservices. But this process introduces another kind of complexity - how to properly configure cloud resources, run those microservices, let them communicate and monitor such a large number of services. What is much harder is to keep doing that over and over again as the product matures. 

Without getting into the disadvantages of today's solutions as a part of this talk proposal request, I would like to present a product that changes the way how services and cloud resources are defined, configured and deployed. 

I will clearly present the problem domain. Show alternative solution to how things are done today. And show a very quick live demo.

**Twitter handle (optional)**
[https://twitter.com/berlioz_cloud](https://twitter.com/berlioz_cloud)

**Other social profiles or personal blog (optional)**
[https://medium.com/@ruben.hakopian](https://medium.com/@ruben.hakopian)

**Url to slides or github (either now or can be posted in meetup comments later)**
[https://github.com/berlioz-the](https://github.com/berlioz-the)
[https://github.com/rubenhak](https://github.com/rubenhak)

**Are you going to be live coding?**
Will show live demo. Within couple of minutes will deploy a pretty complex microservices application to the cloud. Will show a but in the code, fix it live and deploy again. Should take about 10-15 minutes.

**Do you need audio from your computer?**
No.

**Availability**
As soon as possible.

**Comment by paulgrock** [comment]
@rubenhak are you interested in presenting at our event on 9.6?

**Comment by paulgrock** [comment]
@rubenhak we’re already full for August. I’ll pencil you in for September but if anything changes I’ll let you know

**Comment by rubenhak** [comment]
sounds good. thanks.
