### ISSUE TITLE
Helping with nametags for attendees

### ISSUE THREAD

**Issue by kevinsimper** [sfnode/sfnode#74]
Hi SFNode, 

I am going to the SFNode on the 12th July and want to help 😄 

I have made a really cool hack-project to print name-tag labels and have done it at several meetups. It is made with Node.js.

Can I help with nametags for that meetup?

![img_0985](https://user-images.githubusercontent.com/1126497/41824351-11b46ab8-780f-11e8-9c11-22740cdf44bf.JPG)

**Comment by kevinsimper** [comment]
Hi @paulgrock, can I help with name tags for the next meetup? 😄

**Comment by paulgrock** [comment]
Could you tell me how it works? Not necessarily the project but what we would need to do to make this happen. Do we print these off as attendees roll in or is it more something we’d do before hand?

**Comment by kevinsimper** [comment]
@paulgrock It makes most sense to have printed all of them before, it would take around 2-3 minute if a lot of people are coming through the door at the same time. I usually print as people come in to check the person is correct :)

**Comment by kevinsimper** [comment]
@paulgrock I just used it again today for my own meetup again and I even made it work wirelessly 😄 What do you think? Do you have more questions?

https://www.facebook.com/566056680150026/posts/1810173505738331/

**Comment by paulgrock** [comment]
Seems reasonable to me. I have two other questions: would you print our logo in the top left where you have the ruby gem in the image above and where does the QR code lead?

**Comment by kevinsimper** [comment]
@paulgrock I will add the SFNode logo, the template that I customize is located right here: https://rawgit.com/kevinsimper/meetuplabel/master/template.html
The QR code just goes to the meetup event page.
Glad you like it, looking forward to helping with it!

**Comment by paulgrock** [comment]
Perfect. What’s your email? I’ll send the list of attendees over the day before the event

**Comment by kevinsimper** [comment]
@paulgrock I already send you an email to that you have on your github profile 😄
