### ISSUE TITLE
Talk proposal: Forgot Password? Yes I did!

### ISSUE THREAD

**Issue by joellord** [sfnode/sfnode#75]
**Full name and Bio:**
Joel Lord
Joel Lord is passionate about web and technology in general.  He likes to learn new things but most of all, he likes to share his discoveries.  He does so by travelling at various conferences all across the globe.
He graduated from college in computer programming in the last millennium.  Apart for a little break to get his BSc in computational astrophysics, he was always in the industry.
As a technical evangelist with Auth0, he meets with developers to help them make the web a safer place.
During his free time, he is usually found stargazing in a camping site somewhere or brewing a fresh batch of beer in his garage.

**Talk title and abstract (description)**
Forgot Password? Yes I Did!
Every month, we hear about a new data breach and billions of user passwords are being shared as we speak.  How can we stop this?  There is a simple solution, let’s stop using passwords!  From email links to biometrics, more and more technologies are available to help developers handle different types of credentials.  During this presentation, the attendees will learn about some of the alternatives and how to implement them in the context of an OAuth flow.  

**Twitter handle (optional)**
@joel__lord

**Other social profiles or personal blog (optional)**
https://javascripteverything.com/

**Url to slides or github (either now or can be posted in meetup comments later)**
Will be posted later.

**Are you going to be live coding?**
I'll be showing code snippets but no live coding per say.

**Do you need audio from your computer?**
Nope

**Other notes**
This has to be for the August 2nd Meetup.  I have extended my stay until the 3rd so I could present but I won't be there next month ;)
Thank you for considering this talk!

**Comment by joellord** [comment]
No specific preference, I'm comfortable with all three.  I do like this one
too as it's my newest talk :)

Le dim. 8 juil. 2018 à 11:23, Paul Grock <notifications@github.com> a
écrit :

**Comment by paulgrock** [comment]
Great! Let’s do this one in August.

**Comment by joellord** [comment]
Awesome!  I've added it to my schedule!

Le dim. 8 juil. 2018 à 13:08, Paul Grock <notifications@github.com> a
écrit :

**Comment by paulgrock** [comment]
@joellord thanks for great talk!
