### ISSUE TITLE
Talk Proposal: I Don't Care About Security (And Neither Should You)

### ISSUE THREAD

**Issue by joellord** [sfnode/sfnode#76]
**Full name and Bio:**
Joel Lord
Joel Lord is passionate about web and technology in general.  He likes to learn new things but most of all, he likes to share his discoveries.  He does so by travelling at various conferences all across the globe.
He graduated from college in computer programming in the last millennium.  Apart for a little break to get his BSc in computational astrophysics, he was always in the industry.
As a technical evangelist with Auth0, he meets with developers to help them make the web a safer place.
During his free time, he is usually found stargazing in a camping site somewhere or brewing a fresh batch of beer in his garage.

**Talk title and abstract (description)**
I Don't Care About Security (And Neither Should You)
Remember when setting up an auth system was easy? Me neither. From the signup form, the login form, password reset form, and all the validation in between it can easily take weeks if not months to get something basic up and running. Then you have to deal with all the security considerations. No thanks. During this presentation, the attendees will be introduced to OpenID and OAuth.  They will learn how to leverage these technologies to create secure applications, but most importantly, they will learn why and how to delegate authorization and authentication so they can focus on their real work and forget about all that security stuff.

**Twitter handle (optional)**
@joel__lord

**Other social profiles or personal blog (optional)**
https://javascripteverything.com/

**Url to slides or github (either now or can be posted in meetup comments later)**
Will be posted later.

**Are you going to be live coding?**
I'll be showing code snippets but no live coding per say.

**Do you need audio from your computer?**
Nope

**Other notes**
This has to be for the August 2nd Meetup.  I have extended my stay until the 3rd so I could present but I won't be there next month ;)
Thank you for considering this talk!

**Comment by paulgrock** [comment]
closing in favor of #75
