### ISSUE TITLE
Talk Proposal: WTH is a JWT (And It's Not Called A 'jot')

### ISSUE THREAD

**Issue by joellord** [sfnode/sfnode#77]
**Full name and Bio:**
Joel Lord
Joel Lord is passionate about web and technology in general. He likes to learn new things but most of all, he likes to share his discoveries. He does so by travelling at various conferences all across the globe.
He graduated from college in computer programming in the last millennium. Apart for a little break to get his BSc in computational astrophysics, he was always in the industry.
As a technical evangelist with Auth0, he meets with developers to help them make the web a safer place.
During his free time, he is usually found stargazing in a camping site somewhere or brewing a fresh batch of beer in his garage.

**Talk title and abstract (description)**
WTH is a JWT (And It's Not Called A 'jot')
Chances are sooner or later your shiny new single page application will need authentication.  Add some security and resource access control to that list as well.  But how can we integrate all of this into  a single page application that is entirely public?  How can we ensure that our users only have access to the resources they are authorized to by hacking way in via the console?  In this talk, the attendees will learn about l JSON Web Tokens (JWT) and see how they can be used to properly secure single page applications.

**Twitter handle (optional)**
@joel__lord

**Other social profiles or personal blog (optional)**
https://javascripteverything.com/

**Url to slides or github (either now or can be posted in meetup comments later)**
Will be posted later.

**Are you going to be live coding?**
I'll be showing code snippets but no live coding per say.

**Do you need audio from your computer?**
Nope

**Other notes**
This has to be for the August 2nd Meetup. I have extended my stay until the 3rd so I could present but I won't be there next month ;)
Thank you for considering this talk!

**Comment by paulgrock** [comment]
closing in favor of #75
