### ISSUE TITLE
Talk Proposal: JavaScript Event Loop and the Web vs Node.js nuances that you must know

### ISSUE THREAD

**Issue by derekstavis** [sfnode/sfnode#78]
**Full name and Bio**
Derek Stavis

Derek Stavis has been hacking and building software since 2000's, having participated in technology choices, design, architecture and implementation in a myriad of projects, ranging from embedded systems, realtime backends and web apps. His excitement is to develop elegant software solutions for real world problems.

**Talk title and abstract (description)**
JavaScript Event Loop and the Web vs Node.js nuances that you must know

Have you ever heard or read that Node.js has an event loop? That applications on the browser and Node.js are event-oriented? Have you ever wondered how the event loop works with the JavaScript runtime? What are the event loop differences on the web and node? Let's answer all this questions on this talk which will explore the JavaScript runtime and explain everything you must know about the event loop and the nuances between browser and Node.js.

**Twitter handle (optional)**
@derekstavis

**(Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by paulgrock** [comment]
@derekstavis Would you like to present at the September 6th event?

**Comment by derekstavis** [comment]
Yeah! It works for me!
