### ISSUE TITLE
Talk Proposal: Scalable Command Line Interfaces 

### ISSUE THREAD

**Issue by ev1stensberg** [sfnode/sfnode#79]
# Full name and Bio:
Even Stensberg is an OSS entusiast and student

Even is an Information Technology student based in Tromsoe. He is one of many maintainers of webpack and enjoys Open Source quite a lot.

# Talk title and abstract (description)

### Description
Libraries are often hard to get "just right" at first. It takes work to be able to use the tool without getting stuck. This talk will go through how to craft Command Line Interfaces that are scalable and easy to use in order to onboard new users. 

By combining 0CJS techniques, scaling the complexity of the tool and thinking about Developer Experience, one is able to make advanced tools that are easy for beginners as well as experienced developers to make sense of.

# Twitter handle (optional)
[@ev1stensberg](https://twitter.com/ev1stensberg)
# Other social profiles or personal blog (optional)
n/a
# Url to slides or github 
Posted later
# Are you going to be live coding?
No
# Do you need audio from your computer?
No
# Other notes

I'm coming to the Bay in October so this talk would be best to have in October! This talk is a variation of the talk I had at JSHeroes earlier this year.

**Comment by paulgrock** [comment]
@ev1stensberg our October event is on the 4th, does that work for timeframe?

**Comment by ev1stensberg** [comment]
Might be. I'm coming for Google Mentor Summit. Can I get back to you once they release dates?

**Comment by paulgrock** [comment]
Sure thing

**Comment by ev1stensberg** [comment]
Is this announced @paulgrock ? I might need to update my bio

**Comment by paulgrock** [comment]
No it’s not announced yet. Let me know what you want to update your bio to and I’ll change it

**Comment by ev1stensberg** [comment]
Even Stensberg is an OSS entusiast, Software Developer at Telia Sonera and Computer Science at the Artic University of Norway, based in Tromsoe, Norway.  He is one of many maintainers of webpack and enjoys it quite a lot!
