### ISSUE TITLE
Making tectonic shifts through node

### ISSUE THREAD

**Issue by ev1stensberg** [sfnode/sfnode#8]
# Making tectonic shifts through node
⚠️ Abstract

Starting programming in JS is always a hard thing for a beginner. What framework am I going to use? What tools do I need for it to work? How do these tools work? These are some of the questions I've asked myself a lot when starting programming in JavaScript. And it may not come as a shock, that this is highly relative to NPM and NodeJS. This talk will go through the pitfalls beginners make and how those pitfalls make a difference when learning modern JavaScript. 

During the talk, Evan will show how you can help beginners approach ES6 and node, as well as he will show some common patterns for beginners and how those could be improved through the open-source community. Lastly, he will show how learning ES6 is actually learning the tools you use.

♻️  Bio

## Even Stensberg

Evan is a Front-End developer from Norway. He is interested in React, Redux and making things in JavaScript. Currently Even works at Dossier Solutions in Oslo. He started programming in 6th grade and quickly got inspired to continue to make abstract thoughts into writable programs.

**Comment by ev1stensberg** [comment]
This won't be as boring as it sounds, I promise <3

**Comment by paulgrock** [comment]
@ev1stensberg this talk doesn't sound boring at all. Are you cool with doing this talk for the August 4th event?

**Comment by ev1stensberg** [comment]
@paulgrock Definitely! I'll actually be arriving to SF the day before so it fits well for my schedule. Anywhere I could get some practical information about location and such?

**Comment by paulgrock** [comment]
That's great! I'll add your talk details to the meetups page. 

We haven't announced the location yet but it's likely going to be at Earnest which is located at 1455 Market St. 18th Floor.

**Comment by ev1stensberg** [comment]
Cool. I'll assume the time is there as well? ( at meetup.com/...)

**Comment by paulgrock** [comment]
Doors open at 6:30 first talk will be at 7. Doors close around 9. That's the general schedule. http://www.meetup.com/sfnode/events/224882986/ is the link to the event.

**Comment by ev1stensberg** [comment]
Thanks! See you there @paulgrock 💯
