### ISSUE TITLE
Talk proposal: Scaling DevOps - how to solve a puzzle of thousands of pieces

### ISSUE THREAD

**Issue by dietree** [sfnode/sfnode#80]
**Full name and Bio**
Shimon Tolts

Shimon is the CTO and Co-Founder at datree.io, a platform that solves DevOps scaling for you. It’s a simple, seamless, and a fully automated solution that will help you effortlessly map, smoothly navigate using actionable insights and successfully scale your DevOps organization.
Shimon also spearheads the Israeli AWS User Group and he is a regular speaker on the Big Data, DevOps and Serverless tech circuits, giving talks around the world at conferences like AWS Summits, Serverless-days and Devcon.

**Talk title and abstract (description)**
Scaling DevOps: how to solve a puzzle of thousands of pieces

Multiple cross-functional teams, gems, pip’s, npm’s, docker’s, ci/cd pipelines and hundreds of git repositories generate a chaotic and difficult environment to coordinate.
This session is about real life best practices that will help you map and navigate your development environment in order to successfully scale your DevOps organization.
You will learn:

- How to manage hundreds of Git repositories
- How to maintain thousands of packages
- How to easily encourage developers following company’s best practices

**Twitter handle (optional)**
@shimontolts

**Url to slides or github (either now or can be posted in meetup comments later)**
Will be posted later.

**(Are you going to be live coding?**
Yes

**Do you need audio from your computer?**
No

**Other notes**
In San Francisco from July 31 to August 14. It would be great to fit the talk into the August 2 Meetup if it's possible. If not, let's talk for future Meetups.

**Comment by Trewaters** [comment]
Hi Shimon, sorry we missed your time frame. We are behind on fallowing up with speakers. Maybe next time you are in the SF bay area you will reach out to us. I did enjoy meeting you last summer at MixMax. 

Good luck with the datatree.io project!

**Comment by Trewaters** [comment]
I suggest we close this issue for now and you could resubmit it when you are available again.
