### ISSUE TITLE
Talk proposal: Progressive Web Apps - the what, why and how.

### ISSUE THREAD

**Issue by shrutikapoor08** [sfnode/sfnode#81]
**Full name and bio**
Shruti Kapoor
I am a Software Engineer at PayPal. I like JavaScript. I like devjokes. 

**Description**
Progressive web applications enable key features such as instant download, offline viewing, responsive navigation and push notifications, thereby bridging the gap between mobile and web experiences. In this talk, I talk about what makes progressive web apps so popular and how to develop one.

**Twitter handle:**
@shrutikapoor08

**Blog**:
https://medium.com/@shruti.kapoor08

**Are you going to be live coding?**
No

**Do you need audio from your computer?**
No

**Comment by paulgrock** [comment]
hi @shrutikapoor08 are you available to speak on November 1st at our next event?

**Comment by paulgrock** [comment]
Hey @shrutikapoor08 are you still interested in giving this talk?
