### ISSUE TITLE
Session Proposal: Deep Learning in Your Browser with NodeJS

### ISSUE THREAD

**Issue by ocampesato** [sfnode/sfnode#84]
Session Description: 
This is a fast-paced introduction to Deep Learning concepts, followed by a quick tour of TensorFlow concepts, and then an example of a CNN in tensorflow.js, along with a code sample in NodeJS. Basic knowledge of vectors, matrices, and derivatives is helpful for this session. Basic knowledge of vectors, matrices, and derivatives is helpful in order to derive the maximum benefit from this session.

General biography:
Oswald is a former PhD Candidate (ABD) in Mathematics, an education addict with multiple graduate degrees, and an author of 20 technical books. He has worked for Oracle, AAA, and Just Systems of Japan, along with various startups. He has lived/worked in 5 countries on three continents, and in a previous career he worked in South America, Italy, and the French Riviera, and has traveled to 70 countries on six continents. He has worked from C/C++/Java developer to CTO, comfortable in 4 languages, and wants to become fluent in Japanese. He has presented Deep Learning sessions at conferences, Google LaunchPad, and BA meetups to more than 1,200 people, and he is currently is an instructor for Deep Learning and TensorFlow as well as Machine Learning at UCSC (Santa Clara extension), and a consultant who provides training primarily in Deep Learning, TensorFlow, and Android.

Other comments:
1) no live coding (some simple demos) and no audio required
2) November or December timeframe (let's coordinate)
3) slide deck will be posted on Slideshare after presentation
4) session duration (estimate): 1 hour and 15 minutes

**Comment by ocampesato** [comment]
I noticed that the next available "first Thursday of the month" slot is 12/06/2018, which works for me.
However, if other dates around mid-November are available, please let me know ... thanks!

**Comment by paulgrock** [comment]
hey @ocampesato we don't have a mid November date open but are you still available for the 12.6 event?

**Comment by paulgrock** [comment]
@ocampesato are you still cool with 12.6 for this talk?

**Comment by paulgrock** [comment]
@ocampesato I know it’s been a while but would you still like to give this talk?

**Comment by Trewaters** [comment]
I am closing this due to lack of contact. If you are interested in speaking please open another issue. Sorry we didn't get you on the schedule. 

I think the audience would be interested in your topic.
