### ISSUE TITLE
Microsoft Reactor Venue

### ISSUE THREAD

**Issue by nebrius** [sfnode/sfnode#85]
Hi SFNode, due to shifts at Microsoft I'm now available to host SFNode again!

_What is the address, floor, room name if any, entrance instructions?_

680 Folsom St, Ste 145, San Francisco, CA. The entrance to our office is on the ground floor in the main lobby for the building. No notable entrance instructions, we'll manage it for you

_Do we need to submit an attendee list for security purposes?_

No

_What's the total number of people that space can hold?_

This one is a bit tricky to answer, but realistically we can hold up to about 80 folks, even if the space can technically hold a lot more.

_Will food and drinks will be provided? Are there vegetarian and gluten free options?_

Yes and yes.

_What is the AV setup like?_

It's pretty advanced. Multiple inputs and outputs that can be rerouted from a central control panel

_What is the microphone setup? Mic stand or headset mic?_

We have both handheld and lavaliere mics.

_What is the parking situation like? Is bike parking available? Any off-street parking?_

I'll need to follow up on bike parking, as I'm not sure what's available. There is plenty of parking in a parking garage right next to our building.

**Comment by nebrius** [comment]
Just to update on scheduling, I couldn't make scheduling logistics work for the December 6th meetup, but I can make January 3rd and February 7th work. Let me know which you'd like!

**Comment by Trewaters** [comment]
Hi Bryan, 

I want to confirm that SFNode is looking forward to Microsoft hosting us January 3rd. Please let me know if that is still available. Thanks

Tre,

**Comment by nebrius** [comment]
Yes, the MS Reactor is still available and has been officially booked for SFNode on January 3rd. Looking forward to it!

**Comment by paulgrock** [comment]
@nebrius do you or someone else at MS want to speak at the Jan event?

**Comment by nebrius** [comment]
@paulgrock I'm always down to speak, yes! Do any of these three talks sound fitting?

https://nebri.us/talk/nodeconf-eu-2018-effective-documentation-for-open-source-projects.html
https://nebri.us/talk/view-source-conference-2018-johnny-five-and-the-rise-of-javascript-hardware.html
https://nebri.us/talk/silicon-valley-code-camp-2018-understanding-functions-and-this-in-the-world-of-es2018.html

I can also come up with something else if none of these appeal to you (I've been kicking around an idea on Serverless)

**Comment by paulgrock** [comment]
personally I'd lean towards the one on documentation but both sound cool

**Comment by nebrius** [comment]
Great, let's do the documentation talk then :)
