### ISSUE TITLE
Talk Proposal: Debugging Node Services in Kubernetes With Linkerd 2.0

### ISSUE THREAD

**Issue by grampelberg** [sfnode/sfnode#86]
## Debugging Node Services in Kubernetes With Linkerd 2.0

Node services are increasingly deployed by service owners in a Kubernetes cluster. While Kubernetes can automatically keep your service up in the event of node failure or a software crash, it doesn’t provide visibility into how your service is behaving.

In this talk, we will walk through how to monitor your service on Kubernetes and troubleshoot some common issues. This will be a live demo and no previous Kubernetes experience is required.

## About Me

> Thomas Rampelberg | @grampelberg

Thomas Rampelberg is a Software Engineer at Buoyant Inc. He has made a career of building infrastructure software that allows developers and operators to focus on what is important to them.

**Comment by paulgrock** [comment]
Great! We’ll get you on the list.

**Comment by paulgrock** [comment]
I just added you to the meetup page https://www.meetup.com/sfnode/events/mxstsmyxpbcb/ Looking forward to your presentation!
