### ISSUE TITLE
Talk proposal: Build a task app with Hapi, MongoDB and Vue.js

### ISSUE THREAD

**Issue by connor11528** [sfnode/sfnode#87]
# Build a task app with Hapi, MongoDB and Vue.js

This talk goes through setting up an application from scratch using a Hapi v17 server, MongoDB with Mongoose ORM and a separate Vue.js frontend. We'll include transition and fade animations with Vue.js as well as handling asynchronous calls on the frontend with Axios.

Full tutorial and source code available [here](https://medium.com/employbl/build-a-task-app-with-hapi-mongodb-and-vue-js-dc05c1bb8778).

# About me

> Connor Leech | @connor11528

Connor is a Software Engineer at [Stitch Labs](https://www.stitchlabs.com/) where he works with Node.js and PHP. He likes paddleboarding, spending time with his family and working on his side project [Employbl.com](https://employbl.com/).

**Comment by paulgrock** [comment]
@connor11528 would you like to speak at our February event on the 7th?

**Comment by connor11528** [comment]
Hey @paulgrock yes I'd be happy to

**Comment by Trewaters** [comment]
See you tonight. If you have questions you can reach us through the meetup comments, or if you have any of the organizer's contact info.

**Comment by connor11528** [comment]
Thanks for the opportunity, it was a lot of fun

Slides (with links to source code): https://docs.google.com/presentation/d/1H9iD760JedijtnCACqSVyebYD36Vf5XFga7aALZnY0U/edit?usp=sharing

![]( https://media3.giphy.com/media/t64o8WukSJwqY/giphy.gif?cid=3640f6095c5de28d4e33754e6346e491)
