### ISSUE TITLE
Talk Proposal: A Response To "Design Flaws In Node"

### ISSUE THREAD

**Issue by Trott** [sfnode/sfnode#89]
* Full name and Bio

Rich Trott

Rich is a Node.js Core Contributor and all-around swell human being. He creates software, rock operas, and pizzas. He is a member of the Node.js Technical Steering Committee and works for the University of California.

* Talk title and abstract (description)

Title: A Response To "Design Flaws in Node"

Abstract: A non-inflammatory (I promise!) review and response to an event that prompted headlines like "Node.js Creator Blasts Node.js".

* Twitter handle (optional)

@Trott

* Other social profiles or personal blog (optional)

https://medium.com/@Trott

* Do you need audio from your computer?

No.

* Are you going to be live coding?

Hell no.

**Comment by paulgrock** [comment]
Are you interested/available to give this talk at the January event on 1.3?
