### ISSUE TITLE
Open Source S3 Clone in Node

### ISSUE THREAD

**Issue by LaurenSpiegel** [sfnode/sfnode#9]
We just built an S3 clone using Node and open sourced it!  The talk will cover:
- How Node enhanced the development process
- Problems encountered (e.g. ES6 compatibility) and solutions
- How developers can use the server to develop apps that are S3 compatible
- Demo

Speakers: Lauren Spiegel and Giorgio Regni

Lauren is a node developer working on the Scality team.  She over-thinks everything she does especially when writing about herself in the third person.  Twitter is @notfollowingyet

Giorgio is CTO and co-founder of Scality, likes mangling the English language and has been contributing to open source projects since before the debut of the Atari ST.  Twitter is @giorgioregni

[S3 Server](https://s3.scality.com/)

[GitHub Repo](https://github.com/scality/S3)

[Docker Hub Image](https://hub.docker.com/r/scality/s3server/)

![S3 Server logo](https://dl.dropboxusercontent.com/u/15463127/S3Server/Scality-S3-Server-Logo-Large.png)
![-](http://bit.ly/DHSHIM)

**Comment by paulgrock** [comment]
@LaurenSpiegel are you available to give this talk in September? Our event is on the first of the month.

**Comment by LaurenSpiegel** [comment]
@paulgrock Yes, sounds good!

**Comment by paulgrock** [comment]
@LaurenSpiegel awesome. I'll add your talk details to the event page

**Comment by GiorgioRegni** [comment]
Excellent @paulgrock , looking forward to it!

**Comment by paulgrock** [comment]
Great talk last night, @LaurenSpiegel and @GiorgioRegni! Thanks for presenting. Would you post a link to your slides on here when you have the opportunity?

**Comment by LaurenSpiegel** [comment]
@paulgrock, sorry for the delay.  Here are the slides: http://www.slideshare.net/Scality/scality-s3-server-node-js-meetup-presentation

Thanks again for hosting us!
