### ISSUE TITLE
Talk Proposal: Building a Hybrid Node + Browser App in Electron

### ISSUE THREAD

**Issue by burtonator** [sfnode/sfnode#90]
Polar is an offline browser and document annotation / management system based on Electron:

http://getpolarized.io/

It's about 50% node and 50% web in terms of tech split.

I'd like to discuss the Node part of the equation and integrating it tightly with the chrome portion.

For example, many web libraries require https to function correctly (cookies, etc) which poses a problem for Electron apps.

Another example is the potential use of GRPC to build a service mesh between browser windows instead of using the Electron IPC mechanism (which is slower).

**Comment by Trewaters** [comment]
Hi @burtonator would you still be interested in giving this talk?

**Comment by burtonator** [comment]
Yes. Would love too. Any thoughts on a date?

**Comment by Trewaters** [comment]
Next available spot would be possibly March 7th or April 4th. Do either of those work for your schedule?

@paulgrock

**Comment by Trewaters** [comment]
As you can see in the issue tracker we have a few submissions. I want to make sure we get your talk confirmed if you are still interested. It looks like May 2nd or later is available.

**Comment by Trewaters** [comment]
@burtonator May has filled up. Next available spot is July 11, 2019. If that works for you and you are still available to talk please let me know. 
Thanks!

**Comment by Trewaters** [comment]
Hi @burtonator 
We are looking to make our final list of speakers for July 2019. Please let me know in 24 hours if you are available to speak July 11th. I don't want to miss you but we are in a little bit of a time crunch.

Thanks!

**Comment by burtonator** [comment]
@Trewaters July 11 would work great... looking forward to it.

I'm also thinking about doing a meetup myself and would love to ask you a few question.

burtonator+git@gmail.com

or we can just discuss on the 11th.

**Comment by Trewaters** [comment]
@burtonator we had someone move their talk. Now we have an opening for June 6th. Would you mind moving your talk to June instead of July?

We could definitely talk about meetups. I will reach out.

**Comment by Trewaters** [comment]
Oops. forget that! I messed up. We do need you July 11th! 

I must need more coffee!!! Sorry for any confusion. I will update this issue to reserve the July 11th spot.

**Comment by burtonator** [comment]
ok... July 11... works for me.

**Comment by Trewaters** [comment]
Thank you!

**Comment by Trewaters** [comment]
Hi Kevin,

I am running behind on this but could you fill this out so I could update the description. For now I will put a placeholder until you complete this. Sorry for the last minute notification. I only noticed this morning that we were missing these details.

- Full name and Bio
- Talk title and abstract (description)
- Make sure talk is true to the title and abstract
- Twitter handle (optional)
- Other social profiles or personal blog (optional)
- Url to slides or github (either now or can be posted in meetup comments later)
- Are you going to be live coding?
- Do you need audio from your computer?
- See past proposals for examples

**Comment by burtonator** [comment]
> Full name and Bio

Kevin Burton, CEO/Founder - Polar

> Talk title and abstract (description)

Title: Building a Hybrid Node + Browser App in Electron

Abstract: 

Polar is a personal knowledge repository for capturing web content, 
PDFs and annotating them using the web and Electron as a backend.

Polar is designed to run within Electron and the web and we have 
both local and web backends.

Electron itself is based on Node + Chromium and we discuss some of the 
challenges we faced when building Polar for both the desktop and the 
web. 

> Make sure talk is true to the title and abstract
> Twitter handle (optional)

https://twitter.com/getpolarized

> Other social profiles or personal blog (optional)

https://getpolarized.io
https://www.inputneuron.io/

> Url to slides or github (either now or can be posted in meetup comments later)

I'll get it to you soon.  I want to make a few changes to it.

> Are you going to be live coding?

No way. :)

> Do you need audio from your computer?
> See past proposals for examples

**Comment by burtonator** [comment]
BTW.;.. how many minutes should I budget to talk for?

**Comment by Trewaters** [comment]
Less than 30 minutes. You will have to set up your laptops in that time too.  I would suggest targeting 20 minutes.
