### ISSUE TITLE
Talk proposal: Impress Friends w/ NBA stats you parse from an Excel spreadsheet in Node.js

### ISSUE THREAD

**Issue by elizabethsiegle** [sfnode/sfnode#91]
I'm a big Warriors fan and have been following their season with my brother and some of his friends. Unfortunately, sometimes they try to make me prove that I'm a real fan by asking for obscure trivia or stats. Luckily for me (and other programmers), we can write some Node.js code to stealthily check a parsed spreadsheet of basketball data without others knowing what we're doing.

This talk will go over how to use the XLSX node module to 

1. read a file
2. read a specific cell
3. add a new worksheet
4. write to a workbook
5. parse a spreadsheet of any type of data
6. and more!

**Comment by Trewaters** [comment]
Hi @elizabethsiegle would you still be interested in giving this talk?

**Comment by Trewaters** [comment]
Are you still available to speak? If so please comment below. 

Thanks!

**Comment by Trewaters** [comment]
Hi @elizabethsiegle are you still available to talk?

**Comment by Trewaters** [comment]
We haven't talked in so long I am going to close this issue. If you would like to submit this or another talk you are always welcome to.
