### ISSUE TITLE
Talk Proposal: Typescript with Node

### ISSUE THREAD

**Issue by andkhong** [sfnode/sfnode#93]
How to set-up and roll out typescript in production with Webpack.

Javascript at scale is impossible without a sort of type checking system. If the backend gets enough errors, it can shut down and all the users will lose access to your app. This can effectively kill the company overnight. Because Javascript is a dynamic language, it allows for many mistakes that even the most seasoned engineers can miss. Typescript helps remedies the problem by providing a wealth of type checking resources. When the app gets bundled, all type checking code gets stripped and the code gets transpiled to Javascript.

Andy is currently a Senior Full Stack Engineer over at Vida Health. His primary role is to roll out and maintain a GraphQL system for the front-end and mobile teams. Other responsibilities comprise of optimizing and improving the React app.

His previous work also included being a pivotal engineer at Bee Nest Inc. where he lead the development for the Vacation Rental app. He pioneered many core features such as Authentication/Authorization, Crypto + USD payment processing, analytics tracking, internal admin panel, GraphQL services, and etc.

On his free time, he likes to engage in the exploration with his two pups. One of which is an instagram star.

https://www.instagram.com/littlecooperbear/?hl=en

**Comment by andkhong** [comment]
hmm if there isn't an interest in this talk, i can remove it?

**Comment by paulgrock** [comment]
Hey @andkhong we're definitely interested in having you speak at an upcoming event. Apologies for not responding quicker. We're still trying to figure out which month would be the best fit. If you're no longer interested in presenting feel free to close this.

**Comment by Trewaters** [comment]
@andkhong We would like to schedule this talk for a future meetup. Would you still be interested in giving this talk? If so comment and I will work with you to get a date in the books.

Thanks for your patience!

**Comment by andkhong** [comment]
I'm still interested. Are there common concerns/questions regarding TS and node?

**Comment by Trewaters** [comment]
Glad to hear it. Our next open speaking date is April 4th. Does that sound like it would fit on your schedule?

**Comment by andkhong** [comment]
I believe April 4th sounds like a solid date for me.

**Comment by Trewaters** [comment]
Hi @paulgrock if this looks like it would fit could you lock it in for April? Thanks for making all these updates. I appreciate it.

**Comment by Trewaters** [comment]
@andkhong I am going to schedule you for our April 4th meetup. Please give me a final confirmation that this will work for you. I want to make sure we are on the same page.

@paulgrock please label this talk for April.

**Comment by Trewaters** [comment]
Hi @andkhong wanted to check with you about speaking May.

Please post if you are still available to talk. I want to make sure my notes are updated correctly. Thanks :)

**Comment by Trewaters** [comment]
Hi @andkhong 

Checking on your submission. Did you still want to talk?

**Comment by andkhong** [comment]
Sure, I am still interested in speaking. Lost update on this so it slipped my mind.

**Comment by Trewaters** [comment]
Awesome! We are at MixMax June 6th. Doors open at 6 and close at 9pm.

Can I put you on that schedule, or is another month better?

**Comment by andkhong** [comment]
Sure, that sounds great! Ill prepare and submit slides the the talk format if that works?

**Comment by Trewaters** [comment]
You get 30 minutes to setup computer and talk. I know MixMax has a projector so you would be able to show slides. Besides that I think the format is pretty free style. I like seeing code but do what works best for your topic.

send me any questions you have.

**Comment by Trewaters** [comment]
Are you ready for tomorrow? I am here for questions. 

Please post a comment to confirm you are on for tomorrow.

We are meeting at Mixmax (512 2nd St, San Francisco, on the first floor). Doors open at 6:30 pm. There will be pizza and soda provided by the venue.

**Comment by andkhong** [comment]
I have the code ready, still working on the slides! Currently putting fires out. Will update finalize the slides by tomorrow morning!

https://docs.google.com/presentation/d/1Dz-y_L9Uien39ZmSbxFPMxtSx7DHIAnwm6G6uUeOK1A/edit

**Comment by Trewaters** [comment]
Thanks for confirming. I understand being busy. Good luck!

I am posting on Twitter do you have a Twitter account you would like me to share?

**Comment by andkhong** [comment]
Unfortunately I do not have a Twitter account. My corgi does have an instagram account

Instagram:
https://www.instagram.com/littlecooperbear/?hl=en

Twitch:
https://www.twitch.tv/adkhermit

**Comment by andkhong** [comment]
https://github.com/andkhong/webpack-typescript-node

here's a repo that's not too different from the code i'll be demoing tomorrow
