### ISSUE TITLE
Talk Proposal: BAM! -- A Serverless Framework

### ISSUE THREAD

**Issue by jociemoore** [sfnode/sfnode#96]
**BAM! -- A Serverless Framework**

Working with Amazon Web Services directly can be burdensome. As a result, a variety of frameworks have been created to abstract away its complexity, but still, these frameworks tend to be either as unwieldy as AWS itself or lacking in functionality. The BAM! framework, on the other hand, is made for humans; it’s quick, easy to use, and allows you to stay focused on your code. 

Come learn about the current landscape of serverless technologies, the difficulties of interacting with the Amazon cloud, and how the BAM! framework improves this interaction. More specifically, come see how BAM! enables you to deploy an AWS Lambda and Amazon API Gateway with one command. 💥

**Jocie Moore**
www.jociemoore.com
@iamjociemoore

Jocie Moore is one of co-creators of the BAM! framework and a software engineer who cares about thoughtful development of the products she works on. Before BAM!, she worked at Dealer.com where she first started using Amazon Web Services. She enjoys learning about the history of computer science and believes in the power of technology to solve some of the biggest problems facing our world today.  

**Logistics**
* View presentation slides [here](https://docs.google.com/presentation/d/e/2PACX-1vTh6ppRBBaJs8VsYk4xr8IRDkzip-pP5K8FYBXeF1Gnv6cXo1EJDYHx8C1YY_6BE49_djNPXbmah77i/pub?start=false&loop=false&delayms=3000#slide=id.g498632f1f0_1_12)
* Are you going to be live coding? No
* Do you need audio from your computer? No

**Comment by jociemoore** [comment]
Hi Tre',
Thanks for reaching out. Yes, that would work. Let me know if there is an available speaking spot in April, but if not, May would work too.

**Comment by Trewaters** [comment]
@jociemoore 
After reviewing our calendar it looks like May 2nd is available. Can I put you on the calendar for that day? Comment below to confirm you are okay with that.

**Comment by jociemoore** [comment]
Yes, that would be great!

**Comment by Trewaters** [comment]
Speaker won't be able to talk May. I welcome Jocie to open issues in the future.
