### ISSUE TITLE
Talk Proposal: Real World Attacks in the npm Ecosystem

### ISSUE THREAD

**Issue by tlhunter** [sfnode/sfnode#97]
**Real World Attacks in the npm Ecosystem**: In this talk we will examine some practical attacks against the npm package ecosystem. We will look at both theoretical attacks as well as attacks which have already happened.

The most recently publicized attack we’ll look at is the `event-stream` module. This will include a breakdown of functionality, why it was difficult to find, and why a static analysis tool will not protect from such an attack. We’ll also look at some other intentionally malicious modules like `getcookies` which have also been published.

We’ll also look at some theoretical attacks and incorporate research done by @ChALkeR and npm.

Content is based on these two posts of mine:
[The Dangers of Malicious Modules](https://medium.com/intrinsic/common-node-js-attack-vectors-the-dangers-of-malicious-modules-863ae949e7e8)
[Compromised npm Package: event-stream](https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502)

Talk will cite some research done by ChALkeR and npm:
https://github.com/ChALkeR/notes/blob/master/Gathering-weak-npm-credentials.md
https://medium.com/npm-inc/security-in-the-js-community-4bac032e553b

_Slides aren't ready yet. No live coding or audio necessary._

**Thomas Hunter II**: Thomas is the author of Advanced Microservices and is a prolific public speaker with a passion for reducing complex problems into simple language and diagrams. His career includes working at Fortune 50's in the Midwest, co-founding a successful startup, and everything in between.

**Comment by tlhunter** [comment]
I'm free on April 4th (and April 11th)

**Comment by Trewaters** [comment]
@tlhunter I am putting you on the calendar for April 4th. Happy to have you talk. I enjoy your material.

@paulgrock please label this talk for April meetup. Thanks!

**Comment by tlhunter** [comment]
@Trewaters I renamed the talk from "Practical Attacks..." to "Real World Attacks..."

**Comment by Trewaters** [comment]
I will update that once we get the details published. Sorry we are little behind on adding the Meetup details at the moment. But coming soon.

**Comment by tlhunter** [comment]
It's all good. Thanks
