### ISSUE TITLE
Talk proposal: Testing apps with third-party API integrations

### ISSUE THREAD

**Issue by mikesol** [sfnode/sfnode#98]
**Testing apps with third-party API integrations**

In this talk we will examine strategies and best practices to develop and test node apps that make heavy use of third-party API integrations.  As reliance on third-party services becomes more and more prevalent in the node ecosystem, developers need cost-effective, secure, reliable and fast ways to mock these services for both dev/staging environments and testing.

We will start with looking at [nock](https://github.com/nock/nock), and open-source mocking solution for local development, and move onto [unmock](https://github.com/unmock/unmock-js) which provides mocks-as-a-service of popular APIs.

The session will have live coding for both nock and unmock using express to create a simple microservice and jest for testing.  It will also present several popular design patterns for isolating and testing third-party integrations as well as strategies for integration testing apps that rely on third-party APIs, including corner-case and error testing.

The proposal is for the **Thursday, February 7th Meetup** at Braintree.

Presenters will be myself (Mike Solomon - unmock.io) and I will invite Matt Levy (Twilio), Dan Shaw (PayPal) and others to chime in about the importance of testing third-party integrations and the emerging ecosystem of developer sandbox environments for API testing.

**Comment by paulgrock** [comment]
@mikesol Could you provide a bio for yourself so we can add it to the meetup page?

**Comment by mikesol** [comment]
<bio>
Mike Solomon is the founder and CEO of Meeshkan (meeshkan.com), a Helsinki-based DevOps company.  A music major at Stanford University, Queen's University Belfast and the University of Florida, Mike has been a guest researcher at the University of Paris VI and has held the post of artistic director of the Ensemble 101 (ensemble101.fr) from 2011 until the present day.  While working at the IRCAM as a computer music designer, he fell in love with Machine Learning and founded Meeshkan to ease several DevOps pain points in the ML pipeline.  Since then, Meeshkan has expanded to other areas of DevOps, including API testing with unmock (unmock.io).
</bio>
Thanks!

**Comment by Trewaters** [comment]
See you tonight. If you have questions you can reach us through the meetup comments, or if you have any of the organizer's contact info.
