### ISSUE TITLE
Talk proposal: Serverless with Apache Openwhisk

### ISSUE THREAD

**Issue by lidderupk** [sfnode/sfnode#99]
### Dive into JavaScript serverless with Apache Openwhisk 
Let's dive into Serverless concepts including actions, triggers, rules and event driven paradigm on the OpenWhisk Serverless open source platform. We will use the `wsk` command-line tool to create and organize JavaScript functions in packages that can be run on demand. The talk will include current landscape of serverless, common pitfalls and next steps for interested audience who want to venture deeper. There will be live coding and plenty of examples.

Apache OpenWhisk (Incubating) is an open source, distributed Serverless platform that executes functions (fx) in response to events at any scale. OpenWhisk manages the infrastructure, servers and scaling using Docker containers so you can focus on building amazing and efficient applications. 

### About Upkar
Upkar Lidder is a Full Stack Developer and Data Wrangler with a decade of development experience in a variety of roles. He can be seen speaking at various conferences and participating in local tech groups and meetups. He is currently curious about magic behind Machine Learning and Deep Learning, specifically use of NLP in chatbots. Upkar went to graduate school in Canada and currently resides in the United States.
Twitter: lidderupk

Logistics:
### Url to slides or github (either now or can be posted in meetup comments later)
https://www.slideshare.net/UpkarLidder/serverless-sfjavascript

### Are you going to be live coding?
Yes

### Do you need audio from your computer?
No

### Comments
I have presented this talk at Denver, Boulder and San Francisco meetups and will be hosting a workshop on the same at ForwardJS (https://forwardjs.com/schedule#lecture-431). Additionally my employer, IBM, is able to sponsor food for the evening or host at our partner spaces (Galvanize and Wework). The talk does not promote or mention IBM except that I work there and will be focused on opensource solutions. Happy to discuss timeline if you think this is a good fit with the meetup audience.

**Comment by Trewaters** [comment]
Sorry that we have not responded to your request yet. We are interested and will get back to you soon.

**Comment by Trewaters** [comment]
We have availability for folks to speak starting in June. It could possibly be earlier if space opens up. Please post if June is good for you.
Thanks!

**Comment by lidderupk** [comment]
June works. Also happy to present earlier if spots open. Look forward to it !

**Comment by Trewaters** [comment]
Thanks! I added you to June and if something opens up for sooner I will keep you in mind.

**Comment by lidderupk** [comment]
@Trewaters, how long will the talk be ?  I have done lightning talks as well as full day workshops with openwhisk.  I will prepare accordingly. Thanks again for fitting me in.

**Comment by Trewaters** [comment]
@lidderupk sorry for the delayed response.

Our talks are limited to 30 minutes, including equipment setup.

**Comment by lidderupk** [comment]
Thank you @Trewaters ! Looking forward to speaking with the group.

**Comment by Trewaters** [comment]
@lidderupk would you still be available for June 6th, Thursday eve?

**Comment by lidderupk** [comment]
@Trewaters, I am trying to make June 6 work. I should know by EOD PST today. when is the next available date ?

**Comment by Trewaters** [comment]
@lidderupk the next available speaking date would be August 1st.

Keep me updated. If you can't make June work I will ask around for someone to fill that spot.

Good luck!

**Comment by lidderupk** [comment]
Hi @Trewaters, 

I would like to switch to August. Thank you so much for giving me the option to postpone.

Upkar.

**Comment by Trewaters** [comment]
Roger that. Looking forward to it!

**Comment by Trewaters** [comment]
Hi Upkar! How are you feeling? We have you in the line up for next month at GitHub.

I would love to talk to you about IBM hosting a future meetup, if that offer is still available?

**Comment by lidderupk** [comment]
Thank you @Trewaters! I am still good for August 1.
I am working with my team to see if we can host you. The response has been positive. Looking forward to chatting with you on this topic.

**Comment by Trewaters** [comment]
That is super great news, we can use the support!

Sorry for my delayed response. I was on vacation for a week. I am back to the Real World now.

**Comment by lidderupk** [comment]
@Trewaters, what is the best channel to talk about space? I have some updates. Thanks!

**Comment by Trewaters** [comment]
Our email is Teamsfnode@gmail.com,  just address me and I will know.

Thanks so much!
